innovationacademy-kr/Cabi

- backend/controllers/routers/user.ts
- frontend/src/component/CabinetBox.tsx
- frontend/src/component/Carousel.tsx
✅  update user router and cabinet box
> ✅  update user router and cabinet box

- frontend/src/component/Carousel.tsx
- frontend/src/component/carousel.css
> 🎨  update cabinet grid #63

- backend/controllers/routers/route.ts
> 🔨  invalid token error #68

- frontend/package-lock.json
- frontend/src/pages/Return.tsx
🐛  fix: extension button error
* 연장하기 조건 수정
> 🐛  fix: extension button error #83

- backend/controllers/routers/eventRouter.ts
- backend/models/eventModel.ts
🐛  update time conditions for event
* Date 객체의 시간이 2022년 5월 16일 18시 00분 00초로 되어 있었습니다.
* 한국 기준 오전 9시로 시간을 수정하기위해 09시로 수정했습니다.
> 🐛  update time conditions for event

- frontend/src/event/EventType.tsx
- frontend/src/types/cabinetTypes.tsx
- frontend/src/types/userTypes.tsx
> 🏷️  fix types to interfaces

- frontend/src/main.tsx
> 🐛  hide subscribe

- backend/models/dbModel.ts
- backend/models/queryModel.ts
* mariaDB version up
* lent_log 외래키 삭제
* user time stamp 컬럼 추가
> 👍 성공적 첫 서버점검

- backend/controllers/routers/eventRouter.ts
- backend/models/eventModel.ts
- frontend/src/modal/ReturnEventModal.tsx
- frontend/src/modal/returnEventModal.css
- frontend/src/pages/Lent.tsx
- frontend/src/pages/Return.tsx
- package-lock.json
✨  update Event Modal in Return page
> ✨  update Event Modal in Return page

- backend/controllers/middleware/emailerMiddleware.ts
- backend/controllers/middleware/slackMiddleware.ts
- backend/models/types.ts
✅  update emailing system
✅  change types to interfaces
> ✅  update emailing system

- backend/controllers/middleware/emailerMiddleware.ts
> 🧪  test for email log

- backend/controllers/middleware/passportMiddleware.ts
- backend/models/dbModel.ts
- backend/models/eventModel.ts
- backend/models/queryModel.ts
- backend/models/slackModel.ts
🚚  change console.log to console.error
🚚  remove okPacket from pm2 log
> 🚚  change console.log to console.error

- backend/controllers/middleware/authMiddleware.ts
- backend/controllers/middleware/jwtMiddleware.ts
- backend/controllers/middleware/passportMiddleware.ts
- backend/controllers/routers/authRouter.ts
- backend/controllers/routers/eventRouter.ts
🔨  add new conditions in authCheck
📝  write remarks on middlewares
> 🔨  add new conditions in authCheck

- backend/controllers/middleware/authMiddleware.ts
- backend/models/types.ts
🏗️  add conditions for jwt and session
> 🏗️  add conditions for jwt and session

- backend/controllers/middleware/authMiddleware.ts
> 🐛  update authMiddleware

- backend/controllers/middleware/passportMiddleware.ts
- backend/controllers/routers/apiRouter.ts
> 🐛  update jwt value error

- backend/controllers/middleware/passportMiddleware.ts
> 🐛  update passport middleware

- backend/controllers/routers/apiRouter.ts
- backend/models/banModel.ts
- backend/models/dbModel.ts
- backend/models/queryModel.ts
- backend/models/types.ts
- frontend/src/modal/LentModal.tsx
- frontend/src/pages/Lent.tsx
✨ 사물함 대여 조건 추가
✨ 사물함 대여시 사물함 상태 조건 추가!
> ✨ 사물함 대여 조건 추가

- package-lock.json
- package.json
- src/cabinet/cabinet.controller.ts
> V2.0.0 #api2

- src/ban/ban.module.ts
- src/ban/guard/ban-check.guard.ts
- src/ban/repository/ban.repository.ts
- src/ban/repository/rawquery.ban.repository.ts
BanCheckGuard를 만들었습니다.
적용 방법
1. BanCheckGuard를 사용하는 모듈에서 BanModule를 import 합니다.
2. useguard 를 다음과 같이 적용합니다.
`@UseGuards(JwtAuthGuard, BanCheckGuard)`
다음과 같이 적용하면 로그인 여부를 판단 후, 로그인한 사용자가 밴되었는지 체크합니다.
> feat: add bancheck guard

- src/auth/auth.module.ts
- src/auth/auth.service.ts
- src/cabinet/cabinet.controller.ts
- src/cabinet/cabinet.service.ts
- src/cabinet/dto/cabinet-lent-info.dto.ts
- src/cabinet/repository/cabinet.repository.ts
- src/cabinet/repository/rawquery.cabinet.repository.ts
- src/email/email.service.ts
> V2.0.0 #156

- .env.sample
- package-lock.json
- package.json
- src/auth/auth.controller.ts
- src/ban/ban.module.ts
- src/cabinet/cabinet.controller.ts
- src/config/configuration.ts
- src/email/email.service.ts
- src/event/event.controller.ts
- src/main.ts
> V2.0.0 #swagger

- src/cabinet/cabinet.controller.ts
- src/cabinet/cabinet.module.ts
- src/event/event.controller.ts
- src/event/event.module.ts
> #157 add guard

- .github/workflows/cicd.yaml
> fix: #177 add fe build

- .github/workflows/cicd.yaml
> dev to main

- .github/workflows/cicd.yaml
> fix: #177 dir

- frontend/src/component/Menu.tsx
- frontend/src/modal/ExtensionModal.tsx
- frontend/src/modal/LentModal.tsx
- frontend/src/modal/PasswordModal.tsx
- frontend/src/modal/ReturnModal.tsx
- frontend/src/network/axios/axios.custom.ts
- frontend/src/network/axios/axios.instance.ts
- frontend/src/pages/Lent.tsx
- frontend/src/pages/Return.tsx
#169 
- axios 추상화를 위해 기존에 컴포넌트 내에 위치하던 axios를 하나의 파일에서 관리
- /src/network/axios/axios.instance.ts 파일 생성 및 axios instance 생성
- /src/network/axios/axios.custom.ts 파일 생성 및 axios instance를 통한 axios custom 생성
- event/return api 주석 처리
- 추후 JWT refresh token이 적용되면 axios instance에서 처리하면 좋을 것 같습니다 :)
> refactor: axios

- frontend/src/component/CabinetBox.tsx
- frontend/src/component/Menu.tsx
- frontend/src/main.tsx
- frontend/src/pages/Lent.tsx
- frontend/src/redux/hooks.ts
- frontend/src/redux/slices/cabinetSlice.ts
- frontend/src/redux/slices/lentSlice.ts
- frontend/src/redux/slices/userSlice.ts
- frontend/src/redux/store.ts
#170 
redux-toolkit 적용하여 slice로 reducer 관리
/src/redux 폴더 생성 및 store, hooks 생성
/src/redux/slices 폴더 생성 및 reducer를 slice로 리팩토링
> refactor: redux

- frontend/src/component/CabinetBox.tsx
- frontend/src/component/Carousel.tsx
- frontend/src/component/Location.tsx
- frontend/src/component/Menu.tsx
- frontend/src/component/map/SeromFloor.tsx
- frontend/src/component/map/SeromSecondFloor.tsx
- frontend/src/modal/ContentsModal.tsx
- frontend/src/modal/ExtensionModal.tsx
- frontend/src/modal/LentModal.tsx
- frontend/src/modal/PasswordModal.tsx
- frontend/src/modal/ReturnModal.tsx
- frontend/src/pages/Lent.tsx
- frontend/src/pages/Return.tsx
- frontend/src/redux/slices/cabinetSlice.ts
- frontend/src/redux/slices/lentSlice.ts
- frontend/src/redux/slices/userSlice.ts
#171 
Component props의 any 타입 제거
Component props 타입 인터페이스화
> refactor: remove any type props

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/GlobalStyle.tsx
- frontend/src/component/Carousel.tsx
- frontend/src/component/Location.tsx
- frontend/src/component/Menu.tsx
- frontend/src/component/Question.tsx
- frontend/src/component/button/HomeButton.tsx
- frontend/src/component/button/MenuButton.tsx
- frontend/src/component/button/QuestionButton.tsx
- frontend/src/component/menu.css
- frontend/src/component/question.css
- frontend/src/pages/Lent.tsx
1. React child key 추가
2. 일부 Button Component 분리
> refactor: apply atomic

- backend/src/auth/repository/rawquery.auth.repository.ts
- backend/src/blackhole/blackhole.module.ts
- backend/src/blackhole/blackhole.service.ts
- backend/src/cabinet/cabinet.controller.ts
- backend/src/cabinet/repository/rawquery.cabinet.repository.ts
- backend/src/user/dto/user.dto.ts
> :bug: fix unexpected exception #191

- frontend_v3/.eslintrc.cjs
- frontend_v3/src/components/atoms/buttons/Button.tsx
- frontend_v3/src/components/atoms/inputs/Input.tsx
- frontend_v3/src/components/organisms/EditInput.tsx
- frontend_v3/src/components/templates/Footer.tsx
- frontend_v3/src/components/templates/LentCabinet.tsx
- frontend_v3/src/components/templates/LentInfo.tsx
- frontend_v3/src/components/templates/Login.tsx
- frontend_v3/src/pages/Main.tsx
> fe_ve: apply folder_tree

- frontend_v3/package-lock.json
- frontend_v3/package.json
- frontend_v3/src/App.tsx
- frontend_v3/src/components/templates/CabinetTemplate.tsx
- frontend_v3/src/components/templates/Footer.tsx
- frontend_v3/src/components/templates/FooterTemplate.tsx
- frontend_v3/src/components/templates/LentCabinet.tsx
- frontend_v3/src/components/templates/LentInfo.tsx
- frontend_v3/src/components/templates/LentTemplate.tsx
- frontend_v3/src/components/templates/Login.tsx
- frontend_v3/src/components/templates/LoginTemplate.tsx
- frontend_v3/src/pages/Lent.tsx
- frontend_v3/src/pages/Login.tsx
- frontend_v3/src/pages/Main.tsx
#205 
- Login, Main, Lent page에 대한 Route를 추가하였습니다.
- 기존 Page name 수정.
- Main -> Login
- Lent -> Main
- Return -> Lent
> ✨Connect Route && Rename Template and Page

- frontend_v3/package-lock.json
- frontend_v3/package.json
- frontend_v3/src/components/atoms/buttons/MenuButton.tsx
- frontend_v3/yarn.lock
> fe_v3: menu button

- frontend_v3/src/App.tsx
- frontend_v3/src/components/templates/FooterTemplate.tsx
- frontend_v3/src/pages/Login.tsx
- frontend_v3/src/styles/GlobalStyle.tsx
#207 
```ts
import FooterTemplate from "../components/templates/FooterTemplate";
```
- page 내 template가 필요할 때 사용하시면 될 것 같습니다.
- GlobalStyle에 배경에 필요한 Body를 적용시켰습니다.
> ✨ Apply FooterTemplate

- frontend_v3/src/components/atoms/buttons/ReturnButton.tsx
> fe_v3: return button

- frontend_v3/src/components/atoms/buttons/CabinetBoxButton.tsx
- frontend_v3/src/pages/Main.tsx
#204 
CabinetBox Button 만들었습니다.
조건에 따른 클릭 및 클릭 이벤트 핸들러 추가 필요합니다.
> fe_v3/cabinet box button

- frontend_v3/src/components/atoms/buttons/SlideButton.tsx
#204 
slideButton 추가
Carousel 구현 후 클릭 이벤트 핸들러 내 로직 추가 필요
> Fe v3/slide button

- frontend_v3/src/components/atoms/buttons/SectionButton.tsx
> Fe v3/section button

- frontend_v3/src/components/atoms/buttons/FloorButton.tsx
MUI ButtonGroup 및 Button으로 층 이동 버튼 구현했습니다.
- 현재 건물 위치 알려주는 l_idx 변수명 더 구체적으로 변경하면 좋을 것 같습니다
- location 변경 시 setLidx 함수를 통해 l_idx가 변경되고 있어, 버튼이 아닌 다른 컴포넌트에서 이 상태를 관리하도록 변경하는 게 좋을 것 같습니다
> fe_v3/Floor Button

- frontend_v3/src/components/atoms/buttons/BuildingButton.tsx
#204 
- 차후 새롬관, 마루관에 따라 다르게 보여줘야할 경우 건물의 정보를 받아와야될 것 같습니다
- 현재는 새롬관(default)만 존재하므로 고려하지 않았습니다.
> fe_v3/BuildingButton

- frontend_v3/src/components/atoms/modals/GuideBox.tsx
- frontend_v3/src/components/atoms/modals/GuideModal.tsx
MUI `modal` 및 `box` 사용하여 가이드 모달 및 박스 컴포넌트 만들었습니다.
> fe_v3/Guide Modal and Guide Box

- frontend_v3/src/components/atoms/modals/GuideBox.tsx
#231 
GuideBox
- 글씨체 적용이 필요합니다.
- 향후 안내 사항을 읽은 것에 대한 체크 여부가 필요할 경우를 대비하여 CheckButton을 사용하였습니다.
> fe_v3/guide box

- backend/src/dto/cabinet.dto.ts
- backend/src/dto/cabinet.extend.dto.ts
- backend/src/dto/lent.dto.ts
- backend/src/dto/request/update.cabinet.update.request.dto.ts
- backend/src/dto/response/cabinet.info.response.dto.ts
- backend/src/dto/response/lent.info.response.dto.ts
- backend/src/dto/response/my.cabinet.info.response.dto.ts
- backend/src/dto/response/space.data.response.dto.ts
- backend/src/dto/space.data.dto.ts
- backend/src/dto/user.ban.dto.ts
- backend/src/dto/user.dto.ts
- backend/src/dto/user.over.dto.ts
- backend/src/dto/user.session.dto.ts
- backend/src/enum/lent.type.enum.ts
> #215 DTO 추가

- backend/Dockerfile
- backend/database/42cabi_v3_test.sql
- backend/database/init.sh
introduce docker setting in 42cabi_v3 #234
> :sparkles: introduce docker setting in 42cabi_v3 #234

- backend/src/config/typeorm.config.ts
fix username in typeorm.config #247
> :bug: fix username in typeorm.config #247

- backend/src/entities/cabinet.entity.ts
add enum field in lent_type field #247
> :bug: add enum field in lent_type field #247

- backend/src/entities/event.entity.ts
> :fire: rm event entity #247

- frontend_v3/src/components/atoms/buttons/MenuButton.tsx
- frontend_v3/src/components/templates/CabinetTemplate.tsx
- frontend_v3/src/network/axios/axios.custom.ts
- frontend_v3/src/pages/Main.tsx
- /src/components/templates/CabinetTemplate.tsx
- MainSection 아래에 Nav, Carousel, Question section으로 구분
- /src/components/atoms/buttons/MenuButton.tsx
- handleReport, handleLogout 구현
- /src/network/axios/axios.custom.ts 
- Method의 형태를 API 명세에 따라 POST에서 GET으로 변경
> fe_v3/MainTemplate

- backend/database/42cabi_v2_test.sql
- backend/database/init.sh
- backend/docker-compose.yaml
- backend/src/auth/repository/rawquery.auth.repository.ts
- backend/src/ban/repository/rawquery.ban.repository.ts
- backend/src/blackhole/repository/rawquery.blackhole.repository.ts
- backend/src/cabinet/repository/rawquery.cabinet.repository.ts
- backend/src/config/configuration.ts
- backend/src/config/typeorm.config.ts
- backend/src/event/repository/rawquery-event.repository.ts
- frontend_v3/yarn.lock
> :ambulance: add v2 db #258

- dev/configure.conf
- frontend_v3/package.json
- frontend_v3/vite.config.ts
add frontend_v3 reverse proxy setting #266
> :sparkles: add frontend_v3 reverse proxy setting #266

- backend/database/42cabi_v3_test.sql
- backend/src/entities/ban.log.entity.ts
- backend/src/entities/cabinet.entity.ts
- backend/src/entities/lent.entity.ts
- backend/src/entities/lent.log.entity.ts
- backend/src/entities/user.entity.ts
> :bug: fix: entities relationship

- backend/src/config/configuration.ts
- backend/src/entities/user.entity.ts
- backend/src/v3/cabinet/cabinet.info.controller.ts
- backend/src/v3/cabinet/cabinet.info.service.ts
- backend/src/v3/cabinet/repository/cabinet.info.repository.interface.ts
- backend/src/v3/cabinet/repository/cabinet.info.repository.ts
- backend/src/v3/lent/lent.controller.ts
- backend/src/v3/lent/lent.module.ts
- backend/src/v3/lent/lent.service.ts
- backend/src/v3/lent/repository/lent.repository.interface.ts
- backend/src/v3/lent/repository/lent.repository.ts
> Be v3/cabinet

- backend/src/config/configuration.ts
- backend/src/entities/user.entity.ts
- backend/src/v3/cabinet/cabinet.info.controller.ts
- backend/src/v3/cabinet/cabinet.info.service.ts
- backend/src/v3/cabinet/repository/cabinet.info.repository.interface.ts
- backend/src/v3/cabinet/repository/cabinet.info.repository.ts
- backend/src/v3/lent/lent.controller.ts
- backend/src/v3/lent/lent.module.ts
- backend/src/v3/lent/lent.service.ts
- backend/src/v3/lent/repository/lent.repository.interface.ts
- backend/src/v3/lent/repository/lent.repository.ts
Reverts innovationacademy-kr/42cabi#277
> Revert "Be v3/cabinet"

- dev/configure.conf
nginx.conf /v3/api endpoint를 추가했습니다.
> :sparkles: add new endpoint /v3/api in nginx.conf

- frontend_v3/src/components/atoms/buttons/CabinetBoxButton.tsx
- frontend_v3/src/components/atoms/modals/LentBox.tsx
- frontend_v3/src/components/atoms/modals/LentModal.tsx
- frontend_v3/src/components/atoms/modals/ReturnBox.tsx
- frontend_v3/src/components/organisms/Slide.tsx
- frontend_v3/src/mock/CabinetBoxButton.mock.ts
- frontend_v3/src/themes/cabinetColor.ts
- frontend_v3/src/types/dto/cabinet.dto.ts
- frontend_v3/src/types/dto/lent.dto.ts
- frontend_v3/src/types/dto/user.dto.ts
- frontend_v3/src/types/enum/cabinet.status.enum.ts
- frontend_v3/src/types/enum/cabinet.type.enum.ts
> fe_v3: apply interface

- frontend_v3/src/network/axios/axios.custom.ts
#283 
- GET /v3/api/cabinet_info
- space 정보 호출
- GET /v3/api/cabinet_info/{location}/{floor}
- 층 정보 호출
- GET /v3/api/cabinet_info/{cabinet_id}
- 사물함 정보 호출
- POST /v3/api/lent/{cabinet_id}
- GET /v3/api/my_lent_info
- 자기 자신의 대여 정보를 가져옴.
> fe_v3/v3Axios

- backend/src/v3/lent/lent.service.ts
Inject repository in lentService #259
> :ambulance: Inject repository in lentService #259

- backend/src/auth/auth.controller.ts
- frontend_v3/src/components/atoms/buttons/CabinetBoxButton.tsx
- frontend_v3/src/components/atoms/buttons/MenuButton.tsx
- frontend_v3/src/components/templates/CabinetTemplate.tsx
- frontend_v3/src/network/axios/axios.custom.ts
- frontend_v3/src/redux/slices/userSlice.ts
- frontend_v3/src/types/dto/user.dto.ts
- my_info API로 메인페이지 처음 렌더링 시 로그인된 유저 정보 불러와 리덕스에 저장합니다. (기존에 저장되어 있는 유저 정보가 있다면 API를 호출하지 않습니다)
- 기존 로그아웃 버튼이 이벤트 핸들러에서 `/api/logout` URL에 대해 axios 호출로 get 요청을 보내던 것을 `href` 로 연결되도록 수정했습니다.
- 로그인 버튼과 같은 방식입니다.
> MyInfo API Added / Logout Button Edited

- backend/package.json
- backend/src/auth/auth.controller.ts
- frontend_v3/src/components/atoms/buttons/CabinetBoxButton.tsx
- frontend_v3/src/components/atoms/buttons/MenuButton.tsx
- frontend_v3/src/components/templates/CabinetTemplate.tsx
- frontend_v3/src/network/axios/axios.custom.ts
- frontend_v3/src/redux/slices/userSlice.ts
- frontend_v3/src/types/dto/user.dto.ts
- 이용 안내 제거 
- 사물함 신청 추가
- slack에  기존 동아리 사물함 신청 링크 사용
> Fe v3/menu item

- frontend_v3/src/components/atoms/buttons/FloorButton.tsx
- frontend_v3/src/components/atoms/buttons/LocationButton.tsx
- frontend_v3/src/components/organisms/Carousel.tsx
- frontend_v3/src/components/organisms/SlideContainer.tsx
- frontend_v3/src/components/templates/CabinetTemplate.tsx
- frontend_v3/src/types/dto/cabinet.dto.ts
- useAppDispatch, useAppSelector 제거
- v3 API  axiosLocationFloor, axiosCabinetByLocationFloor 추가 및 Location, FloorButton에 적용
> fe_v3/MainTemplateAPI

- frontend_v3/src/components/atoms/inputs/LentTextField.tsx
- frontend_v3/src/components/organisms/LentInfo.tsx
- frontend_v3/src/network/axios/axios.custom.ts
- 캐비넷 메모, 타이틀 업데이트 API의 URL 추가했습니다.
- TestTextField 이름 LentTextField로 변경했습니다.
> fe_v3/LentPageAPI

- backend/src/dto/cabinet.dto.ts
- backend/src/v3/cabinet/cabinet.info.controller.ts
- backend/src/v3/cabinet/repository/cabinet.info.repository.ts
cabinet 모듈의 HTTP Response Code를 수정하였으며 누락된 section 필드를 추가하였습니다.
> fix: HTTP Status Code & add section field

- backend/src/dto/response/cabinet.per.section.response.dto.ts
- backend/src/v3/cabinet/cabinet.info.controller.ts
- backend/src/v3/cabinet/cabinet.info.service.ts
- backend/src/v3/cabinet/repository/cabinet.info.repository.ts
- backend/src/v3/cabinet/repository/interface.cabinet.info.repository.ts
프론트앤드 분들의 요청에 따라 `/v3/api/cabinet_info/{location}/{floor}` 리스폰스를 수정하였습니다.
> fix: cabinet info & logout

- frontend_v3/src/components/atoms/buttons/CabinetBoxButton.tsx
- frontend_v3/src/components/atoms/modals/LentBox.tsx
- frontend_v3/src/components/organisms/Carousel.tsx
- frontend_v3/src/components/organisms/Slide.tsx
- frontend_v3/src/components/organisms/SlideContainer.tsx
- frontend_v3/src/components/templates/CabinetTemplate.tsx
- frontend_v3/src/types/dto/cabinet.dto.ts
1. v3/api/lent/{cabinet_id} API 적용
2. v3/api/cabinet_info/{location}/{floor} API 적용
3. MockData를 실제 캐비넷 데이터로 변경
> fe_v3: apply cabinet API for Carousel

- frontend_v3/src/components/templates/LentTemplate.tsx
#315 
- 차후 state에 대한 처리가 완료된 후 사용하기 위해 주석 처리.
> fix lentTemplate validation logic

- frontend_v3/package-lock.json
- frontend_v3/package.json
- frontend_v3/src/main.tsx
- frontend_v3/src/redux/store.ts
- frontend_v3/yarn.lock
> fe_v3: apply redux-persist

- frontend_v3/src/pages/Lent.tsx
- frontend_v3/src/pages/Login.tsx
- frontend_v3/src/pages/Main.tsx
Redux 내 user 정보 유/무에 따른 navigating
> fe_v3: navigate by userInfo in redux

- frontend_v3/src/components/atoms/buttons/MenuButton.tsx
- frontend_v3/src/pages/Lent.tsx
- frontend_v3/src/pages/Login.tsx
- frontend_v3/src/pages/Main.tsx
기존 a 태그로 동작하던 로그아웃에 API 적용
API를 통해 로그아웃에 성공할 경우, Redux 내 user 정보 초기화 및 로그인 페이지로 네비게이팅
> Fe v3/logout

- frontend_v3/.eslintrc.cjs
- frontend_v3/src/components/atoms/buttons/MenuButton.tsx
- frontend_v3/src/components/atoms/buttons/ReturnButton.tsx
- frontend_v3/src/components/templates/LentTemplate.tsx
- frontend_v3/src/network/axios/axios.custom.ts
- frontend_v3/src/pages/Lent.tsx
- frontend_v3/src/pages/Login.tsx
- frontend_v3/src/pages/Main.tsx
- frontend_v3/src/redux/slices/userSlice.ts
1. v3/api/lent/return custom axios 생성
2. redux 내 유저의 캐비넷 정보 변경하는 액션 생성
3. 반납버튼 클릭 시, api 요청 및 요청 성공 시, 유저의 캐비넷 정보 -1로 변경
> Fe v3/return cabinet

- frontend_v3/.eslintrc.cjs
- frontend_v3/src/components/atoms/buttons/MenuButton.tsx
- frontend_v3/src/components/atoms/buttons/ReturnButton.tsx
- frontend_v3/src/components/atoms/modals/LentBox.tsx
- frontend_v3/src/components/organisms/Slide.tsx
- frontend_v3/src/components/templates/LentTemplate.tsx
- frontend_v3/src/network/axios/axios.custom.ts
- frontend_v3/src/pages/Lent.tsx
- frontend_v3/src/pages/Login.tsx
- frontend_v3/src/pages/Main.tsx
- frontend_v3/src/redux/slices/userSlice.ts
1. 캐비넷 렌트 시, redux 내 user의 캐비넷 정보 변경을 위한 props 추가 (cabinet_id)
2. 캐비넷 렌트 성공 시, redux 내 user의 캐비넷 정보 변경
> Fe v3/lent cabinet

- frontend_v3/.eslintrc.cjs
- frontend_v3/src/components/atoms/buttons/MenuButton.tsx
- frontend_v3/src/components/atoms/buttons/ReturnButton.tsx
- frontend_v3/src/components/atoms/modals/LentBox.tsx
- frontend_v3/src/components/organisms/Slide.tsx
- frontend_v3/src/components/templates/LentTemplate.tsx
- frontend_v3/src/network/axios/axios.custom.ts
- frontend_v3/src/pages/Lent.tsx
- frontend_v3/src/pages/Login.tsx
- frontend_v3/src/pages/Main.tsx
- frontend_v3/src/redux/slices/userSlice.ts
메뉴 버튼의 `내 사물함` 클릭 시, redux 내 유저의 사물함 대여 정보를 확인하여 lent 페이지로 이동
> Fe v3/move lent page

- backend/src/v3/cabinet/cabinet.info.controller.ts
- backend/src/v3/cabinet/cabinet.info.service.ts
- backend/src/v3/cabinet/repository/cabinet.info.repository.ts
- backend/src/v3/lent/lent.service.ts
- backend/src/v3/user/user.service.ts
1. try-catch 수정
2. abinetsPerSectionResponseDto 배열 리턴 시 cabinet_num 순서대로 정렬되도록 수정
3. 400 bad request 처리
> Be v3/#300

- .gitignore
- backend/database/init.sh
- frontend_v3/package-lock.json
- frontend_v3/yarn.lock
> :sparkles: add sample data settings #296

- backend/Dockerfile
- backend/database/init.sh
- backend/src/main.ts
fix bug in database init.sh #296
> :bug: fix bug in database init.sh #296

- backend/src/config/configuration.ts
- backend/src/main.ts
- frontend_v3/src/network/axios/axios.instance.ts
fix CORS error in localhost #349
> :bug: fix CORS error in localhost #349

- frontend_v3/src/pages/Lent.tsx
#315 
- login 하지 않은 상태에서 lent page 접속 시
- login은 했지만 사물함을 대여하지 않은 상태에서 lent page 접속 시
- 상기 경우 navigate("/")
> fe_v3/lentPageNavigate

- backend/src/auth/auth.controller.ts
#356 PR에 남겨주신 의견에 따라 리다이렉트 경로를 메인으로 고정하였습니다.
> fix: #356 redirect

- frontend_v3/src/App.tsx
- frontend_v3/src/network/ga/gaTracker.ts
#354 
- 42cabi 공용 아이디(gmail)에 GA를 연동하였습니다.
- localhost의 로그는 추적하지않고,  dev 서버만 추적하도록 작성하였습니다.
- 배포 전 본 서비스에 적용하려면 새 id를 생성하여 적용해야 본 서비스의 정확한 통계를 확인할 수 있을 것 같습니다.
> fe_v3/GoogleAnalytics

- backend/src/main.ts
- backend/src/v3/lent/lent.controller.ts
- backend/src/v3/lent/lent.service.ts
- backend/src/v3/lent/repository/lent.repository.interface.ts
- backend/src/v3/lent/repository/lent.repository.ts
- 공유 사물함 대여 시 만료 시간을 null로 설정하고, 사물함이 FULL이 되면 만료 시간이 설정되도록 수정.
- 공유 사물함 중도 이탈 시 패널티를 부과하는 로직 추가. (함수 구현은 banService에서 필요함)
> :zap: set expire time when cabinet is FULL #330

- frontend_v3/src/components/atoms/modals/LentBox.tsx
LentBox 내 Typography에 대한 unique key error 수정했습니다.
추가로 sharedCabinetMessage, personalCabinetMessage에 대한 타입 지정 추가하였습니다.
> fix: fix unique key error

- frontend_v3/src/components/atoms/buttons/MapButton.tsx
- frontend_v3/src/components/organisms/Carousel.tsx
- frontend_v3/src/components/organisms/SectionMap.tsx
- frontend_v3/src/components/organisms/SlideContainer.tsx
- frontend_v3/src/components/templates/CabinetTemplate.tsx
#316 
Carousel의 첫 슬라이드로 적용될 SectionMap 제작했습니다.
Section 클릭 시, 해당 section의 캐비넷 슬라이드로 이동하게 됩니다.
> fe_v3/section map

- frontend_v3/src/components/atoms/modals/LentBox.tsx
> refactor: apply response message for alert

- backend/src/v3/cabinet/cabinet.info.controller.ts
> Add: Guard #388

- backend/src/dto/cabinet.dto.ts
update API Swagger field in cabinetStatus #330
> :memo: update API Swagger field in cabinetStatus #330

- backend/src/v3/cabinet/cabinet.info.service.ts
- backend/src/v3/user/repository/user.repository.interface.ts
- backend/src/v3/user/repository/user.repository.ts
- backend/src/v3/user/user.module.ts
- backend/src/v3/user/user.service.ts
내 사물함에서 사물함을 공유하는 유저의 정보를 볼 수 있도록 수정했습니다.
> 내 사물함에서 전체 대여자가 보이지 않는 이슈 해결

- backend/src/v3/lent/lent.component.ts
- backend/src/v3/lent/lent.service.ts
- backend/src/v3/lent/repository/lent.repository.interface.ts
- backend/src/v3/lent/repository/lent.repository.ts
fix bug remain title, memo when return #386
> :bug: fix bug remain title, memo when return #386

- frontend_v3/src/components/atoms/buttons/EditButton.tsx
- frontend_v3/src/components/atoms/inputs/LentTextField.tsx
- frontend_v3/src/components/atoms/modals/LentBox.tsx
- frontend_v3/src/components/organisms/LentInfo.tsx
- frontend_v3/src/components/organisms/Slide.tsx
- frontend_v3/src/components/templates/LentTemplate.tsx
- frontend_v3/src/types/dto/cabinet.dto.ts
- 사물함 대여 모달에서 **사물함 제목**이 보이지 않아 추가했습니다.
> fe_v3/LentBoxTitle

- frontend_v3/src/components/atoms/Spinner.tsx
- frontend_v3/src/components/organisms/SectionMap.tsx
main 페이지에 처음 접근하는 경우, /v3/api/cabinet_info/ API를 통해 sections 정보를 저장하는데 1000ms 이상의 시간이 소요됩니다.
사용자 경험을 위해 첫 페이지가 렌더되기 전 로딩중임을 알리는 스피너를 적용했습니다.
> fe_v3/spinner

- backend/src/v3/lent/lent.component.ts
`returnStateTransition` 에서 지금 보니 조건문이 잘못 작성된 부분이 있어 수정했습니다.
> :ambulance: hotfix condition check on return status transition

- .gitignore
- backend/package-lock.json
- backend/package.json
- backend/src/app.module.ts
- backend/src/main.ts
- backend/src/v3/ban/ban.service.ts
- backend/src/v3/ban/repository/ban.repository.interface.ts
- backend/src/v3/ban/repository/ban.repository.ts
- backend/src/v3/cabinet/cabinet.info.service.ts
- backend/src/v3/cabinet/repository/cabinet.info.repository.ts
- backend/src/v3/cabinet/repository/interface.cabinet.info.repository.ts
- backend/src/v3/lent/lent.component.ts
- backend/src/v3/lent/lent.mock.controller.ts
- backend/src/v3/lent/lent.service.ts
- backend/src/v3/lent/repository/lent.repository.interface.ts
- backend/src/v3/lent/repository/lent.repository.ts
- backend/src/v3/user/repository/user.repository.interface.ts
- backend/src/v3/user/repository/user.repository.ts
- backend/src/v3/user/user.service.ts
- backend/src/v3/utils/expired.checker.component.ts
#424 에서 언급드린 것 처럼 `@Transaction` 데코레이터로 트랜잭션을 관리해주는 모듈을 도입했습니다.
기존에 `QueryRunner`를 사용하던 부분은 모두 삭제처리했습니다!
> Transactional Decorator 추가

- .github/workflows/cicd.yaml
> fix: #428 CD Script

- backend/database/42cabi_v3_test.sql
- backend/src/entities/ban.log.entity.ts
반납 패널티로 인한 ban과 연체로 인한 ban을 나누기 위한 필드를 추가했습니다.
> Add: is_penalty field #439

- backend/src/ban/ban.module.ts
- backend/src/ban/ban.service.ts
- backend/src/ban/guard/ban-check.guard.ts
- backend/src/ban/repository/ban.repository.interface.ts
- backend/src/ban/repository/ban.repository.ts
기존
공유 사물함 72시간 내 반납 penalty를 받으면 개인 사물함도 빌리지 못하게 함.
변경
공유 사물함 72시간 내 반납 penalty를 받으면 개인 사물함은 빌릴 수 있으나 공유 사물함은 빌리지 못함.
> Be_v3/banguard

- frontend_v3/index.html
#458 
- 요청하신 Site 내 Title의 Name, Icon을 수정하였습니다.
> Fe v3/title name ico

- frontend_v3/src/components/atoms/inputs/LentTextField.tsx
- frontend_v3/src/components/atoms/modals/ReturnBox.tsx
- frontend_v3/src/components/organisms/LentInfo.tsx
- frontend_v3/src/components/templates/LentTemplate.tsx
반납 확인 모달에서, 사용자가 자신의 **대여일** 을 확인할 수 있도록 해당 데이터 추가했습니다. (#442)
> fe_v3/ReturnBoxLentDate

- backend/src/auth/auth.service.ts
- backend/src/blackhole/blackhole.service.ts
prevent run blackhole module when local #443
> :zap: prevent run blackhole module when local #443

- backend/database/42cabi_v3_test.sql
- backend/src/entities/user.entity.ts
추후 블랙홀 관리기능 개선을 위한 `blackhole_date` 컬럼을 추가하였습니다.
> add RDB column

- frontend_v3/src/components/atoms/modals/GuideModal.tsx
- alert 메세지 오타 수정하였습니다.
- 대여 완료 된 사물`합`입니다 -> 대여 완료 된 사물`함`입니다
> fe_v3/ModifiedGuideModal

- frontend_v3/src/components/atoms/buttons/MenuButton.tsx
- #492
오른쪽 상단 메뉴가 추가되었습니다(정지 해제)
> FEAT: add menu for delete panelty for beta test

- frontend_v3/.gitignore
- frontend_v3/src/components/atoms/modals/GuideBox.tsx
- frontend_v3/src/components/atoms/modals/LentBox.tsx
- frontend_v3/src/components/atoms/modals/LentModal.tsx
- frontend_v3/src/components/atoms/modals/QuestionTestModal.tsx
- frontend_v3/src/components/atoms/modals/ReturnBox.tsx
- #498 
기존에 대여 기간 관련된 안내가 하드 코딩으로 되어 있던 부분을 환경변수로 관리하도록 변경되었습니다.
> ENHANCEMENT: 대여 정책과 관련된 기간 환경변수로 관리

- frontend_v3/index.html
https://github.com/innovationacademy-kr/42cabi/issues/511
> 🐛 fix en->ko

- frontend_v3/index.html
Reverts innovationacademy-kr/42cabi#514
> revert main to dev

- backend/database/42cabi_v3_test.sql
- backend/src/app.module.ts
- backend/src/auth/auth.service.ts
- backend/src/auth/jwt/guard/jwtauth.guard.ts
- backend/src/auth/repository/auth.repository.ts
- backend/src/ban/ban.service.ts
- backend/src/ban/guard/ban-check.guard.ts
- backend/src/blackhole/blackhole.service.ts
- backend/src/cabinet/cabinet.info.service.ts
- backend/src/cabinet/repository/cabinet.info.repository.ts
- backend/src/dto/simple.cabinet.data.dto.ts
- backend/src/entities/cabinet.entity.ts
- backend/src/lent/lent.component.ts
- backend/src/lent/lent.mock.controller.ts
- backend/src/lent/lent.service.ts
- backend/src/lent/repository/lent.repository.ts
- backend/src/user/repository/user.repository.interface.ts
- backend/src/user/repository/user.repository.ts
- backend/src/user/user.service.ts
- backend/src/utils/email.sender.component.ts
- backend/src/utils/expired.checker.component.ts
> Add: cabinet status_note field #509

- backend/src/app.module.ts
- backend/src/main.ts
- backend/src/middleware/session-middleware.ts
helmet 미들웨어의 위치를 미들웨어 모듈로 옮겼습니다.
> middleware 위치 변경

- backend/src/dto/return.cabinet.data.dto.ts
- backend/src/lent/lent.component.ts
- backend/src/lent/lent.service.ts
- backend/src/lent/repository/lent.repository.interface.ts
- backend/src/lent/repository/lent.repository.ts
fix deadlock problem when return cabinet at the same time #532
> :bug: fix deadlock problem when return cabinet at the same time #532

- backend/src/app.module.ts
> remove: betatest module

- frontend_v3/src/components/atoms/buttons/MenuButton.tsx
- frontend_v3/src/components/organisms/LentInfo.tsx
- #551 
- 정지 해제 메뉴 삭제
- dev, main env 수정 -> 대여기간 개인 21일 ,공유 42일
- lent 페이지에 남은 대여 기간, 현재 연체 기간 표시 -> 이 부분 깔끔하게 작성하고 싶은데 조언 부탁드립니다..
> ENHANCEMENT: 정식 서비스 오픈 준비

- backend/.env.sample
- backend/src/config/configuration.ts
- backend/src/config/typeorm.config.ts
- backend/src/main.ts
- backend/src/utils/email.sender.component.ts
`TEST` 환경변수의 기능을 MAIL_SEND와 DEBUG_LOG로 분할하였습니다.
> fix: #557 env

- backend/src/utils/email.sender.component.ts
테스트 메일 송부 여부가 역으로 동작되는 문제를 수정하였습니다.
> hotfix: mail send bug

- .gitignore
- backend/package.json
- backend/src/app.module.ts
- backend/src/config/configuration.ts
#559에서 결정된대로 작업하였습니다.
가이드는 내일 중으로 작성하겠습니다!
> 프론트앤드 정적파일을 백앤드 소스폴더내 deploy에서 배포하도록 변경

- dev/configure.conf
localhost 메인에서 어드민으로 API 요청을 할 수 있도록 nginx.conf 수정 #578
> :wrench: 메인에서 어드민으로 API 요청을 할 수 있도록 nginx.conf 수정 #578

- .github/workflows/cicd.yaml
- backend/src/app.module.ts
- backend/src/auth/auth.controller.ts
- backend/src/auth/jwt/jwt.strategy.ts
- backend/src/lent/lent.controller.ts
- backend/src/main.ts
- backend/src/middleware/session-middleware.ts
lint check + CD PM2 프로세스 명 오타 수정 #580
> :lipstick: lint check #580

- frontend_v4/.eslintrc.json
- frontend_v4/package-lock.json
- frontend_v4/package.json
- frontend_v4/src/App.tsx
- frontend_v4/tsconfig.json
- frontend_v4/vite.config.ts
> Fe/dev/feat alias/#593

- frontend_v4/src/App.tsx
- frontend_v4/src/pages/HomePage.tsx
> [FE] v4 폴더 라우터 세팅

- frontend_v4/src/types/dto/cabinet.dto.ts
- frontend_v4/src/types/dto/lent.dto.ts
- frontend_v4/src/types/dto/user.dto.ts
- frontend_v4/src/types/enum/cabinet.status.enum.ts
- frontend_v4/src/types/enum/cabinet.type.enum.ts
> v3에서 사용하던 cabinet, user, lent Dto 및 CabinetStatus, CabinetType 그대로 가져왔습니다.
> [FE] FEAT: Dto 및 enum 타입 추가 #609

- frontend_v4/src/containers/CabinetListContainer.tsx
> [FE] FEAT: 사물함 구역  컨테이너 제작 #598

- frontend_v4/src/containers/ButtonContainer.tsx
- frontend_v4/src/containers/ModalContainer.tsx
> [FEAT] Create Button Component#599

- frontend_v4/src/index.css
공통으로 사용하는 css color 변수 추가했습니다.
간단한 사항이라 바로 머지하도록 하겠습니다.
> [FE] FEAT: index.css gray-color 변수 추가

- frontend_v4/src/containers/TopNavContainer.tsx
- frontend_v4/src/index.css
- frontend_v4/src/pages/HomePage.tsx
- frontend_v4/src/pages/LoginPage.tsx
- frontend_v4/src/pages/MainPage.tsx
- TopNavContainer 컴포넌트 추가
- 건물 이름 클릭 시 선택할 수 있는 모달 추가
> [FE] FEAT: Top Navi 컴포넌트 추가 #611

- frontend_v4/src/assets/images/club_circle.svg
- frontend_v4/src/assets/images/group_circle.svg
- frontend_v4/src/assets/images/single_circle.svg
- frontend_v4/src/containers/InfoContainer.tsx
- frontend_v4/src/pages/MainPage.tsx
> [FE] FEAT: 이용안내서 컴포넌트 추가 #618

- frontend_v4/src/containers/CabinetListContainer.tsx
> [FE] FIX: CabinetListContainer 수정

- frontend_v4/src/containers/CabinetListItemContainer.tsx
메인 페이지에서 SET_EXPIRED_AVAILABLE한 캐비넷의 아이콘 및 텍스트 색상을 수정하였습니다.
> [FE] BUG: SET_EXPIRE_AVAILABLE한 캐비넷 아이콘 및 색상 수정 #642

- frontend_v4/src/containers/CabinetInfoArea.tsx
- frontend_v4/src/containers/SectionPaginationContainer.tsx
- frontend_v4/src/pages/MainPage.tsx
> [FE] ETC: 우측 구역 컴포넌트 배치, 전체적으로 css 조정 #644

- frontend_v4/package-lock.json
- frontend_v4/package.json
- frontend_v4/src/main.tsx
recoil이 package.json에 추가되었습니다.
redux가 package.json에서 삭제되었습니다.
> [FE] FEAT: main.tsx에 recoil 코드 추가 #645

- frontend_v4/src/containers/CabinetListItemContainer.tsx
캐비닛 아이템에 마우스 오버 시 애니메이션 동작하도록 추가해봤습니다.
다른 버튼들에도 애니메이션 유사하게 적용한다면, 사이트의 UI/UX 일관성이 좋아질 것 같습니다
추후에 디테일 잡을 때 고려해보면 좋을 것 같네요!
> [FE] FEAT: 캐비닛 아이템 마우스 오버 시 애니메이션 개선 #647

- frontend_v4/src/components/CabinetColorTable.tsx
- frontend_v4/src/containers/LeftNavOptionContainer.tsx
- frontend_v4/src/pages/MainPage.tsx
> [FE] FEAT: 좌측 섹션 구역 네비게이션 추가 #611

- frontend_v4/src/containers/InfoContainer.tsx
- frontend_v4/src/containers/LeftNavContainer.tsx
- frontend_v4/src/containers/LeftNavOptionContainer.tsx
- frontend_v4/src/pages/HomePage.tsx
> [FE] FEAT: 왼쪽 네비게이션 라우팅 추가 #666

- frontend_v4/src/components/LoadingModal.tsx
- frontend_v4/src/pages/HomePage.tsx
> [FE] FEAT: loading 컴포넌트 추가 #668

- backend/src/auth/auth.controller.ts
- backend/src/auth/jwt/guard/jwtsign.guard.ts
- backend/src/utils/expired.checker.component.ts
- backend/src/utils/leave.absence.component.ts
- backend/src/utils/scheduling.component.ts
- backend/src/utils/utils.module.ts
#589 에 대한 PR입니다.
12/23(금) 회의에서 얘기했던대로 처리는 했지만, 비효율적으로 처리 되는 부분이 많아 나중에 리팩토링이 필요할 것 같습니다.
cron으로 스케줄링 하는 부분을 따로 컴포넌트로 만들었고 token을 발급받아 연체자에 대한 정보를 받아와서 휴학생인지를 판단한 후 반납처리 하도록 했습니다.
이 과정에서 연체된 lent를 확인하는 부분이 중복되므로 DB에서 lent list를 가져올 때 연체된 사물함만 가지고 오는 방식도 고려해봐야할 것 같습니다.
> [BE] FEAT: 휴학생 관련 기능 추가

- backend/src/config/typeorm.config.ts
> [BE] FIX: 오류 수정

- frontend_v4/src/api/axios/axios.custom.ts
v4 axios.custom.ts  파일 최신화 하였습니다.
Closes #688
> [FE] FIX: v4 axios.custom.ts 수정 #688

- backend/src/config/typeorm.config.ts
오타로 인해 원하는 대로 동작하지 않아서 수정했습니다.
> [BE] BUG: config 오타 수정 #673

- frontend_v4/src/components/SectionPagination.tsx
- frontend_v4/src/containers/SectionPaginationContainer.tsx
- frontend_v4/src/pages/MainPage.tsx
>왼쪽 section 바와 중앙 구역 상단 페이지네이션 바 동일하게 보이도록 수정.
기존 container에서 관리하던 기능적인 부분들을 component로 분리했습니다.
> [FE] FIX: Section Pagination 왼쪽바와 동기화, 기능부분 component로 분리 #691

- frontend_v4/src/components/CabinetInfoArea.tsx
- frontend_v4/src/types/dto/cabinet.dto.ts
>CabinetInfo Interface에 floor과 location 추가되고 해당 사항 우측 구역에도 반영되었습니다.
> [FE] FIX: cabinet_info API 변경된 response 반영 #702

- frontend_v4/src/components/HomeInfo.tsx
- frontend_v4/src/containers/HomeInfoContainer.tsx
- frontend_v4/src/pages/HomePage.tsx
InfoContainer -> HomeInfoContainer로 변경
components에 HomeInfo 파일 추가 후 기능 추가 했습니다.
기능은
floors 값을 받아서 index 0번 값을 넣어서 main으로 네비게이팅해주었습니다.
> [FE] FEAT: homeInfo "시작하기" 버튼 기능 추가, 파일이름 변경 #705

- frontend_v4/src/components/LoadingModal.tsx
- frontend_v4/src/index.css
- frontend_v4/src/pages/LoginPage.tsx
login 버튼 클릭 시 로딩중 표시 기능 추가 했습니다.
Closes #716
> [FE] login 버튼 클릭 시 로딩중 표시 #716

- frontend_v4/src/containers/HomeInfoContainer.tsx
- [] FEAT : 새로운 기능 추가 및 개선
홈에 [대여 시작하기] 버튼 [시작하기] 로 수정
클릭 시 "/main"으로 네비게이팅하도록 정리하였습니다.
> [FE] FIX: 홈에 [대여 시작하기] 버튼 이름 수정 + 기능 붙이기 #718

- frontend_v4/src/containers/LeftNavContainer.tsx
> [FE] BUG: 로그아웃 버튼 클릭 시 login으로 네비게이팅 #723

- frontend_v4/src/containers/MemoModalContainer.tsx
- frontend_v4/src/containers/ModalContainer.tsx
zindex -> z-index로 수정하였고 정상적으로 모든 요소보다 상위에 존재하는 것을 확인했습니다. 그 외 추가로 스타일드 컴포넌트 이름에 오타를 발견하였고 수정하였습니다. 
closes #727
> [FE] 모달창 배경 z-index 미적용 관련 오타 수정

- frontend_v4/src/containers/ButtonContainer.tsx
- frontend_v4/src/containers/CabinetInfoAreaContainer.tsx
- frontend_v4/src/containers/MemoModalContainer.tsx
- frontend_v4/src/containers/ModalContainer.tsx
FEAT: 버튼 gary line 테마 추가 후, 다른 테마 이름도 교체하였습니다.
fill, line, grayLine 으로 변경하였습니다.
Closes #730
> [FE] FEAT: 버튼 gary line 테마 추가 #730

- frontend_v4/src/containers/CabinetListItemContainer.tsx
- #734 
>대여 불가능한 사물함이면 우측 구역에 상세 정보가 표시되지 않도록 수정했습니다.
> [FE] FIX: 대여 불가능한 사물함 우측 구역 출력 방지 #734

- frontend_v4/src/components/CabinetList.tsx
- frontend_v4/src/containers/CabinetListContainer.tsx
- frontend_v4/src/containers/CabinetListItemContainer.tsx
- frontend_v4/src/pages/HomePage.tsx
- frontend_v4/src/pages/MainPage.tsx
- frontend_v4/src/recoil/atoms.ts
- frontend_v4/src/recoil/selectors.ts
- frontend_v4/src/sectionColNumData.ts
- #704 
>기존 resize JS 로직이 css grid 적용으로 대체 되었습니다.
static colNum 데이터를 atom으로 가지고 있어서 selector를 이용해서 받아올 수 있습니다.
> [FE] FEAT: 실제 사물함 배치와 동일하게 렌더링

- frontend_v4/src/components/SectionPagination.tsx
맵에서 E/V 클릭 시 PAGENATION 이전 버튼 클릭하면 다 사라지는 버그 수정하였습니다.
Closes #743
> [FE] BUG: E/V클릭 후 pagination 이전버튼 클릭 버그 #743

- frontend_v4/src/containers/CabinetInfoAreaContainer.tsx
- frontend_v4/src/containers/CabinetListItemContainer.tsx
- frontend_v4/src/containers/ModalContainer.tsx
- frontend_v4/src/containers/TopNavButtonsContainer.tsx
- frontend_v4/src/recoil/atoms.ts
> [FE] 대여, 반납 api

- frontend_v4/src/components/TopNav.tsx
- frontend_v4/src/containers/CabinetInfoAreaContainer.tsx
- frontend_v4/src/containers/LeftNavContainer.tsx
- frontend_v4/src/hooks/useIsMount.ts
- frontend_v4/src/recoil/atoms.ts
> [FE] BUG: 대여, 반납 후 캐비넷 정보, 상세정보 미반영 버그 #750

- frontend_v4/src/containers/MapInfoContainer.tsx
dev 정상작동을 위한 핫픽스입니다.
Closes #747
> [FE] FIX: import 경로 파일이름 수정 #747

- frontend_v4/src/components/MemoModal.tsx
- frontend_v4/src/containers/MemoModalContainer.tsx
> 메모 모달 수정모드에서 저장 버튼을 누르면 캐비넷 메모와 타이틀을 수정하는 api요청을 날립니다. 
단, 두 값 모두 변경 사항이 있을 때만 api콜을 하도록 설계하였습니다.
> [FE] 캐비넷 메모, 타이틀 수정 api적용

- frontend_v4/src/components/CabinetInfoArea.tsx
- frontend_v4/src/containers/CabinetListItemContainer.tsx
> currentCabinetIdState를 참고하여 현재 선택되었다면 호버효과와 동일하게 transform 1.05  프로퍼티를 주었습니다. 
closes #722
> [FE] FEAT: 캐비넷 선택시 호버효과 고정 적용 #722

- frontend_v4/src/Layout.tsx
- frontend_v4/src/components/LentLog.tsx
- frontend_v4/src/components/LogTable.tsx
개인이 사용할 대여 기록 확인 컴포넌트를 제작하였습니다.
이후 백엔드에서 개인 대여기록을 받아오는 api를 열어 주면 기능을 붙이겠습니다
> [FE] FEAT: 개인 로그 기록 확인 컴포넌트 제작 #752

- frontend_v4/src/containers/MemoModalContainer.tsx
>메모 모달 컴포넌트에서 mode가 write이면 input필드를 자동으로 focus 하도록 개선했습니다. 
closes #773
> [FE] 메모 모달안의 수정하기 클릭 시 input필드 autoFocus 적용 #773

- frontend_v4/src/containers/SectionPaginationContainer.tsx
메인의 사물함 부분을 스크롤시 페이지네이션이 상단에 고정되도록 작업하였습니다.
> [FE] FEAT: 페이지네이션 스크롤 시 상단 고정 #776

- backend/package.json
- frontend/src/components/Modals/MemoModal/MemoModal.tsx
- #797 
메모 모달 포탈 적용과 CD 명령어 수정입니다.
함께 수정한 내용이라 바로 머지하겠습니다.
> [FE] FIX: 메모 모달 포탈 적용, CD 명령어 수정 #797

- frontend/src/pages/Layout.tsx
모바일 섹션 이동 스와이프 기능 구현
https://github.com/innovationacademy-kr/42cabi/issues/796
> [FE] 모바일 섹션 이동 스와이프 기능 구현 #796

- frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
- frontend/src/components/CabinetList/RealViewNotification/RealViewNotification.tsx
- frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.tsx
- frontend/src/components/LeftNav/LeftSectionNav/LeftSectionNav.tsx
- frontend/src/components/MapInfo/MapFloorSelect/MapFloorSelect.tsx
- frontend/src/components/MapInfo/MapGrid/MapGrid.tsx
- frontend/src/components/SectionPagination/SectionPagination.tsx
- frontend/src/components/TopNav/TopNav.tsx
- frontend/src/components/TopNav/TopNavButtonGroup/TopNavButton/TopNavButton.tsx
- frontend/src/index.css
https://github.com/innovationacademy-kr/42cabi/issues/801
```
@media (hover: hover) and (pointer: fine) {
...
}
```
위 css 방식으로 마우스와 터치를 구분하여 처리하였습니다.
Closes #801
> [FE] FIX: 모바일에서 터치 이후 hover css 적용되는 문제 #801

- frontend/src/index.css
https://github.com/innovationacademy-kr/42cabi/issues/803
다크모드 관련 css 삭제했습니다.
Closes #803
> [FE] FIX: 다크모드 css 삭제 #803

- frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
- frontend/src/components/Common/Button.tsx
- frontend/src/components/Modals/MemoModal/MemoModal.tsx
- frontend/src/pages/Layout.tsx
https://github.com/innovationacademy-kr/42cabi/issues/807
모바일에서 최대한 보일 수 있도록 수정하였습니다.
dev에 올라가면 실제 모바일로 다시 확인하여 추가적인 작업이 이루어질 수 있습니다.
Closes #807
> [FE] FIX: 사물함 상세보기 모바일 크기 적용 #807

- backend/package.json
- backend/src/admin/auth/auth.controller.ts
- backend/src/admin/auth/google/guard/google.guard.ts
- backend/src/admin/auth/jwt/guard/jwtsign.guard.ts
- backend/src/admin/cabinet/cabinet.controller.ts
- backend/src/admin/return/return.module.ts
- backend/src/auth/auth.controller.ts
- backend/src/auth/auth.module.ts
- backend/src/cabinet/cabinet.info.service.spec.ts
- backend/src/cabinet/repository/mock/mock.cabinet.info.repository.ts
- backend/src/user/my.lent.info.controller.ts
https://github.com/innovationacademy-kr/42cabi/issues/793
CabinetInfoService 테스트 파트를 부모 브랜치(test_main_cabinet) 으로 병합합니다.
> [BE] TEST: cabinet 테스트 병합 #793

- backend/package.json
- backend/src/cabinet/cabinet.info.service.spec.ts
- backend/src/cabinet/repository/mock/mock.cabinet.info.repository.ts
sanan님과 한 모듈에 test code를 추가했기 때문에 우선 간단하게 테스트를 구현하고 두 개의 브랜치를 머지하였습니다.
나머지 세세한 test code는 더 추가하도록 하겠습니다!
> Be/test main cabinet/test main cabinet upper/#793

- frontend/src/App.tsx
- frontend/src/assets/data/maps.ts
- frontend/src/components/CabinetList/RealViewNotification/RealViewNotification.tsx
- frontend/src/components/Home/ServiceManual.tsx
- frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.tsx
- frontend/src/components/TopNav/TopNav.tsx
- frontend/src/components/TopNav/TopNavButtonGroup/TopNavButtonGroup.tsx
- frontend/src/pages/LoginPage.tsx
https://github.com/innovationacademy-kr/42cabi/issues/828
src를 절대경로로 바꿨고 관리자용 라우터도 추가해 뒀습니다.
> [FE] FIX: img src 절대경로로 수정 #828

- frontend/src/components/MapInfo/MapInfo.container.tsx
- frontend/src/components/MapInfo/MapInfo.tsx
- frontend/src/pages/Layout.tsx
https://github.com/innovationacademy-kr/42cabi/issues/826
모바일에서 스와이프로 현재 층의 정보를 바꾸는 기능을 추가하였니다.
> [FE] FEAT: 맵 정보 컴포넌트에 스와이프 기능 추가 #826

- frontend/src/assets/data/sectionColNumData.ts
> [FE] FIX: colNum 데이터 수정 #847

- frontend/src/components/Modals/MemoModal/MemoModal.container.tsx
> [FE] FIX: 타이틀 및 메모 첫 수정시 수정사항 미반영 이슈 해결 #851

- frontend/src/components/CabinetList/CabinetList.container.tsx
- frontend/src/components/CabinetList/EmptySection.tsx
https://github.com/innovationacademy-kr/42cabi/issues/838
엘레베이터 누르는 경우에 나올 이스터에그 컴포넌트 추가했습니다
Closes #838
> [FE] FEAT: 이스터 에그 추가 #838

- frontend/src/components/Modals/LentModal/LentModal.tsx
- frontend/src/components/Modals/ReturnModal/ReturnModal.tsx
>안내 문구 전후 공백 제거, 공백 제거 
#842 
Closes #842
> [FE] FIX: 모달 안내 문구 개행 및 공백 개선 #842

- frontend/src/assets/data/mapPositionData.ts
- frontend/src/components/MapInfo/MapInfo.container.tsx
https://github.com/innovationacademy-kr/42cabi/issues/835
지도 컴포넌트 스와이프 기능 방향을 수정하였고
지도 정적 데이터의 오타 부분을 수정하였습니다.
> [FE] FIX: 지도 컴포넌트 스와이프 이벤트 방향 수정 #835

- frontend/src/components/CabinetList/RealViewNotification/RealViewNotification.tsx
- #825 
모바일에 안맞는 내용 문구 수정했습니다.
> [FE] FIX: realNoti 메시지 문구 수정 #825

- backend/src/admin/log/repository/log.repository.ts
offset대신 skip을 사용하는 방법이 권장되는 거 같지만, query string에 offset에 재대로 들어가지 않아 일단 작동하는 코드로 바꾸겠습니다.
https://github.com/innovationacademy-kr/42cabi/issues/865
> [BE] FIX: pagination query에서 limit가 재대로 추가되도록 변경

- backend/src/user/my.lent.info.controller.ts
param으로 직접 전달하는 것 보다 querystr으로 보내는 것이 더 일반적인 것 같아 바꿨습니다.
> [BE] FIX: param을 querystring으로 변경

- frontend/src/assets/data/sectionColNumData.ts
- frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.container.tsx
- frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.tsx
- frontend/src/components/LeftNav/LeftNav.tsx
- frontend/src/components/LeftNav/LeftSectionNav/LeftSectionNav.container.tsx
- frontend/src/components/LeftNav/LeftSectionNav/LeftSectionNav.tsx
> [FE] REFACTOR: 왼쪽 nav 컨테이너, 컴포넌트 분리 작업 #846

- backend/src/admin/cabinet/cabinet.controller.ts
https://github.com/innovationacademy-kr/42cabi/issues/879
기존에 머지되었던 브랜치에서 CabinetFloorDto가 임포트 되지 않았던 부분을 수정하였습니다.
(CI/CD 크래쉬 수정)
> [BE] FIX : CabinetFloorDto 임포트수정 #879

- backend/src/admin/admin.module.ts
https://github.com/innovationacademy-kr/42cabi/issues/888
DEV 환경변수를 읽지 못해 Develop 모듈이 Dev 환경에서 로딩되지 않는 버그를 수정하였습니다.
> [BE] BUG : Devleop 모듈 로딩 안되는 문제 수정 - ConfigModule import #888

- backend/src/admin/cabinet/cabinet.controller.ts
> [BE] BUG : DTO 중복 선언 핫픽스

- backend/src/dto/request/update.cabinet.memo.request.dto.ts
- backend/src/dto/request/update.cabinet.title.request.dto.ts
위 사진과 같이 64바이트를 넘어가는 요청은 400 Bad Request를 응답하도록 수정했습니다.
> [BE] HOTFIX: update title, memo에 class-validate 추가 #898

- frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
- frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.tsx
- frontend/src/components/LeftNav/LeftSectionNav/LeftSectionNav.tsx
- frontend/src/components/MapInfo/MapFloorSelect/MapFloorSelect.tsx
- frontend/src/components/MapInfo/MapFloorSelectOption/MapFloorSelectOption.tsx
- frontend/src/components/MapInfo/MapInfo.tsx
- frontend/src/components/MapInfo/MapItem/MapItem.tsx
- frontend/src/components/Modals/MemoModal/MemoModal.tsx
- frontend/src/components/SectionPagination/SectionPagination.tsx
- frontend/src/components/TopNav/TopNav.tsx
- frontend/src/components/TopNav/TopNavButtonGroup/TopNavButton/TopNavButton.tsx
https://github.com/innovationacademy-kr/42cabi/issues/902
- 크롬 익스텐션 vimium 지원
- memo 엔터키로 저장되도록 추가
Closes #902
> [FE] 크롬 익스텐션 vimium 지원 #902

- frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
- frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.tsx
- frontend/src/components/LeftNav/LeftSectionNav/LeftSectionNav.tsx
- frontend/src/components/MapInfo/MapFloorSelect/MapFloorSelect.tsx
- frontend/src/components/MapInfo/MapFloorSelectOption/MapFloorSelectOption.tsx
- frontend/src/components/MapInfo/MapInfo.tsx
- frontend/src/components/MapInfo/MapItem/MapItem.tsx
- frontend/src/components/Modals/MemoModal/MemoModal.tsx
- frontend/src/components/SectionPagination/SectionPagination.tsx
- frontend/src/components/TopNav/TopNav.tsx
- frontend/src/components/TopNav/TopNavButtonGroup/TopNavButton/TopNavButton.tsx
https://github.com/innovationacademy-kr/42cabi/issues/902
> [FE] vimium 지원 기능추가 #902

- frontend/src/components/TopNav/TopNav.tsx
- frontend/src/index.css
https://github.com/innovationacademy-kr/42cabi/issues/905
https://stackoverflow.com/questions/25704650/disable-blue-highlight-when-touch-press-object-with-cursorpointer
위 링크에서 찾은 내용을 적용해봤습니다.
Closes #905
> [FE] BUG: 삼성 인터넷 앱에서 버튼 클릭 시 블루 하이라이트 유지되는 버그 #905

- frontend/src/components/TopNav/TopNav.tsx
- frontend/src/index.css
Reverts innovationacademy-kr/42cabi#908
> Revert "[FE] BUG: 삼성 인터넷 앱에서 버튼 클릭 시 블루 하이라이트 유지되는 버그 #905"

- frontend/src/index.css
추가 사항 반영을 위해 이전부분들 revert 후 다시 머지합니다.
https://github.com/innovationacademy-kr/42cabi/issues/905
> [FE] 삼성 인터넷 앱에서 버튼 클릭 시 블루 하이라이트 유지되는 버그 #905

- frontend/src/components/Search/SearchItem.tsx
- frontend/src/components/TopNav/SearchBar/SearchList/SearchList.tsx
- frontend/src/index.css
- frontend/src/pages/admin/AdminLayout.tsx
- frontend/src/pages/admin/SearchPage.tsx
https://github.com/innovationacademy-kr/42cabi/issues/838
/admin/search 페이지에서 보여질 SearchItem 컴포넌트 스타일 추가했습니다.
여기에 사용될 api 확인 및 개선 후 추가 진행이 있을 예정입니다.
> [FE] FEAT: SearchItem 컴포넌트 추가 #868

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Login/__tests__/LoginTemplate.test.tsx
- frontend/src/setupTest.ts
- frontend/vite.config.ts
#891 
Vitest 사용을 위한 설정을 추가하였습니다. 
Vitest 테스트 러너를 사용하면 Vite과 하나의 파이프라인으로 configuration이 가능합니다. 또한 Jest API를 사용할 수 있습니다.  
`npm install`로 dependency를 설치하시면 테스트 실행이 가능합니다.
`npm test` : default 테스트 실행 명령입니다. 감시 모드로 진입합니다. 감시 모드에서는 테스트 관련 파일의 변화가 있을 때마다 테스트를 자동으로 재실행합니다. 
`npm test run` : 감시 모드 없이 한 번의 테스트를 수행하고 끝냅니다.
`jsdom` : 노드 환경에서 DOM 렌더링을 시뮬레이션 해주는 유틸입니다. 
`@testing-library` : 테스트를 위한 유용한 matcher 함수들을 제공하는 라이브러리입니다.
- test 코드는 [이름].test.tsx 와 같이 작성합니다.
- 혹은 __tests__라는 폴더 안의 모든 js,mjs,cjs,ts,mts,cts,jsx,tsx 파일은 테스트 코드로 인식합니다.
- 위 설정은 vite.config.ts 파일에서 수정할 수 있습니다.
=========================================
***LoginTemplate 폴더 안에 __tests__라는 폴더를 만들어 LoginTemplate.test.tsx라는 샘플 테스트 코드를 추가했습니다.***
closes #891
> [FE] frontend 유닛 테스팅을 위한 vitest 설치 및 초기설정 #891

- backend/test/test_db.sql
>아래 링크에 이슈번호를 적어주세요. 예) .../42cabi/issues/793
테스트용 sql 파일에서 관리자 유저 데이터를 추가했습니다.
> Be/dev/e2e test main lent/#793

- backend/src/admin/search/repository/search.repository.ts
searchUserCabinetList에서 정렬 조건을 수정하여 
Lent가 null이 아닌 값들은 Lent.cabinet.floor, Lent.cabinet.cabinet_num로 오름차순 정렬
Lent가 null인 값들은 intra_id로 오름차순 정렬되도록 조치했습니다.
https://github.com/innovationacademy-kr/42cabi/issues/921
> [BE] FIX: searchUserCabinetList에서 정렬 조건 수정 #921

- frontend/src/components/AdminChart/BarChart.tsx
- frontend/src/components/AdminChart/PieChart.tsx
- frontend/src/components/Login/LoginTemplate.tsx
https://github.com/innovationacademy-kr/42cabi/issues/926
차트 내용 수정 및 출력 색상 등 ui를 살짝 수정했습니다.
> [FE] FIX: 차트 색상 및 데이터 출력 값 수정 #926

- frontend/src/assets/css/media.css
- frontend/src/components/TopNav/SearchBar/SearchBar.tsx
- frontend/src/components/TopNav/TopNav.tsx
- frontend/src/components/TopNav/TopNavButtonGroup/TopNavButtonGroup.tsx
- frontend/src/pages/admin/SearchPage.tsx
…into dev
https://github.com/innovationacademy-kr/42cabi/issues/939
page라는 변수가 0으로 초기화되나, useState로 변수를 만들어서 바로 반영이 안되는 버그입니다.
해당 변수를 useState대신 useRef로 변경하여 처리했습니다.
> [FE] FEAT: 모바일을 위한 검색 레이아웃 수정 #933

- frontend/src/components/AdminChart/BarChart.tsx
- frontend/src/components/AdminChart/PieChart.tsx
> [FE] FIX: 반응형 차트 크기 조정 #949

- frontend/src/api/axios/axios.custom.ts
- frontend/src/assets/css/media.css
- frontend/src/components/Search/SearchItemByIntraId.tsx
- frontend/src/components/Search/SearchItemByNum.tsx
- frontend/src/components/TopNav/SearchBar/SearchBar.tsx
- frontend/src/components/TopNav/SearchBar/SearchBarList/SearchBarList.tsx
- frontend/src/components/TopNav/SearchBar/SearchListItem/SearchListItem.tsx
- frontend/src/hooks/useMenu.ts
- frontend/src/pages/admin/SearchPage.tsx
- frontend/src/recoil/atoms.ts
https://github.com/innovationacademy-kr/42cabi/issues/943
- 검색바에서 외 다른 곳 클릭 시 리스트 안보이게 처리
- 키보드 up, down 시 검색 리스트 이동 가능하게 처리
> [FE] FEAT: 검색바 UX 개선 #943

- backend/test/admin/cabinet.e2e-spec.ts
- backend/test/admin/develop.e2e-spec.ts
> Be/e2e test/admin develop/#793

- backend/src/admin/log/log.controller.ts
- backend/src/admin/log/log.service.ts
- backend/src/admin/log/repository/log.interface.repository.ts
- backend/src/admin/log/repository/log.repository.ts
https://github.com/innovationacademy-kr/42cabi/issues/960
특정 유저가 현재 받고 있는 페널티를 해제하는 기능을 추가했습니다.
해당 기능에 대한 api는 `/api/admin/log/ban/:userId`으로 Delete 요청 보내시면 되고, param으로 user_id를 보내주시면 됩니다.
제가 개인적으로 테스트 해보긴 했으나 문제 있으면 언제든 말해주시고
혹시 코드에 이상한 점이 있거나 수정해야할 부분이 있으면 말해주세요!
> [BE] feat: 특정 유저의 페널티 해제 기능 추가 #960

- backend/src/admin/dto/blocked.user.info.dto.ts
- backend/src/admin/dto/cabinet.location.floor.dto.ts
- backend/src/admin/dto/user.cabinet.info.dto.ts
- backend/src/admin/search/repository/search.repository.ts
인트라 아이디로 검색하는 API에서, 검색 대상의 사용 정지 정보를 추가하고, 해당 유저가 대여중인 사물함이 있는 경우, 해당 사물함을 대여중인 유저들의 대여 정보를 추가했습니다.
사용 정지 정보는 기존의 `BlockedUserInfoDto`에서 `banned_date`와 `unbanned_date를` optional로 변경하여 사용했으며,
사물함 정보 + 대여 정보는 `CabinetLocationFloorDto`에서 `lent_info`를 optional로 추가하여 사용했습니다.
쿼리문으로 검색을 수행할 때 `BanLog` 테이블과의 join을 추가하여 해당 유저의 사용 정지 내역을 가져오도록하고,
사용 정지 내역 중 가장 최근 값이 오늘 날짜보다 이후일 때만 값을 저장하고, 그렇지 않으면 null을 저장하도록 했습니다.
유저가 대여중인 사물함을 대여중인 유저들의 정보를 `LentDto`의 배열 형태로 `lentInfo` 필드에 저장하도록 했습니다.
```
{
"result": [
{
"user_id": 81795,
"intra_id": "minsikim",
"banned_date": null,
"unbanned_date": null,
"cabinetInfo": {
"cabinet_id": 84,
"cabinet_num": 4,
"lent_type": "SHARE",
"cabinet_title": "dkdkdkkddddd",
"max_user": 3,
"status": "AVAILABLE",
"section": "End of …
```
> [BE] FIX: admin search intraId에 대여정보와 사용정지 정보 추가 #961

- frontend/src/components/AdminInfo/Table/PageNation2.tsx
> [FE] FIX: 빈 컴포넌트 수정 #956

- backend/src/admin/dto/Overdue.user.cabinet.info.dto.ts
- backend/src/admin/dto/OverdueUserInfoPagenationDto.ts
- backend/src/admin/search/repository/search.repository.interface.ts
- backend/src/admin/search/repository/search.repository.ts
- backend/src/admin/search/search.controller.ts
- backend/src/admin/search/search.service.ts
> 연체 유저 관련 API 수정

- backend/src/admin/search/repository/search.repository.ts
> 연체 유저 API 형식 수정

- frontend/src/api/axios/axios.custom.ts
- frontend/src/components/AdminInfo/convertFunctions.ts
- frontend/src/pages/admin/AdminInfoPage.tsx
- frontend/src/types/dto/admin.dto.ts
> [FE] FEAT: 반납 지연 유저 리스트 api 연결 #985

- backend/src/admin/log/repository/log.repository.ts
https://github.com/innovationacademy-kr/42cabi/issues/1004
기존에 잘 작동하지 않았던 페이지네이션을 skip->offset으로 변경하였습니다.
skip이 잘 작동하지 않는 이유에 대해서 찾아보았으나, 명확한 이유는 찾지 못하였습니다.
기존과 동일하게 page=0부터 시작합니다.
> [BE] BUG: 어드민 로그 페이지네이션 비정상 작동 수정#1004

- frontend/src/components/CabinetList/RealViewNotification/RealViewNotification.tsx
> [FE] real view noti 오 표기 수정 #1021

- frontend/src/pages/admin/AdminInfoPage.tsx
https://github.com/innovationacademy-kr/42cabi/issues/1029
테이블 컬럼 두개로 긴급 수정하였습니다.
> [FE] FIX: 고장 사물함 테이블 컬럼 2개로 변경 #1029

- backend/src/main/java/org/ftclub/cabinet/exception/ExceptionController.java
- backend/src/main/java/org/ftclub/cabinet/exception/ExceptionStatus.java
- backend/src/main/java/org/ftclub/cabinet/exception/ServiceException.java
이전에 만든 exception처리 로직을 담고있습니다.
Service class의 메서드에서 ServiceException을 throw하면, 그 Service class의 메서드를 호출한 Controller에서 try catch를 통해 관리하지 않더라도 ExceptionController가 알아서 처리해줍니다.
> Exception을 처리하는 Controller추가

- .gitignore
- backend/build.gradle
- backend/src/main/java/org/ftclub/cabinet/admin/domain/AdminUser.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/domain/Cabinet.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/domain/CabinetGrid.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/domain/CabinetPlace.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/domain/Grid.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/domain/Location.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/domain/MapArea.java
- backend/src/main/java/org/ftclub/cabinet/lent/domain/LentCabinetDetail.java
- backend/src/main/java/org/ftclub/cabinet/lent/domain/LentHistory.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/BanHistory.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/User.java
- backend/src/main/resources/application-test.yml
- backend/src/main/resources/application.yml
- backend/src/test/java/org/ftclub/cabinet/CabinetApplicationTests.java
- jpa에 sql ddl에 대한 정보를 추가했습니다.
- test용 profile을 @ActiveProfiles 어노테이션을 따로 추가하지 않더라도 사용할 수 있도록 gradle을 변경했습니다.
> [BE] FEAT: JPA 및 DDL 업데이트

- backend/src/admin/cabinet/cabinet.service.ts
- backend/src/admin/cabinet/repository/cabinet.repository.interface.ts
- backend/src/admin/cabinet/repository/cabinet.repository.ts
- backend/src/admin/dto/Overdue.user.cabinet.info.dto.ts
- backend/src/admin/dto/OverdueUserInfoPagenationDto.ts
- backend/src/admin/log/repository/log.repository.ts
- backend/src/admin/return/return.service.ts
- backend/src/blackhole/blackhole.service.ts
- backend/src/cabinet/cabinet.info.controller.ts
- backend/test/admin/cabinet.e2e-spec.ts
- backend/test/admin/search.e2e-spec.ts
- backend/test/main/cabinet.e2e-spec.ts
- backend/test/main/user.e2e-spec.ts
https://github.com/innovationacademy-kr/42cabi/issues/1041
BANNED 타입이 삭제되어 블랙홀 모듈의 코드를 수정하였습니다.
개인 사물함을 빌리고 있는 사람이 블랙홀에 빠지게 되면 BANNED 타입으로 바뀐 뒤 반납이 되는 구조였는데, 바로 반납이 될 수 있도록 수정했습니다.
> [BE] FIX: BANNED 타입 삭제로 인한 블랙홀 모듈 수정 #1041

- backend/src/admin/return/return.controller.ts
- backend/test/admin/return.e2e-spec.ts
https://github.com/innovationacademy-kr/42cabi/issues/1044
수정,, 완료
> [BE] BUG: 다중 선택 반납 수정 #1044

- frontend/src/components/CabinetList/CabinetList.container.tsx
> https://github.com/innovationacademy-kr/42cabi/issues/#1052
이전 PR에서 추가했던 코드 중 EmptySection을 추가하는 조건을 삭제하였습니다.
Closes #1052
> [FE] 캐비닛 받아오는 시점에서 cabi 이모티콘 뜨는 오류 #1052

- backend/src/main/java/org/ftclub/cabinet/dto/BlockedUserDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/BlockedUserPaginationDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/BrokenCabinetDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/BrokenCabinetPaginationDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/BuildingFloorsDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/BuildingFloorsResponseDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/CabinetDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/CabinetFloorStatisticsResponseDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/CabinetInfoPaginationDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/CabinetInfoResponseDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/CabinetWithMemoDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/CabinetsPerSectionResponseDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/LentDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/LentHistoryDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/LentHistoryPaginationDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/LentsStatisticsResponseDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/MyCabinetInfoResponseDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/MyProfileResponseDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/OverdueUserCabinetDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/OverdueUserCabinetPaginationDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/UserProfileDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/UserProfilePaginationDto.java
notion에 정리해놓으신 dto들을 옮겨놨습니다.
getter와 constructor만 만들어 놓고, 모든 field는 final로 설정했습니다. 문제가 있다면 말해주세요
> [BE] FEAT: 새로 만든 DTO들 추가

- backend/src/main/java/org/ftclub/cabinet/cabinet/domain/Cabinet.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetService.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/lent/controller/LentController.java
- backend/src/main/java/org/ftclub/cabinet/lent/domain/LentHistory.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentHistoryService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserService.java
서비스 계층 구현 과정에서 다른 서비스 계층 메소드를 의존하는 경우, 이를 mocking하여 작업하기 위해 서비스 계층용 인터페이스 추가를 추가했습니다.
https://github.com/innovationacademy-kr/42cabi/issues/1023
> [BE] FEAT: 서비스 계층용 인터페이스 추가

- backend/src/admin/search/repository/search.repository.ts
- backend/src/admin/search/search.controller.ts
https://github.com/innovationacademy-kr/42cabi/issues/1081
대여가 몇 번 발생했는지 확인할 때 lent_log와 lent 테이블 모두 참조하여 개수를 셀 수 있도록 수정하였습니다.
> [COMMON] FIX: 대여/반납 통계관련 로직 수정 #1081

- backend/src/main/java/org/ftclub/cabinet/auth/AdminAuthController.java
- backend/src/main/java/org/ftclub/cabinet/auth/AuthAspect.java
- backend/src/main/java/org/ftclub/cabinet/auth/AuthController.java
- backend/src/main/java/org/ftclub/cabinet/auth/CookieManager.java
- backend/src/main/java/org/ftclub/cabinet/auth/OauthService.java
- backend/src/main/java/org/ftclub/cabinet/auth/TokenProvider.java
- backend/src/main/java/org/ftclub/cabinet/auth/TokenValidator.java
- backend/src/main/java/org/ftclub/cabinet/config/JwtProperties.java
- backend/src/test/java/org/ftclub/cabinet/auth/controller/AdminAuthControllerTest.java
- backend/src/test/java/org/ftclub/cabinet/auth/controller/AuthControllerTest.java
- backend/src/test/java/org/ftclub/cabinet/auth/domain/ApiUriBuilderTest.java
- backend/src/test/java/org/ftclub/cabinet/auth/domain/CookieManagerTest.java
- backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenProviderTest.java
- backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenValidatorTest.java
- backend/src/test/java/org/ftclub/cabinet/auth/service/OauthServiceTest.java
https://github.com/innovationacademy-kr/42cabi/issues/1089
기존 Auth의 로직을 수정(쿠키에 해당하는 auth level에 맞는 쿠키 있는지 검증하는 로직 추가)하였고,
테스트를 추가하였습니다.
> [BE] FIX, TEST: 기존 검증 로직 보완 및 테스트 추가

- backend/src/main/resources/application-test.yml
- backend/src/test/resources/Dockerfile
- backend/src/test/resources/my.cnf
test용 db가 대소문자를 구분하여 테스트에서 문제가 생기는 경우를 경험하여 설정을 바꾸었습니다.
설정을 바꾸는 부분이라 바로 올리는 것이 좋을 거 같아서 먼저 체리픽으로 반영했습니다.
> [BE] FIX: test용 db 대소문자 구분 안하도록 변경

- backend/src/main/java/org/ftclub/cabinet/config/CabinetProperties.java
- backend/src/main/java/org/ftclub/cabinet/lent/domain/LentPolicyImpl.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/BanPolicyImpl.java
> [BE] FIX: 프로퍼티 관리 한곳으로 모음

- backend/src/main/resources/application.yml
- backend/src/test/java/org/ftclub/cabinet/auth/controller/AdminAuthControllerTest.java
- backend/src/test/java/org/ftclub/cabinet/auth/controller/AuthControllerTest.java
- backend/src/test/java/org/ftclub/cabinet/auth/domain/ApiUriBuilderTest.java
- backend/src/test/java/org/ftclub/cabinet/auth/domain/CookieManagerTest.java
- backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenProviderTest.java
- backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenValidatorTest.java
- backend/src/test/java/org/ftclub/cabinet/auth/service/OauthServiceTest.java
> [BE] FIX: application yml파일 변경

- frontend/src/components/Login/AdminLoginTemplate.tsx
- frontend/src/pages/admin/AdminLoginPage.tsx
Admin 페이지에 새로운 로그인 입력 폼을 추가했습니다. 기존 Google Oauth 방식 외 어드민 계정으로 로그인 할 수 있습니다.
Closes #1109
> [FE] FEAT: Admin 로그인 입력 폼 추가 #1109

- backend/src/admin/auth/auth.controller.ts
- backend/src/admin/auth/auth.service.ts
- backend/src/admin/dto/admin.login.dto.ts
- backend/src/config/configuration.ts
- /api/admin/auth/login
- 실패시 401
- 성공시 쿠키로 제공 ( admin_access_token )
- .env 에 환경변수로 연결된 값으로 ID & PASSWORD 입력
https://github.com/innovationacademy-kr/42cabi/issues/1109
> [BE] FEAT: 어드민 로그인 id, password 입력받는 방식 개선 #1109

- backend/src/main/java/org/ftclub/cabinet/dto/UserCabinetDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/UserCabinetPaginationDto.java
- backend/src/main/java/org/ftclub/cabinet/exception/ExceptionStatus.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/user/UserController.java
- backend/src/main/java/org/ftclub/cabinet/user/controller/AdminUserController.java
- backend/src/main/java/org/ftclub/cabinet/user/controller/UserController.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/AdminRole.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/BanPolicy.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/BanType.java
- backend/src/main/java/org/ftclub/cabinet/user/repository/AdminUserRepository.java
- backend/src/main/java/org/ftclub/cabinet/user/repository/BanHistoryRepository.java
- backend/src/main/java/org/ftclub/cabinet/user/repository/UserRepository.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserExceptionHandlerService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserServiceImpl.java
- backend/src/test/java/org/ftclub/cabinet/user/controller/AdminUserControllerTest.java
- backend/src/test/java/org/ftclub/cabinet/user/controller/UserControllerTest.java
- backend/src/test/java/org/ftclub/cabinet/user/repository/AdminUserRepositoryTest.java
- backend/src/test/java/org/ftclub/cabinet/user/repository/BanHistoryRepositoryTest.java
- backend/src/test/java/org/ftclub/cabinet/user/repository/UserRepositoryTest.java
- backend/src/test/java/org/ftclub/cabinet/user/service/UserFacadeServiceTest.java
- backend/src/test/java/org/ftclub/cabinet/user/service/UserServiceTest.java
https://github.com/innovationacademy-kr/42cabi/issues/1038
- userController, AdminController 생성
- JavaDoc 추가
- 테스트 코드 추가 (controller 테스트 제외)
- UserCabinetPaginationDto 생성 -> 수정 필요해보이나 우선 구현
아직 완벽히 하진 못 했습니다만..
머지 한 번 하는 게 좋을 것 같아 PR 올립니다!
> [BE] Spring 포팅 - User 

- backend/src/admin/auth/auth.controller.ts
- backend/src/admin/auth/jwt/jwt.strategy.ts
- frontend/src/api/axios/axios.custom.ts
- frontend/src/assets/data/maps.ts
- frontend/src/components/Login/AdminLoginTemplate.tsx
- frontend/src/components/Login/LoginTemplate.tsx
>https://github.com/innovationacademy-kr/42cabi/issues/1109
데스크 요청에 따라 어드민페이지에서는 id, password를 적어서 사용할 수 있도록 변경했습니다.
성공시 서버에서는 200 OK를 보내주며, 200을 받은 프론트에서 페이지 전환을 하도록 수정했습니다.
Closes #1109
> [COMMON] FEAT: 어드민 로그인 api 연결 #1109

- backend/src/main/java/org/ftclub/cabinet/auth/UserAspect.java
- backend/src/main/java/org/ftclub/cabinet/dto/BlockedUserPaginationDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/UserProfilePaginationDto.java
- backend/src/main/java/org/ftclub/cabinet/user/controller/AdminUserController.java
- backend/src/main/java/org/ftclub/cabinet/user/controller/UserController.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/BanPolicy.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/BanPolicyImpl.java
- backend/src/main/java/org/ftclub/cabinet/user/repository/AdminUserRepository.java
- backend/src/main/java/org/ftclub/cabinet/user/repository/BanHistoryRepository.java
- backend/src/main/java/org/ftclub/cabinet/user/repository/UserRepository.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserExceptionHandlerService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserServiceImpl.java
- backend/src/test/java/org/ftclub/cabinet/user/controller/AdminUserControllerTest.java
- backend/src/test/java/org/ftclub/cabinet/user/controller/UserControllerTest.java
- backend/src/test/java/org/ftclub/cabinet/user/repository/UserRepositoryTest.java
- backend/src/test/java/org/ftclub/cabinet/user/service/UserFacadeServiceTest.java
- backend/src/test/java/org/ftclub/cabinet/user/service/UserServiceTest.java
- backend/src/test/java/org/ftclub/testutils/TestControllerUtils.java
https://github.com/innovationacademy-kr/42cabi/issues/1038
- UserController, AdminUserController 테스트 추가
- User 어노테이션 관련 코드 수정
- JavaDoc 추가
- 기타 로직 수정
- 피드백 반영
> [BE] SPRING 포팅 - User

- frontend/src/components/AdminInfo/Table/AdminTable.tsx
- frontend/src/components/AdminInfo/Table/Pagination.tsx
- frontend/src/pages/admin/AdminInfoPage.tsx
> https://github.com/innovationacademy-kr/42cabi/issues/1119
스타일, 오타, 컨벤션 관련 수정 했습니다!
Closes #1119
> [FE] FIX: 어드민 스타일 수정 #1119

- backend/src/main/java/org/ftclub/cabinet/auth/controller/AdminAuthController.java
- backend/src/main/java/org/ftclub/cabinet/auth/controller/AuthController.java
- backend/src/main/java/org/ftclub/cabinet/auth/domain/ApiUriBuilder.java
- backend/src/main/java/org/ftclub/cabinet/auth/domain/TokenProvider.java
- backend/src/main/java/org/ftclub/cabinet/auth/domain/TokenValidator.java
- backend/src/main/java/org/ftclub/cabinet/auth/service/OauthService.java
- backend/src/main/java/org/ftclub/cabinet/config/FtApiProperties.java
- backend/src/main/java/org/ftclub/cabinet/config/GoogleApiProperties.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/UserAspect.java
- backend/src/main/resources/application.yml
- backend/src/test/java/org/ftclub/cabinet/auth/domain/ApiUriBuilderTest.java
- backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenProviderTest.java
- backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenValidatorTest.java
- backend/src/test/java/org/ftclub/cabinet/user/controller/UserSessionControllerTest.java
https://github.com/innovationacademy-kr/42cabi/issues/1123
JSONObject가 Vulnerable하므로 JsonNode로 변경하였고, 한번에 긴 줄로 표현된 부분을 잘라서 재작성하였습니다.
> [BE] Auth JSONObject -> JsonNode 사용으로 변경 및 리팩터링

- backend/src/main/java/org/ftclub/cabinet/event/EventTestService.java
- backend/src/main/java/org/ftclub/cabinet/event/LentEventListener.java
- backend/src/main/java/org/ftclub/cabinet/event/LentStartEvent.java
- backend/src/test/java/org/ftclub/cabinet/event/LentEventListenerTest.java
https://github.com/innovationacademy-kr/42cabi/issues/1126
메일, 슬랙 봇을 위한 이벤트 예시와 테스트를 작성해봤습니다!
자세한 정보는 <a href="https://cabi.oopy.io/0efd3a8e-e4a5-43df-b55e-4839a1f4c923" target="_blank">노션에 작성</a>해두었습니다!
> [BE] SPRING 이벤트 임시 구현

- backend/src/admin/search/repository/search.repository.ts
https://github.com/innovationacademy-kr/42cabi/issues/1136
floor로 정렬해서 받아오도록 코드 수정했습니다 👍
> [BE] BUG: admin에서 캐비닛 number로 검색 시 정렬 오류 #1135

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/AdminInfo/Chart/LineChart.tsx
- frontend/src/pages/admin/AdminInfoPage.tsx
- frontend/stats.html
- frontend/stats.json
- frontend/vite.config.ts
- package-lock.json
- package.json
https://github.com/innovationacademy-kr/42cabi/issues/1127
> [FE] FIX: 차트 title, table column 수정 #1127

- backend/src/admin/search/repository/search.repository.ts
https://github.com/innovationacademy-kr/42cabi/issues/1135
이전에 sort로 처리했던 부분을 order: {floor: 'ASC' } 에서 처리하도록 변경했습니다.
Closes #1135
> [BE] FIX: searchByCabinetNumber order 수정 #1135

- frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.container.tsx
- frontend/src/components/LeftNav/LeftSectionNav/LeftSectionNav.container.tsx
- componets LeftNav import 순서 변경
- 로직은 잘 되어 있다고 생각해서 수정하지 않았습니다!
> [FE] REFACTOR: LeftNav 리팩토링 #1137

- frontend/src/api/axios/axios.custom.ts
- frontend/src/api/axios/axios.instance.ts
- frontend/src/assets/css/mainPage.css
- frontend/src/assets/data/mapPositionData.ts
> https://github.com/innovationacademy-kr/42cabi/issues/1137
- 사용하지 않는 css 파일 삭제
- axios 수정
- 기존 주석 -> Jsdocs로 interface 가독성을 높였습니다.
> [FE] REFACTOR: api, assets 폴더 리팩토링 #1137

- backend/src/main/java/org/ftclub/cabinet/dto/MyProfileResponseDto.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
- backend/src/test/java/org/ftclub/cabinet/user/controller/UserSessionControllerTest.java
> [BE] FIX: MyProfileResponse Dto에 unbannedAt 추가

- backend/src/admin/search/repository/search.repository.ts
- frontend/src/api/axios/axios.custom.ts
- frontend/src/components/TopNav/SearchBar/SearchBar.tsx
- frontend/src/components/TopNav/SearchBar/SearchListItem/SearchListItem.tsx
- frontend/src/pages/admin/SearchPage.tsx
https://github.com/innovationacademy-kr/42cabi/issues/1155
어드민 사물함 검색 시 층 선택 되도록 수정한 내용
main에 배포하겠습니다.
> [FE] FIX: 어드민 사물함 검색 시 층 선택 되도록 수정 #1155

- backend/src/main/java/org/ftclub/cabinet/auth/controller/AdminAuthController.java
- backend/src/main/java/org/ftclub/cabinet/auth/domain/AuthAspect.java
- backend/src/main/java/org/ftclub/cabinet/auth/domain/AuthGuard.java
- backend/src/main/java/org/ftclub/cabinet/auth/domain/AuthLevel.java
- backend/src/main/java/org/ftclub/cabinet/auth/domain/TokenProvider.java
- backend/src/main/java/org/ftclub/cabinet/auth/domain/TokenValidator.java
- backend/src/main/java/org/ftclub/cabinet/auth/service/AuthService.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/controller/AdminCabinetController.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/controller/CabinetController.java
- backend/src/main/java/org/ftclub/cabinet/config/DomainNameProperties.java
- backend/src/main/java/org/ftclub/cabinet/config/MasterProperties.java
- backend/src/main/java/org/ftclub/cabinet/dto/MasterLoginDto.java
- backend/src/main/java/org/ftclub/cabinet/event/LentStartEvent.java
- backend/src/main/java/org/ftclub/cabinet/lent/controller/AdminLentController.java
- backend/src/main/java/org/ftclub/cabinet/statistics/controller/StatisticsController.java
- backend/src/main/java/org/ftclub/cabinet/user/controller/AdminUserController.java
- backend/src/main/java/org/ftclub/cabinet/user/controller/UserController.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/AdminRole.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/UserAspect.java
- backend/src/main/java/org/ftclub/cabinet/user/repository/UserRepository.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserServiceImpl.java
- backend/src/test/java/org/ftclub/cabinet/auth/controller/AdminAuthControllerTest.java
- backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenValidatorTest.java
- backend/src/test/java/org/ftclub/cabinet/cabinet/controller/AdminCabinetControllerTest.java
- backend/src/test/java/org/ftclub/cabinet/cabinet/controller/CabinetControllerTest.java
- backend/src/test/java/org/ftclub/cabinet/user/controller/AdminUserControllerTestSession.java
- backend/src/test/java/org/ftclub/cabinet/user/controller/UserSessionControllerTest.java
- backend/src/test/java/org/ftclub/testutils/TestControllerUtils.java
https://github.com/innovationacademy-kr/42cabi/issues/1158
최고 관리자 권한(MASTER)을 구현했습니다.
AuthGuard의 AuthLevel을 별도의 열거형으로 분리해서, 해당 단계에 따른 토큰의 role과 비교하도록 했습니다.
기존의 TestControllerUtils에서 Master 토큰도 만들 수 있도록 했습니다.
+ 
최고 관리자 로그인 및 Properties 추가로 config 파일들을 변경했습니다. 확인해주세요..!
> [BE] SPRING 최고 관리자 권한, 로그인 구현 및 DB로 권한 확인 로직 추가

- frontend/src/components/Search/NoSearch.tsx
- frontend/src/components/Search/SearchDefault.tsx
- frontend/src/components/Search/SearchItemByIntraId.tsx
- frontend/src/components/Search/SearchItemByNum.tsx
- frontend/src/pages/admin/SearchPage.tsx
> https://github.com/innovationacademy-kr/42cabi/issues/1137
admin의 Search 코드 리팩토링 했습니다.
사용하지 않는 값들의 삭제 및 불분명한 함수의 이름 수정이 있었습니다.
> [FE] REFACTOR: Search 코드 리팩토링 #1137

- frontend/src/components/Home/ServiceManual.tsx
- frontend/src/components/Login/AdminLoginTemplate.tsx
- frontend/src/components/Login/LoginTemplate.tsx
- frontend/src/components/Login/__tests__/LoginTemplate.test.tsx
> [FE] REFACTOR: Home&Login 코드 리팩토링 #1137

- frontend/src/components/TopNav/AdminTopNav.container.tsx
- frontend/src/components/TopNav/SearchBar/SearchBarList/SearchBarList.tsx
- frontend/src/components/TopNav/SearchBar/SearchListItem/SearchListItem.tsx
- frontend/src/components/TopNav/TopNav.container.tsx
- frontend/src/components/TopNav/TopNav.tsx
- frontend/src/components/TopNav/TopNavButtonGroup/TopNavButtonGroup.tsx
- import 순서 변경과 중복되는 변수이름의 수정이 있었습니다.
> [FE] REFACTOR:TopNav 코드 리팩토링 #1137

- frontend/src/components/Login/AdminLoginTemplate.tsx
- frontend/src/components/Login/LoginTemplate.tsx
- frontend/src/components/Login/__tests__/LoginTemplate.test.tsx
- frontend/src/pages/HomePage.tsx
- frontend/src/pages/LoginPage.tsx
- frontend/src/pages/admin/AdminLoginPage.tsx
- loginPage, adminLoginPage 에서 이미지도 필수 값으로 넘겨주는 방식으로 변경
- 중복 사용된 import 삭제
- import 순서 변경
> [FE] REFACTOR:pages-hompage & loginpage 코드 리팩토링 #1137

- frontend/src/pages/MainPage.tsx
swipeSection 함수의 가독성을 높이고, 중복된 코드를 없애기 위해서 코드를 수정했습니다.
코드 변경 사유) swipeMap 코드를 성희님과 수정하면서 비슷한 코드인 swipeSection도 함께 수정을 했습니다 :)
> [FE] REFACTOR: MainPage의 swipeSection 함수 수정 #1137

- frontend/src/components/LentLog/LogTable/AdminCabinetLogTable.tsx
- frontend/src/components/Modals/BanModal/BanModal.tsx
- frontend/src/components/Modals/LentModal/LentModal.tsx
- frontend/src/components/Modals/MemoModal/MemoModal.container.tsx
- frontend/src/components/Modals/MemoModal/MemoModal.tsx
- frontend/src/components/Modals/Modal.tsx
- frontend/src/components/Modals/ModalPortal.tsx
- frontend/src/components/Modals/PasswordCheckModal/PasswordCheckModal.container.tsx
- frontend/src/components/Modals/PasswordCheckModal/PasswordCheckModal.tsx
- frontend/src/components/Modals/ResponseModal/ResponseModal.tsx
- frontend/src/components/Modals/ReturnModal/AdminReturnModal.tsx
- frontend/src/components/Modals/ReturnModal/ReturnModal.tsx
- frontend/src/components/Modals/StatusModal/StatusModal.container.tsx
- frontend/src/components/Modals/StatusModal/StatusModal.tsx
- frontend/src/components/Modals/UnavailableModal/UnavailableModal.tsx
- frontend/src/pages/LogPage.tsx
- frontend/src/types/dto/lent.dto.ts
- Modals 폴더 밑의 컴포넌트들의 import 순서 및 개행, 공백을 수정했습니다.
- IModalContents 통합 후 주석을 추가했습니다.
- LentLog , lent.dto, AdminCabinetLogTable 공백을 수정했습니다.
> [FE] REFACTOR: Modals 컴포넌트 리팩토링 및 추가 수정#1137

- backend/src/main/java/org/ftclub/cabinet/dto/BlockedUserPaginationDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/PaginationRequestDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/UserProfilePaginationDto.java
- backend/src/main/java/org/ftclub/cabinet/lent/controller/AdminLentController.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/mapper/CabinetMapper.java
- backend/src/main/java/org/ftclub/cabinet/search/controller/SearchController.java
- backend/src/main/java/org/ftclub/cabinet/statistics/controller/StatisticsController.java
- backend/src/main/java/org/ftclub/cabinet/user/controller/AdminUserController.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
> [BE] FIX: length -> size 변경 & totalLength -> totalPage

- frontend/src/App.tsx
- frontend/src/pages/admin/AdminHomePage.tsx
https://github.com/innovationacademy-kr/42cabi/issues/1194
> [FE] REFACTOR: adminInfo를 adminHome 페이지로 이름 수정#1194

- backend/src/main/java/org/ftclub/cabinet/user/domain/AdminUser.java
- backend/src/test/java/org/ftclub/cabinet/user/domain/UserDomainTest.java
user domain test 코드 작성
https://github.com/innovationacademy-kr/42cabi/issues/1188
> [BE] TEST: user domain 테스트 작성 #1188

- backend/build.gradle
- backend/src/main/java/org/ftclub/cabinet/cabinet/controller/AdminCabinetController.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/controller/CabinetController.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/repository/CabinetOptionalFetcher.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/lent/controller/AdminLentController.java
- backend/src/main/java/org/ftclub/cabinet/lent/controller/LentController.java
- backend/src/main/java/org/ftclub/cabinet/lent/domain/LentPolicyImpl.java
- backend/src/main/java/org/ftclub/cabinet/lent/repository/LentOptionalFetcher.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/search/controller/SearchController.java
- backend/src/main/java/org/ftclub/cabinet/statistics/controller/StatisticsController.java
- backend/src/main/java/org/ftclub/cabinet/statistics/service/StatisticsFacadeServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/user/controller/AdminUserController.java
- backend/src/main/java/org/ftclub/cabinet/user/controller/UserController.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/BanPolicyImpl.java
- backend/src/main/java/org/ftclub/cabinet/user/repository/UserOptionalFetcher.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserServiceImpl.java
- backend/src/main/resources/log4j2.xml
- log4j2를 이용해서 logger를 추가했습니다
- sql 을 확인하고 싶으시면 application-local 파일을 업데이트 하신 후 log4j2.xml 파일의 주석 부분을 해제해주시면 됩니다.
- 각 메서드 호출 시 info 레벨로 출력되도록 설정해놨습니다.
> [BE] FEAT: logger 추가

- backend/build.gradle
- backend/src/main/java/org/ftclub/cabinet/ping/PingController.java
- backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenProviderTest.java
- backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenValidatorTest.java
- backend/src/test/java/org/ftclub/cabinet/auth/service/OauthServiceTest.java
- backend/src/test/java/org/ftclub/cabinet/user/repository/AdminUserRepositoryTest.java
- backend/src/test/java/org/ftclub/cabinet/user/repository/BanHistoryRepositoryTest.java
- backend/src/test/java/org/ftclub/cabinet/user/repository/UserOptionalFetcherTest.java
- backend/src/test/java/org/ftclub/cabinet/user/repository/UserRepositoryTest.java
> juni4를 삭제하고 사용하지 않는 몇몇 모듈을 삭제했습니다.
> [BE] junit4 모듈 삭제, 사용하지 않는 모듈 삭제

- backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/lent/domain/LentHistory.java
- backend/src/main/java/org/ftclub/cabinet/lent/repository/LentRepository.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/statistics/service/StatisticsFacadeServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/BanHistory.java
- backend/src/main/java/org/ftclub/cabinet/user/repository/BanHistoryRepository.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserServiceImpl.java
- backend/src/test/java/org/ftclub/cabinet/lent/service/LentServiceImplTest.java
- backend/src/test/java/org/ftclub/cabinet/mapper/UserSessionMapperTest.java
- backend/src/test/java/org/ftclub/cabinet/user/domain/BanHistoryTest.java
- backend/src/test/resources/application.yml
https://github.com/innovationacademy-kr/42cabi/issues/1220
BanHistory의 User에 관한 Many To One,
LentHistory에서 User와 Cabinet에 대한 Many To One 조인 컬럼을 추가하였습니다.
우선적으로 적용할 수 있는 부분에 대해서는 적용하였습니다.
> [BE] SPRING JoinColumn 적용

- backend/src/main/java/org/ftclub/cabinet/user/controller/AdminUserController.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/BanHistory.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/BanPolicy.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/BanPolicyImpl.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/User.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/UserAspect.java
- backend/src/main/java/org/ftclub/cabinet/user/repository/BanHistoryRepository.java
- backend/src/main/java/org/ftclub/cabinet/user/repository/UserOptionalFetcher.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/utils/DateUtil.java
DateUtil과 user 관련하여 Date를 LocalDateTime으로 변경하였습니다.
https://github.com/innovationacademy-kr/42cabi/issues/1213
> [BE] FIX: DateUtil 및 user 관련 Date -> LocalDateTime으로 변경/#1213

- backend/src/main/java/org/ftclub/cabinet/auth/domain/AuthAspect.java
기존의 불필요한 로직이었던 Cookie 체크하는 부분을 삭제하였습니다.
> [BE] FIX: AuthAspect의 쿠키 체크 로직 삭제 - 불필요함

- backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/dto/CabinetSimpleDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/CabinetSimplePaginationDto.java
- backend/src/main/java/org/ftclub/cabinet/mapper/CabinetMapper.java
- backend/src/main/java/org/ftclub/cabinet/search/controller/SearchController.java
요청하신 cabinets-simple 만들었습니다!
노션 v4 api에 반환값과 api 적어두었습니다 더 필요한 거 있으면 다시 말씀해주십쇼
> [BE] FEAT: cabinet-simple 추가

- frontend/src/pages/admin/AdminHomePage.tsx
https://github.com/innovationacademy-kr/42cabi/issues/1249
해당 에러는 api 요청되기 전 lineChart에 초기값이 없어서 생기는 에러였습니다.
더미 초기 데이터를 만드는 함수를 추가하여 해당 에러를 해결했습니다.
> [FE] BUG: LineChart 에러 해결 #1249

- backend/src/main/java/org/ftclub/cabinet/cabinet/domain/Cabinet.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/User.java
- backend/src/test/java/org/ftclub/cabinet/auth/domain/ApiRequestManagerUnitTest.java
- backend/src/test/java/org/ftclub/cabinet/lent/domain/LentHistoryTest.java
- backend/src/test/java/org/ftclub/cabinet/lent/domain/LentHistoryUnitTest.java
- backend/src/test/java/org/ftclub/cabinet/mapper/LentMapperTest.java
#1248 시스템 스케줄러 관련 기능 구현을 위해 다른 도메인에 있는 코드를 추가한 부분이 있습니다.
해당 코드들에 대한 테스트 케이스를 추가했습니다.
`FtApiManager`는 Security를 도입하면 사용하게 되지 않을 부분이고 외부 서비스 의존이므로 일단 테스트를 생략했습니다.
`LentService` 에 추가한 `getAllActiveLents`도 단순 조회용도이고 서비스에서 해주는 로직이 없어 해당 서비스에서 의존하는 Mapper만 테스트했습니다. 
추후 `LentRepository`에 대한 테스트 정도만 추가하면 문제 없을 것 같습니다..!
> [BE] TEST: 시스템 스케줄러 의존 모듈 테스트 케이스 추가

- backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/dto/BlockedUserPaginationDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/BrokenCabinetPaginationDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/CabinetInfoPaginationDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/CabinetPaginationDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/LentHistoryPaginationDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/OverdueUserCabinetPaginationDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/UserCabinetPaginationDto.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/mapper/CabinetMapper.java
- backend/src/main/java/org/ftclub/cabinet/mapper/LentMapper.java
- backend/src/main/java/org/ftclub/cabinet/mapper/UserMapper.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/AdminUser.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/BanHistory.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserServiceImpl.java
- backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenProviderUnitTest.java
- backend/src/test/java/org/ftclub/cabinet/user/domain/BanHistoryTest.java
- backend/src/test/java/org/ftclub/cabinet/user/domain/UserTest.java
- backend/src/test/java/org/ftclub/cabinet/user/repository/AdminUserRepositoryTest.java
- backend/src/test/java/org/ftclub/cabinet/user/service/UserFacadeServiceTest.java
- backend/src/test/java/org/ftclub/cabinet/user/service/UserServiceUnitTest.java
https://github.com/innovationacademy-kr/42cabi/issues/1241
totalPage를 totalLength로 변경했습니다.
> [BE] FIX: totalPage -> totalLength 변경 #1241

- .idea/misc.xml
- backend/src/main/java/org/ftclub/cabinet/dto/UserBlackholeInfoDto.java
- backend/src/main/java/org/ftclub/cabinet/user/repository/UserRepository.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/utils/blackhole/manager/BlackholeManager.java
- backend/src/main/java/org/ftclub/cabinet/utils/scheduler/SystemScheduler.java
- backend/src/test/java/org/ftclub/cabinet/utils/blackhole/manager/BlackholeManagerUnitTest.java
블랙홀 스케줄러 구현 및 테스트 코드 작성을 완료했습니다.
> [BE] FEAT: 블랙홀 스케줄러 구현 및 테스트

- backend/src/main/java/org/ftclub/cabinet/auth/service/FtApiManager.java
- backend/src/main/java/org/ftclub/cabinet/utils/blackhole/manager/BlackholeManager.java
- backend/src/main/java/org/ftclub/cabinet/utils/leave/absence/LeaveAbsenceManager.java
- backend/src/main/java/org/ftclub/cabinet/utils/scheduler/SystemScheduler.java
- backend/src/test/java/org/ftclub/cabinet/utils/blackhole/manager/BlackholeManagerUnitTest.java
- backend/src/test/resources/application.yml
- `ServiceException`을 던지면 이를 `ExceptionController`에서 핸들링할 것으로 착각해서
스케줄러에서 `ServiceException`를 던지는 부분을 수정하고,
스케줄러 내에서 발생하는 예외는 모두 스케줄러 안에서 처리하도록 변경했습니다.
- 에러 로그가 의미가 더 잘 드러나도록 일부분을 수정했습니다.
- 하드코딩된 크론 표현식을 yml파일로 빼두었습니다. 
- 이에 따라 노션에 yml 파일을 업데이트했습니다. 미리 받아두시길 바랍니다! (dev, prod에도 반영)
> [BE] ENHANCE: 스케줄러 관련 개선사항

- frontend/src/pages/admin/AdminHomePage.tsx
https://github.com/innovationacademy-kr/42cabi/issues/1255
> [FE] BUG:adminHomePage 스크롤이 안되는 버그 수정

- Dockerfile.main
Reverts innovationacademy-kr/42cabi#1262
> Revert "dev to main"

- backend/src/main/java/org/ftclub/cabinet/config/CorsConfig.java
> [BE] FIX: CORS 에러 수정

- backend/src/main/java/org/ftclub/cabinet/lent/domain/LentPolicyImpl.java
> [BE] HOTFIX: 공유사물함 첫 대여에서 만료 시간 설 정 시, NPE 버그 수정

- backend/src/main/java/org/ftclub/cabinet/auth/service/AuthService.java
- backend/src/test/java/org/ftclub/cabinet/auth/service/AuthServiceUnitTest.java
> [BE] HOTFIX: blackholedAt localdatetime으로 변경이 안 되는 문제 해결

- scripts/deploy-main.sh
> [dev to main] - docker file 수정

- backend/src/main/java/org/ftclub/cabinet/lent/domain/LentPolicyImpl.java
- backend/src/test/java/org/ftclub/cabinet/lent/domain/LentPolicyUnitTest.java
#1294에 따라 LentPolicy에서 블랙홀 체크 로직을 제거했습니다.
> [BE] LentPolicy 블랙홀 검증 로직 삭제

- backend/src/test/java/org/ftclub/cabinet/lent/domain/LentPolicyUnitTest.java
> [BE] FIX: 문제 발생 코드 주석처리 #1294

- frontend/src/assets/data/maps.ts
- frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
- frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
- frontend/src/components/CabinetInfoArea/CountTime/CountTime.container.tsx
- frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
- frontend/src/components/Modals/CancelModal/CancelModal.tsx
- frontend/src/recoil/atoms.ts
https://github.com/innovationacademy-kr/42cabi/issues/1327
- IN_SESSION에 있을 때 대기열 취소 모달을 추가하였습니다.
- timeover 상태 props에서 recoil로 상태 변화를 감지하는 것으로 변경하였습니다.
> [FE] 대기열 취소 모달 추가#1327

- deploy-main/deploy.sh
> [COMMON] FIX: main 배포 스크립트 변경

- backend/build.gradle
관련링크: https://github.com/pinpoint-apm/pinpoint/issues/10191
핀포인트 적용을 위해서 mariadb client버전을 변경하였습니다.
> [BE] FIX: pinpoint에서 지원되는 버전으로 mariadb client 버전 변경

- backend/src/main/java/org/ftclub/cabinet/lent/repository/LentOptionalFetcher.java
- backend/src/main/java/org/ftclub/cabinet/lent/repository/LentRepository.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/utils/scheduler/SystemScheduler.java
- backend/src/main/resources/log4j2-local.yml
> 사물함 반납 후 Pending 처리 #1336

- backend/src/main/java/org/ftclub/cabinet/exception/ExceptionStatus.java
- backend/src/main/java/org/ftclub/cabinet/lent/repository/LentOptionalFetcher.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentService.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
https://github.com/innovationacademy-kr/42cabi/issues/1367
Closing #1367
> [BE] REFACTOR: 공유사물함 1명일때, 연장권 사용 불가능 추가

- backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/lent/repository/LentRedis.java
초대코드 expire time을 테스트용이었던 30초에서 10분으로 수정했습니다.
> [CHORE] redis shadow key expire time을 30초에서 10분으로 변경

- backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
- admin에서 연체된 사물함을 강제 반납시키는 경우 연체한 유저에게 penalty를 적용합니다.
https://github.com/innovationacademy-kr/42cabi/issues/#1364
> [BE] admin에서 연체된 사물함 반납 시 유저에게 ban 적용

- backend/src/main/java/org/ftclub/cabinet/auth/service/FtApiManager.java
- backend/src/main/java/org/ftclub/cabinet/utils/leave/absence/LeaveAbsenceManager.java
- backend/src/main/java/org/ftclub/cabinet/utils/mail/EmailSender.java
- backend/src/main/java/org/ftclub/cabinet/utils/scheduler/SystemScheduler.java
> [BE] HOTFIX: 연체관련 스케줄러 로직 수정

- backend/src/main/java/org/ftclub/cabinet/lent/repository/LentRedis.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
> [BE] FIX: fix redis_error

- backend/src/main/java/org/ftclub/cabinet/auth/domain/TokenValidator.java
- backend/src/main/java/org/ftclub/cabinet/dto/MyProfileResponseDto.java
- backend/src/main/java/org/ftclub/cabinet/mapper/UserMapper.java
- backend/src/main/java/org/ftclub/cabinet/user/repository/LentExtensionOptionalFetcher.java
- backend/src/main/java/org/ftclub/cabinet/user/repository/LentExtensionRepository.java
- backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
- backend/src/test/java/org/ftclub/cabinet/user/controller/UserControllerTest.java
- backend/src/test/java/org/ftclub/cabinet/user/service/UserFacadeServiceTest.java
lentExtension 관련 비즈니스 로직 DB 쿼리에서 서비스단으로 이동 및 버그 수정
> [BE] Mypage에서 내 연장권 보유 여부 반영 안되는 버그 수정

- backend/src/main/java/org/ftclub/cabinet/exception/DomainException.java
- backend/src/main/java/org/ftclub/cabinet/lent/repository/LentRedis.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
> Be/dev/fix share cabinet about redis error/#1413

- frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
- frontend/src/components/CabinetList/CabinetListItem/AdminCabinetListItem.tsx
- frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
- frontend/src/components/Modals/InvitationCodeModal/InvitationCodeModal.container.tsx
https://github.com/innovationacademy-kr/42cabi/issues/#1425
cabinetitems와 클릭한 모달의 사물함 상태가 다를 때 내 사물함이라면 내 사물함 정보를 업데이트하고 해당 층 전체를 업데이트하고
내 사물함이 아니면 해당 층만 업데이트하도록 수정
> Fe/dev/fix share session rendering#1425

- backend/src/main/java/org/ftclub/cabinet/user/repository/LentExtensionOptionalFetcher.java
- backend/src/main/java/org/ftclub/cabinet/user/repository/LentExtensionRepository.java
- frontend/src/components/Card/LentInfoCard/LentInfoCard.container.tsx
> Be/dev/fix put lent extension to my profile response dto/#1424

- backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
> [BE] REFACTOR: 연장권 없을경우 extension dtoNull return 하도록

- backend/src/main/java/org/ftclub/cabinet/user/domain/LentExtensionPolicy.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/LentExtensionPolicyImpl.java
- backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionServiceImpl.java
> [BE] FIX: 연장권 검증로직 수정

- backend/src/main/java/org/ftclub/cabinet/CabinetApplication.java
- backend/src/main/java/org/ftclub/cabinet/utils/TimeResponseFilter.java
> [BE] 응답에 현재시간 필터 추가

- backend/src/main/java/org/ftclub/cabinet/CabinetApplication.java
- backend/src/main/java/org/ftclub/cabinet/utils/TimeResponseFilter.java
> [BE] HOTFIX: 필터 시간 두번찍히는 오류 수정

- backend/src/main/java/org/ftclub/cabinet/user/domain/LentExtension.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/LentExtensions.java
- backend/src/main/java/org/ftclub/cabinet/user/repository/LentExtensionOptionalFetcher.java
- backend/src/main/java/org/ftclub/cabinet/user/repository/LentExtensionRepository.java
- backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionServiceImpl.java
> [BE] HOTFIX: LentExtension Duplicate 에러 수정 및 다중소지 가능하게 로직수정

- backend/src/main/java/org/ftclub/cabinet/dto/MyProfileResponseDto.java
- frontend/src/pages/Layout.tsx
> [BE] HOTFIX: MyProfile에 현재시간 형식에 맞게 출력

- frontend/src/pages/ProfilePage.tsx
- 사용되지 않는 알림 카드 프로필페이지에서 제거
https://github.com/innovationacademy-kr/42cabi/issues/1447
> [FE] FIX: 프로필 페이지에서 알림 카드 제거 #1447

- frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.tsx
- frontend/src/pages/PendingPage/PendingPage.tsx
> [FE] FIX: 오픈예정에서 사용가능으로 변경

- frontend/src/pages/PendingPage/components/FloorContainer.tsx
> [FE] HOTFIX: pendingPage 사용가능한 사물함 없습니다 문구 수정

- backend/database/cabi_local.sql
- backend/src/main/java/org/ftclub/cabinet/dto/LentExtensionResponseDto.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/LentExtension.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/LentExtensions.java
- backend/src/main/java/org/ftclub/cabinet/user/repository/LentExtensionOptionalFetcher.java
- backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
- backend/src/test/java/org/ftclub/cabinet/user/controller/UserControllerTest.java
- backend/src/test/java/org/ftclub/cabinet/user/service/LentExtensionServiceTest.java
- backend/src/test/java/org/ftclub/cabinet/user/service/UserFacadeServiceTest.java
- backend/src/test/resources/application.yml
연장권 관련한 로직 변경하였습니다.
- deleted_at으로 소프트 딜리트 이용하던 부분 제거
- 제거에 따른 로직 수정, 스케줄링 되던 deleteExtensions 메서드 제거.
> HOTFIX : Dev to Main

- backend/src/main/java/org/ftclub/cabinet/occupiedtime/OccupiedTimeController.java
- backend/src/main/java/org/ftclub/cabinet/occupiedtime/OccupiedTimeManager.java
> [BE] HOTFIX: 80시간이상 120시간미만 지급로직 (임시)

- backend/src/main/java/org/ftclub/cabinet/occupiedtime/OccupiedTimeController.java
> [BE] HOTFIX: 연장권 지급 임시로직 비활성화

- frontend/src/api/axios/axios.custom.ts
- frontend/src/components/Card/NotificationCard/NotificationCard.container.tsx
- frontend/src/components/Card/NotificationCard/NotificationCard.tsx
- frontend/src/components/Common/ToggleSwitch.tsx
- 알람을 백앤드에서 올바르게 받을 수 있도록 Object {} 화 시키던 것을 제거했습니다.
- 과도하게 많은 state 를 사용하여 원래 알림 상태 (테이블상의 알림 상태) 와 바뀐 알림 상태를 추적하던 로직을 간소화하고, 취소 시 강제 리랜더링을 하는 부분의 key 로 alarm 을 사용하여 전체적인 코드 길이를 줄였습니다.
- NotificationCard 내의 반복적인 코드 사용을 줄였습니다.
https://github.com/innovationacademy-kr/42cabi/issues/1398
> [FE] FIX: 알람 기능 정상 동작하도록 수정 및 로직 간소화 #1398

- README.md
https://github.com/innovationacademy-kr/Cabi/issues/1494
> [BE] DOCS: sohyupar 계정 추가#1494

- backend/src/main/java/org/ftclub/cabinet/alarm/domain/AnnouncementAlarm.java
- backend/src/main/java/org/ftclub/cabinet/alarm/domain/ExtensionExpirationImminentAlarm.java
- backend/src/main/java/org/ftclub/cabinet/alarm/domain/ExtensionIssuanceAlarm.java
- backend/src/main/java/org/ftclub/cabinet/alarm/domain/LentExpirationAlarm.java
- backend/src/main/java/org/ftclub/cabinet/alarm/domain/LentExpirationImminentAlarm.java
- backend/src/main/java/org/ftclub/cabinet/alarm/domain/LentSuccessAlarm.java
- backend/src/main/java/org/ftclub/cabinet/alarm/dto/MailDto.java
- backend/src/main/java/org/ftclub/cabinet/alarm/handler/EmailAlarmSender.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
https://github.com/innovationacademy-kr/42cabi/issues/1499
> [BE] HOTFIX: 이메일 알람 형식수정

- README.md
https://github.com/innovationacademy-kr/42cabi/issues/1502
> [COMMON] DOCS: readme 프로젝트 멤버 추가 #1502

- README.md
https://github.com/innovationacademy-kr/42cabi/issues/1505
> [COMMON] DOCS: README에 이름 추가

- backend/src/main/java/org/ftclub/cabinet/config/CabinetProperties.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentPolicyService.java
> [BE] REFACTOR: 피드백반영 swap기능을 사용하기 위한 최소일수 변수로 빼기

- backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetQueryService.java
- backend/src/main/java/org/ftclub/cabinet/lent/repository/LentRepository.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentPolicyService.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentQueryService.java
- backend/src/main/java/org/ftclub/cabinet/utils/DateUtil.java
- backend/src/test/java/org/ftclub/cabinet/utils/DateUtilTest.java
> [BE] swap 시 메모 및 비밀번호 같이 이동하도록 수정, cabinet에 Lock 걸고 가져오도록 수정

- backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeService.java
userId로 사물함 Id를 찾아서 오류 발생 -> 404 에러 던짐 -> 프론트에서 에러 무시
일단 백엔드 부분 고쳤고 seonghui님이 곧 프론트 HOTFIX로 수정 후 올리실 듯
> [BE] HOTFIX: 연장권 사용 시 userId로 cabinet 검색하는 오류 수정

- .idea/misc.xml
- backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetQueryService.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentCommandService.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/User.java
- backend/src/main/java/org/ftclub/cabinet/user/service/BanHistoryCommandService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionCommandService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionQueryService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserCommandService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserQueryService.java
- backend/src/main/java/org/ftclub/cabinet/utils/blackhole/manager/BlackholeManager.java
> [BE] HOTFIX: 이전에 블랙홀이었던 유저 대여 시도시, 블랙홀 새로고침 로직 추가 + 연장권 사용 에러 수정

- backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/user/repository/LentExtensionRepository.java
- backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionQueryService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserQueryService.java
> [BE] HOTFIX: DEV TO MAIN

- backend/src/main/java/org/ftclub/cabinet/alarm/config/AlarmProperties.java
- backend/src/main/java/org/ftclub/cabinet/alarm/domain/LentExpirationImminentAlarm.java
- backend/src/main/java/org/ftclub/cabinet/alarm/handler/AlarmEventHandler.java
- backend/src/main/java/org/ftclub/cabinet/alarm/handler/SlackAlarmSender.java
- backend/src/main/java/org/ftclub/cabinet/ping/PingController.java
> [BE] FEAT: 연체 당일 알람 추가

- frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
- /lent/me 실패 시 에러 처리가 되어있지 않아 이를 수정했습니다.
https://github.com/innovationacademy-kr/42cabi/issues/1549
> [FE] FIX: /lent/me 실패 시 예외상황 핸들링 #1549

- backend/src/main/java/org/ftclub/cabinet/admin/lent/service/AdminLentFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/lent/repository/ClubLentRepository.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/ClubLentQueryService.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeService.java
> [BE] 동아리 사물함 여러개 배정 오류 #1560

- backend/src/main/java/org/ftclub/cabinet/slack/controller/SlackController.java
- backend/src/main/java/org/ftclub/cabinet/slack/dto/SlackMessageDto.java
- backend/src/main/java/org/ftclub/cabinet/slack/service/SlackFacadeService.java
> [BE] FEAT: slack message

- frontend/src/components/Card/ClubNoticeCard/ClubNoticeCard.tsx
- frontend/src/components/Club/ClubInfo.tsx
- frontend/src/components/Modals/ClubModal/ClubMemoModal.tsx
- 동아리 변경시 열린 Menu 들을 닫도록 수정
- 동아리 메모 line-spacing 조절
- 동아리 맴버를 불러올 때 100명씩 불러오도록 수정
https://github.com/innovationacademy-kr/42cabi/issues/1562
> [FE] FIX: 동아리 페이지 버그 및 사용성 수정 #1562

- frontend/src/Presentation/components/Details/DetailContent.container.tsx
- frontend/src/Presentation/constants/policy.ts
- frontend/src/Presentation/pages/Layout.tsx
- frontend/src/Presentation/pages/admin/AdminLayout.tsx
- frontend/src/Presentation/utils/dateUtils.ts
- frontend/src/index.css
- 상세일정 페이지에서 비어있는 일정 4,5 월에 '신청하기' 버튼이 보이지 않는 현상 수정
- 서브 컬러 추가
https://github.com/innovationacademy-kr/42cabi/issues/1587
> [COMMON] FIX: 수요지식회 Post 패치 #1587

- .github/workflows/front-cicd.yaml
- 프론트엔드 폴더 구조 변경에 따라 Asset 폴더가 변경되어, 이에 맞춰 frontend cicd 디렉토리를 변경하였습니다.
https://github.com/innovationacademy-kr/42cabi/issues/1586
> [COMMON] FIX: asset 디렉토리 변경에 따른 frontend main cicd 수정 #1586

- backend/src/main/java/org/ftclub/cabinet/dto/ActiveCabinetInfoDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/ItemDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/MyItemResponseDto.java
- backend/src/main/java/org/ftclub/cabinet/item/controller/ItemController.java
- backend/src/main/java/org/ftclub/cabinet/item/repository/ItemHistoryRepository.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemHistoryQueryService.java
- backend/src/main/java/org/ftclub/cabinet/mapper/LentMapper.java
빌드 오류 수정 및 중복 코드 삭제, 비즈니스 로직 중 안 맞는 부분 수정
> Be/dev/feat coin/jpark2#1604

- backend/src/main/java/org/ftclub/cabinet/admin/item/controller/AdminItemController.java
- backend/src/main/java/org/ftclub/cabinet/dto/ItemAssignDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/ItemCreateDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/ItemDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/MyItemResponseDto.java
- backend/src/main/java/org/ftclub/cabinet/item/controller/ItemController.java
- backend/src/main/java/org/ftclub/cabinet/item/domain/ItemHistory.java
- backend/src/main/java/org/ftclub/cabinet/item/domain/ItemType.java
- backend/src/main/java/org/ftclub/cabinet/item/domain/Sku.java
- backend/src/main/java/org/ftclub/cabinet/item/repository/ItemRepository.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemCommandService.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/mapper/ItemMapper.java
> [BE] FEAT: 인벤토리 조회, ADMIN 테스트용 아이템 생성, 할당 기능 추가

- backend/src/main/java/org/ftclub/cabinet/admin/item/controller/AdminItemController.java
- backend/src/main/java/org/ftclub/cabinet/admin/item/service/AdminItemFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/dto/ItemCreateDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/ItemStoreDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/ItemStoreResponseDto.java
- backend/src/main/java/org/ftclub/cabinet/exception/ExceptionStatus.java
- backend/src/main/java/org/ftclub/cabinet/item/controller/ItemController.java
- backend/src/main/java/org/ftclub/cabinet/item/domain/Item.java
- backend/src/main/java/org/ftclub/cabinet/item/domain/ItemType.java
- backend/src/main/java/org/ftclub/cabinet/item/domain/Sku.java
- backend/src/main/java/org/ftclub/cabinet/item/repository/ItemRepository.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemCommandService.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemHistoryCommandService.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemPolicyService.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemQueryService.java
- backend/src/main/java/org/ftclub/cabinet/mapper/ItemMapper.java
Item 필드 변경
- name, description 삭제 : 아이템 종류(ItemType)에 따라 동일한 설명, 이름을 가지기 때문에 Enum 내부 필드로 이동
- 아이템 구매 시 Coin 계산 로직 수정 : 아이템 가격이 음수임에 따라 구매 시 뺄셈에서 덧셈으로 변경
- 아이템 추가 및 재고 등록 구조 정리 : admin의 해당 로직에 Facade Service가 빠져있어 추가
> Be/dev/feat coin/error fix#1604

- backend/src/main/java/org/ftclub/cabinet/dto/CoinHistoryDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/CoinHistoryPaginationDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/ItemDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/ItemHistoryDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/ItemHistoryPaginationDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/ItemStoreDto.java
- backend/src/main/java/org/ftclub/cabinet/item/controller/ItemController.java
- backend/src/main/java/org/ftclub/cabinet/item/repository/ItemHistoryRepository.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemHistoryQueryService.java
- backend/src/main/java/org/ftclub/cabinet/mapper/ItemMapper.java
프론트 요구사항으로 기간 조회(start, end)가 아닌 pagination 조회 방식으로 변경
> Be/dev/feat coin/fix pagination#1604

- frontend/src/Cabinet/components/Store/StoreCoinPick.tsx
- frontend/src/Cabinet/components/Store/StoreInfo.tsx
- frontend/src/Cabinet/pages/ItemUsageLogPage.tsx
- frontend/src/Cabinet/pages/StoreMainPage.tsx
> Common/dev/feat coin/miyu#1604

- backend/src/main/java/org/ftclub/cabinet/admin/statistics/controller/AdminStatisticsControllerV5.java
- backend/src/main/java/org/ftclub/cabinet/admin/statistics/service/AdminStatisticsFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/dto/CoinCollectStatisticsDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/CoinCollectedCountDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/TotalCoinAmountDto.java
- backend/src/main/java/org/ftclub/cabinet/item/controller/ItemController.java
- backend/src/main/java/org/ftclub/cabinet/item/repository/ItemHistoryRepository.java
- backend/src/main/java/org/ftclub/cabinet/item/repository/ItemRedis.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemHistoryQueryService.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemRedisService.java
- 정책이 시행된 시점부터 현재까지 발행된 재화의 총량과, 사용된 재화의 총량 확인
- 원하는 기간(한 달)동안 동전 줍기 기능의 사용자 수 확인
- 동전을 주운 회수 별 사용자 수 확인
https://github.com/innovationacademy-kr/42cabi/issues/1604
> Common/dev/feat coin/admin/hyowchoi#1604

- backend/src/main/java/org/ftclub/cabinet/admin/statistics/controller/AdminStatisticsControllerV5.java
- backend/src/main/java/org/ftclub/cabinet/admin/statistics/service/AdminStatisticsFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/dto/CoinCollectStatisticsDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/CoinCollectedCountDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/TotalCoinAmountDto.java
- backend/src/main/java/org/ftclub/cabinet/item/controller/ItemController.java
- backend/src/main/java/org/ftclub/cabinet/item/repository/ItemHistoryRepository.java
- backend/src/main/java/org/ftclub/cabinet/item/repository/ItemRedis.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemHistoryCommandService.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemHistoryQueryService.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemRedisService.java
- backend/src/main/java/org/ftclub/cabinet/lent/repository/LentRepository.java
- backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionManager.java
- backend/src/main/java/org/ftclub/cabinet/utils/lock/IntegerLock.java
- backend/src/main/java/org/ftclub/cabinet/utils/lock/LockUtil.java
- backend/src/main/java/org/ftclub/cabinet/utils/lock/VoidLock.java
https://github.com/innovationacademy-kr/42cabi/issues/1604
1. Redis 데이터 정합성을 위해 동기화 로직 작성
- 동기화 시 로직을 전달할 함수형 인터페이스 추가(반환 타입 void, int 2가지)
- 동기화를 위한 동기화 유틸(LockUtil) 추가
- LockUtil 내부에 userId 및 로직을 전달받을 함수형 인터페이스를 파라미터로 가지는 동기화 메서드 추가
> 함수형 인터페이스란?
> https://jiwon.oopy.io/4f13bf20-9346-44ca-9805-d7d69f898878
2. 기존 연장권을 발급하는 스케줄러 로직을 재화 발급하도록 변경
- 기존 연장권 발급에서 재화 보상 아이템 발급 형태로 변경(재화 금액 증가)
- 재화 발급 시 redis에 재화 변동 내역 반영(각 유저의 재화 보유량 + 어드민의 전체 재화 통계 데이터)
> [!WARNING] 
> hyowchoi님의 작업 브랜치인 .../admin/hyowchoi#1604 브랜치를 pull 당겨온 후 작업한 내용이므로
> 반드시 해당 브랜치의 PR이 merge 된 이후 위 PR을 merge 해야합니다
> Common/dev/feat coin/admin/jpark2#1604

- backend/src/main/java/org/ftclub/cabinet/admin/dto/AdminItemHistoryDto.java
- backend/src/main/java/org/ftclub/cabinet/admin/dto/AdminItemHistoryPaginationDto.java
- backend/src/main/java/org/ftclub/cabinet/admin/item/controller/AdminItemController.java
- backend/src/main/java/org/ftclub/cabinet/admin/item/service/AdminItemFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/admin/statistics/service/AdminStatisticsFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/dto/CoinAmountDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/CoinStaticsDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/ItemAssignPaginationDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/ItemAssignRequestDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/ItemAssignResponseDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/ItemPurchaseCountDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/ItemStatisticsDto.java
- backend/src/main/java/org/ftclub/cabinet/item/repository/ItemHistoryRepository.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemCommandService.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemHistoryQueryService.java
- backend/src/main/java/org/ftclub/cabinet/mapper/ItemMapper.java
- 특정 유저의 아이템 이력 조회 기능
- 재화 사용 통계 기능
- 아이템 통계 기능 기능
https://github.com/innovationacademy-kr/42cabi/issues/1604
> Common/dev/feat coin/admin/sohyupar#1604

- frontend/src/Cabinet/components/Common/Dropdown.tsx
- frontend/src/Presentation/components/Modals/EditStatusModal/EditStatusModal.tsx
- Dropdown 컴포넌트에서 selectedIdx 가 음수인 경우와 넘겨진 options props 가 빈 배열일 경우 존재하지 않는 index 를 참조하거나 undefined 의 imageSrc 를 참조해 앱이 Crash 나는 오류 수정
- #1626
https://github.com/innovationacademy-kr/42cabi/issues/1626
> [FE] FIX: Dropdown 컴포넌트 예외처리 추가 #1626

- backend/src/main/java/org/ftclub/cabinet/admin/item/service/AdminItemFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemRedisService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionManager.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeService.java
> [BE] FIX : 어드민으로 코인 지급 시 redis 반영 안되는 현상 수정:

- frontend/src/Cabinet/components/Modals/ExtendModal/ExtendModal.tsx
https://github.com/innovationacademy-kr/42cabi/issues/1638
> [FE] FIX : 연장권 사용 모달에 출석 연장권 보상 안보이는거 수정

- frontend/src/Cabinet/components/Modals/ExtendModal/ExtendModal.tsx
https://github.com/innovationacademy-kr/Cabi/issues/1638
> [FE] FIX : 연장권 사용 모달에 출석 연장권 보상 안보이는거 수정 #1639

- frontend/src/Cabinet/components/Modals/ExtendModal/ExtendModal.tsx
https://github.com/innovationacademy-kr/42cabi/issues/1642
> [FE] ETC: 연장권 사용모달에서의 테스트 콘솔로그 삭제#1642

- backend/src/main/java/org/ftclub/cabinet/ping/PingController.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/User.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserCommandService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserQueryService.java
> [BE] FIX: Redis to DB coin 임시 메서드 삭제

- README.md
https://github.com/innovationacademy-kr/42cabi/issues/1654
> [COMMON] DOCS: readme에 saymyname 과제 수행 및 이름 추가 #1654

- README.md
- frontend/package-lock.json
https://github.com/innovationacademy-kr/42cabi/issues/1655
> [COMMON] DOCS: README 이름 추가 #1655

- README.md
> [COMMON] DOCS: README에 junsbae 추가 #1656

- frontend/src/Cabinet/api/axios/axios.log.ts
- `access_token` 과 `admin_access_token` 없이 처음 로그인을 시도할 시 없는 string 의 함수를 접근해 발생하는 TypeError 에러 처리 추가
https://github.com/innovationacademy-kr/42cabi/issues/1670
> [FE] HOTFIX: axios.log.ts 에서 token 이 없을 시 예외처리 추가 #1670

- frontend/src/Cabinet/components/CabinetList/CabinetList.container.tsx
- frontend/src/Cabinet/components/LeftNav/LeftMainNav/LeftMainNav.container.tsx
- frontend/src/Cabinet/components/MapInfo/MapGrid/MapGrid.tsx
- frontend/src/Cabinet/pages/MainPage.tsx
- frontend/src/Cabinet/recoil/atoms.ts
https://github.com/innovationacademy-kr/42cabi/issues/1673
> Fe/dev/fix ev section alert/#1673

- backend/src/main/java/org/ftclub/cabinet/auth/service/AuthFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/user/repository/UserRepository.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserCommandService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserQueryService.java
- backend/src/main/java/org/ftclub/cabinet/utils/blackhole/manager/BlackholeManager.java
> [BE] FIX: AGU user deletedAt set to null

- frontend/src/Presentation/components/LeftNav/LeftMainNav/LeftMainNav.container.tsx
- navigate 경로를 수정해서 정상적으로 admin의 detail로 연결되도록 했습니다.
- 통일성을 위해서 상대 경로로 작성되어있던 부분을 절대 경로로 수정했습니다.
#1688
> [FE] BUG: navigate 경로 수정 #1688

- README.md
https://github.com/innovationacademy-kr/42cabi/issues/1724
> [COMMON] DOCS : readme에 jongmlee 이름 추가 #1724

- README.md
https://github.com/innovationacademy-kr/42cabi/issues/1722
> [COMMON] DOCS: README에 7차 백엔드 멤버 sokwon 추가 #1722

- README.md
https://github.com/innovationacademy-kr/42cabi/issues/1729
> DOCS : README에 7차 백엔드 멤버 yeoshin 추가 #1729

- frontend/src/Cabinet/api/axios/axios.instance.ts
- frontend/src/Cabinet/pages/ProfilePage.tsx
- frontend/src/Cabinet/recoil/atoms.ts
- frontend/src/Cabinet/types/dto/user.dto.ts
- frontend/src/Cabinet/types/enum/error.type.enum.ts
- frontend/src/Presentation/types/common/login.ts
1. 연동된 sns 계정 정보 property 수정
2. 403 에러 발생 시 로그인으로 리다이렉트
3. 일반 요청에는 쿠키를 포함하지 않도록 수정
> Be/dev/feat sns login#1726

- frontend/src/Cabinet/pages/AvailablePage.tsx
5층 사물함 이용 금지로 인해 접근 불가 처리 
https://github.com/innovationacademy-kr/42cabi/issues/1753
> [FE] FIX: DISABLED_FLOOR 에 5 추가 #1753

- backend/src/main/java/org/ftclub/cabinet/admin/auth/service/AdminAuthService.java
- backend/src/main/java/org/ftclub/cabinet/auth/controller/AuthController.java
- backend/src/main/java/org/ftclub/cabinet/auth/service/AuthFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/auth/service/CookieService.java
- backend/src/main/java/org/ftclub/cabinet/auth/service/OauthFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/auth/service/OauthLinkFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/dto/LinkOauthRedirectDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/LinkOauthRedirectUrlServiceDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/LinkOauthTokenDto.java
- backend/src/main/java/org/ftclub/cabinet/dto/StateInfoDto.java
- backend/src/main/java/org/ftclub/cabinet/jwt/controller/JwtController.java
- backend/src/main/java/org/ftclub/cabinet/jwt/repository/JwtRedis.java
- backend/src/main/java/org/ftclub/cabinet/jwt/service/JwtProvider.java
- backend/src/main/java/org/ftclub/cabinet/jwt/service/JwtRedisService.java
- backend/src/main/java/org/ftclub/cabinet/jwt/service/JwtService.java
- backend/src/main/java/org/ftclub/cabinet/security/SecurityConfig.java
- backend/src/main/java/org/ftclub/cabinet/security/handler/CustomAuthorizationRequestResolver.java
- backend/src/main/java/org/ftclub/cabinet/security/handler/CustomSuccessHandler.java
- backend/src/main/java/org/ftclub/cabinet/security/handler/OAuth2ResolverConfig.java
- frontend/src/Cabinet/api/axios/axios.custom.ts
- frontend/src/Cabinet/api/axios/interceptors/axios.request.interceptors.ts
- frontend/src/Cabinet/api/axios/interceptors/axios.response.interceptors.ts
- frontend/src/Cabinet/api/react_cookie/cookies.ts
- frontend/src/Cabinet/components/Login/AdminLoginTemplate.tsx
- frontend/src/Cabinet/hooks/useOAuth.ts
- frontend/src/Cabinet/pages/HomePage.tsx
- frontend/src/Cabinet/pages/ProfilePage.tsx
- frontend/src/Cabinet/types/types.d.ts
https://github.com/innovationacademy-kr/42cabi/issues/1768
> [COMMON] REFACTOR : OAuth 로그인 / OAuth 계정 연동 구분 방식 변경 #1768

- frontend/src/Cabinet/api/axios/interceptors/axios.response.interceptors.ts
- frontend/src/Cabinet/components/Login/AdminLoginTemplate.tsx
- frontend/src/Cabinet/hooks/useOAuth.ts
- frontend/src/Cabinet/hooks/useOAuthStatus.ts
- frontend/src/Cabinet/hooks/useURLSearchParams.ts
- frontend/src/Cabinet/pages/HomePage.tsx
- frontend/src/Cabinet/pages/LoginPage.tsx
- frontend/src/Cabinet/pages/ProfilePage.tsx
> Fe/dev/refactor oauth link/#1770

- backend/build.gradle
- backend/src/main/java/org/ftclub/cabinet/config/S3Config.java
- backend/src/main/java/org/ftclub/cabinet/exception/ExceptionStatus.java
- backend/src/main/java/org/ftclub/cabinet/presentation/controller/S3ProbeTestController.java
- backend/src/main/java/org/ftclub/cabinet/presentation/service/ThumbnailStorageService.java
https://github.com/innovationacademy-kr/42cabi/issues/1773
> [BE] TEST: S3 연결 확인 로직

- frontend/.eslintrc.json
[변수 선언 키워드 컨벤션](https://www.notion.so/hyunja/Cabi-12275ba473cc4a24ba640d454dc8b7eb?source=copy_link#9a8e5bd4061d4efaa3cc78b91f7c117c)에 따라 var 키워드의 사용을 금지하는 ESLint 규칙을 추가했습니다.
https://github.com/innovationacademy-kr/42cabi/issues/1834
> [FE] FEAT: no-var eslint 규칙 추가

- frontend/src/Presentation/components/RegisterDatePicker.tsx
- frontend/src/Presentation/pages/HomePage.tsx
기존 수지회 참조하는 로직을 삭제합니다.
https://github.com/innovationacademy-kr/42cabi/issues/1745
> [HOTFIX] FE 네비게이터 수정
