- frontend/src/pages/Return.tsx
🐛  fix: extension button error
* UTC 기준 시간으로 시간이 설정되어 대한민국 시간과 9시간 차이가 발생하여 시간을 0시0분0초로 수정함.
> 🐛  fix: extension button error #83

- frontend/src/pages/Return.tsx
- Return Page 상에 존재하는 Extension 버튼의 활성화 날짜 계산이 잘못되어, 해당 부분을 수정하였습니다!
- Return Page / extension btn 
- Date 객체의 선언과 날짜 계산이 불분명한 부분도 문제였지만, 변수명을 조금 더 변별력 있게 지으면 오류를 방지할 수 있다고 생각되요.
- 실질적으로 만료기간을 나타내는 Date 객체의 이름이 그냥 "Date" 로 잡혀있어서 조금 헷갈렸답니다. 아직 변수명을 임의로 고치지는 않았습니다만, 다가오는 회의 때 논의 후, 명시성 있는 변수로 일괄변경해보면 어떨지 제안드려요!
ex) Date > nowDate    ->    expireDate > nowDate
> :bug: 05/22_Return Page의 연장버튼 활성화 날짜 오류 수정 #96

- backend/src/blackhole/blackhole.service.ts
- backend/src/blackhole/repository/blackhole.repository.ts
- backend/src/blackhole/repository/rawquery.blackhole.repository.ts
- 블랙홀에 빠진 유저를 삭제하는 대신 user_id를 음수로 바꾸고, intra_id 앞에 [BLACKHOLED]를 붙히도록 수정했습니다.
- user 한명 한명을 검사하는 도중 토큰이 만료됐을 때를 대비한 코드는 무한 루프의 가능성이 있을 것 같아 주석처리했습니다.
당장은 문제가 없으나 추후 문제가 생길 가능성이 있는 부분입니다.
- 1시간당 intra에 보낼 수 있는 Request의 수는 최대 1200번 입니다.
- 그래서 만약 블랙홀에 빠지지 않고 Cabi DB에 정보가 등록된 유저가 1200명이 넘어서면 1200명 이후부터는 검사가 진행되지 않을 수 있는 문제가 존재합니다.
> 블랙홀에 빠진 유저 예외 처리 완료

- frontend_v3/src/components/atoms/buttons/QuestionTestModal.tsx
- frontend_v3/src/components/atoms/buttons/QustionButton.tsx
#204 
**styled** 및 **fontAwesomeIcon** 사용하여 **우측 하단 이용안내 버튼** 구현했습니다.
아래는 구현 과정에서 생긴 질문입니다(`QuestionButton.tsx` 파일의 `line 24` 주석에 동일하게 기재되어 있습니다):
- 모달의 `open` 상태를 버튼과 모달 중 어느 컴포넌트에서 관리해야 할까요??
- 우선은 모달 컴포넌트를 버튼과 분리해서 따로 관리하고, 버튼 컴포넌트 내부에서 import해서 사용하도록 구현하여 `open` 상태 역시 버튼에서 관리하도록 만들었습니다
- 그런데 이렇게 만들면 컴포넌트를 충분히 독립적으로 추상화시킨 게 맞는지 모르겠습니다. 차라리 `open` 상태를 redux로 관리하는 게 맞을까요?
> fe_v3/Question Button

- frontend_v3/src/components/atoms/buttons/CheckButton.tsx
- frontend_v3/src/main.tsx
- frontend_v3/src/themes/muiCustomPaletteTheme.tsx.tsx
#204 
Mui `Button`으로 확인 및 취소 등에 사용되는 버튼 구현하였습니다.
- `Variant` : contained, outlined 등 3종류
- `color` : primary 등 7종류
- type이 “primary” | “secondary” 등 7개로 고정돼 있음
- 색상을 props로 받느라 인터페이스로 지정
- 인터페이스에 color: string으로 하면 타입 에러 발생
- mui에서 아예 고정되어있는 듯..?
- 그래서 primary 색상을 아예 보라색으로 바꾸기 위해 createTheme과 ThemeProvider 임포트 및 사용
- GlobalStyle과 같이 /src/App.tsx 에서 사용하려고 했으나, App tree의 root에서 사용하는 것을 권장한다는 에러가 떠서 /src/main.tsx에서 <App />을 감싸도록 적용함
- `Disabled`:  props.isChecked 값으로 제어
- `isChecked` 상태는 상위 컴포넌트에서 제어
- `onClick` : 버튼 사용 맥락에 따른 이벤트 핸들러로 상위 컴포넌트로부터 넘겨받음
> fe_v3/Check Button

- frontend_v3/src/components/atoms/modals/GuideModal.tsx
- frontend_v3/src/components/atoms/modals/LentBox.tsx
- frontend_v3/src/themes/muiCustomPaletteTheme.tsx
- `handleClose` 를 defaultProps 에서 지정하여 상위 컴포넌트에서 Box 호출 시 에러 발생하지 않도록 했습니다.
- `isLentAble` : 현재 접속한 사용자가 새 사물함을 대여가능한 상태인지 여부를 나타내는 값입니다. 리덕스에 저장 후 Selector로 가져와서 사용하게 될 것 같습니다.
- 글씨체 적용 및 요소들 간 간격 조정 필요합니다.
> fe_v3/Lent Box

- frontend_v3/src/components/templates/FooterTemplate.tsx
- frontend_v3/src/components/templates/LoginTemplate.tsx
- frontend_v3/src/styles/GlobalStyle.tsx
#205 #207 
- height 90vh 적용
- a 태그에 중복으로 작성된 css 코드 수정
- height 10vh 적용
- footer 내부에 2개의 section으로 구성되도록 수정
- 글씨체가 적용되지 않던 문제를 해결하였습니다.
- font-face를 추가하여 웹 폰트를 불러온 후 body에 글씨체를 적용하여 해결.
> fe_v3:LoginFooter

- frontend_v3/src/components/organisms/EditInput.tsx
edit input이 React.Fragment 태그로 감싸져 있었는데, 해당 컴포넌트를 다른 컴포넌트에서 사용할 때, React.Fragment가 사라지는 경우가 있어 div태그로 바꿨습니다
> fe_v3:React.Fragment to div

- frontend_v3/src/components/atoms/buttons/EditButton.tsx
- frontend_v3/src/components/atoms/inputs/TestTextField.tsx
- frontend_v3/src/network/axios/axios.custom.ts
- `axios.custom.ts`에 `axiosUpdateCabinetMemo` 및 `axiosUpdateCabinetTitle` 추가했습니다.
- API 분리됨에 따라 URL 업데이트 필요합니다.
- `TestTextFieldProps`에서 contentType으로 title인지 memo인지 구분했습니다.
- `p`태그로 보여지는 값과 `input`태그로 입력되는 값을 각각 `textValue`, `inputValue`로 구분했습니다.
- `EditButton.tsx`에서 axios 사용하여 patch 성공 시 사용자가 변경한 값으로 `textValue`가 변경됩니다.
> Fe v3/Edit Button Update

- frontend_v3/src/components/atoms/buttons/LoginButton.tsx
- frontend_v3/src/components/atoms/buttons/ReturnButton.tsx
- frontend_v3/src/components/organisms/LentInfo.tsx
- frontend_v3/src/components/templates/CabinetTemplate.tsx
- frontend_v3/src/components/templates/ContentTemplate.tsx
- frontend_v3/src/components/templates/LentTemplate.tsx
- frontend_v3/src/components/templates/LoginTemplate.tsx
- frontend_v3/src/index.css
- frontend_v3/src/network/axios/axios.custom.ts
- frontend_v3/src/pages/Lent.tsx
- frontend_v3/src/pages/Login.tsx
- frontend_v3/src/pages/Main.tsx
- frontend_v3/src/styles/GlobalStyle.tsx
- ContentTemplate 구현해서 적용했습니다
- Login 페이지가 가로 해상도 390px 이하부터는 깨지는데, 아직 원인을 못 찾았습니다 😭
- 위와 같은 이유로 우선 Draft로 올렸습니다.
- LoginSection에 display: flex 추가 및 내부 img 태그에서 display, width 속성 수정하여 해결했습니다.
- 가로 해상도를 줄이면 이미지는 함께 줄어드는데 a태그(버튼) 사이즈는 그대로인 문제가 남아있습니다.
> Content Template

- frontend_v3/src/components/atoms/buttons/FloorButton.tsx
- frontend_v3/src/components/atoms/buttons/LocationButton.tsx
- frontend_v3/src/components/templates/CabinetTemplate.tsx
- frontend_v3/src/main.tsx
- frontend_v3/src/network/axios/axios.custom.ts
- /src/components/templates/CabinetTemplate.tsx
- axiosCabinetInfo API 호출 및 cabinetAll Action 실행 
- src/components/organisms/CarouselInfo.tsx
- useAppSelector(cabinet.cabinet)
- currLocation, currFloor에 해당되는 것만 4중 배열에서 뽑아낸 후 prop으로 전달
- /src/components/atoms/buttons/FloorButton.tsx
- useAppSelector (cabinet.floor)
- /src/components/atoms/buttons/LocationButton.tsx
- 기존 BuildingButton -> LocationButton으로 rename
- useAppSelector (cabinet.location)
- /src/network/axios/axios.custom.ts 
- axiosCabinetLocationInfo 추가 (새 API에 사용 예정)
- frontend, backend 서버 실행 후 localhost/main
- CabinetTemplate에서 axiosCabinetInfo axios 요청이 처리되기 전에 state를 undefined 값으로 참조하지 않도록 optional chaining으로 구현하였습니다.
- CabinetTemplate에서 현재 location, floor를 state로 가지고, 값이 바뀔 때마다 CarouselInfo 내 4중 배열에서 조건에 맞는 object만 Array에 …
> fe_v3/cabinetAction

- frontend_v3/src/components/atoms/buttons/CabinetBoxButton.tsx
- frontend_v3/src/components/atoms/buttons/QustionButton.tsx
- frontend_v3/src/components/atoms/modals/GuideModal.tsx
- frontend_v3/src/components/atoms/modals/LentBox.tsx
- frontend_v3/src/components/organisms/Slide.tsx
- frontend_v3/src/components/organisms/SlideContainer.tsx
- frontend_v3/src/components/templates/CabinetTemplate.tsx
- 캐러셀 내부의 각 캐비닛 버튼을 누르면 띄워지는 모달창 수정하였습니다.
- 기존에 모달 내용물(box)을 버튼 내부에서 띄우는 구조에서, 모달 내부에 버튼을 포함하는 구조로 교체했습니다.
- 모달 내/외부 구분없이 클릭 시 모달이 꺼지는 현상과, 모달 외부의 다른 버튼을 눌렀을 때 모달이 중첩되어 열리는 현상 해결했습니다.
> fe_v3/carouselModal

- frontend_v3/src/components/atoms/buttons/SlideButton.tsx
- frontend_v3/src/components/organisms/Carousel.tsx
- frontend_v3/src/components/organisms/Slide.tsx
- frontend_v3/src/components/organisms/SlideContainer.tsx
- frontend_v3/src/components/templates/CabinetTemplate.tsx
- frontend_v3/src/mock/CabinetBoxButton.mock.ts
1. mobile, desktop 환경에서 carousel 내 영역이 %로 정해져 부자연스러운 높이가 지정되는 것을 방지하기 위해 각 영역에 max-height 적용
2. desktop 환경에서 캐비넷 박스가 많아지는 경우, overflow-y의 scroll 영역으로 인해 3열로 정렬되던 캐비넷이 2열로 정렬되는 문제 발생하여 scroll-display: none으로 변경
> fix: carousel size

- frontend_v3/src/components/templates/LentTemplate.tsx
#315 
- useAppSelector로 현재 유저가 대여한 cabinet_id 확인
- lentTemplate를 mount할 때 cabinet_id가 `-1`인 경우 대여하지 않은 상태이므로 main으로 navigate 하도록 추가
> lentPage Check cabinetId

- frontend_v3/src/components/atoms/buttons/EditButton.tsx
- frontend_v3/src/components/organisms/LentInfo.tsx
- frontend_v3/src/network/axios/axios.custom.ts
- 캐비닛 타이틀, 메모 업데이트하는 API의 인자 타입 및 EditButton 코드에서의 axios 호출 인자 타입 수정했습니다.
- 해당 API에 객체 데이터를 넘겨야 해서, dto와 변수명 일치시킨 후 문자열을 객체로 감싸 넘기도록 수정했습니다.
- API 코드 (axios.custom.ts)에서 cabinet_memo 및 cabinet_title 타입을 string에서 object로 수정했습니다.
> fe_v3/UpdateAPIs

- frontend_v3/package.json
- frontend_v3/src/network/react-cookie/cookie.ts
- frontend_v3/src/pages/Login.tsx
- 로그아웃 없이 바로 브라우저(탭이 아닌 브라우저 전체)를 종료했을 때 token은 삭제되지만 localStorage의 리덕스 정보는 삭제되지 않는 문제
- token이 없으므로 로그아웃 및 반납 불가, login 페이지에서 리덕스 정보를 바탕으로 main 페이지로 바로 리다이렉트 시키므로 로그인도 불가
- react-cookie 사용하여 accessToken 값이 들어있는지 확인하고, 없다면 기존에 있던 리덕스의 유저 정보도 우선 초기화되도록 변경
> fe_v3/reactCookie

- frontend_v3/src/components/atoms/buttons/MenuButton.tsx
- frontend_v3/src/components/atoms/modals/GuideModal.tsx
#334 
- 현재 box의 cabinet_id와 user state의 cabinet_id를 비교하여 동일한 번호의 사물함을 클릭하는 경우 lent page로 navigate 되도록 하였습니다.
#336
- 대여한 사물함이 있는 경우에만 menuButton의 내 사물함이 활성화 되도록 하였습니다.
> fe_v3/myLentCabinetNavigate

- frontend_v3/src/components/atoms/modals/GuideBox.tsx
#337 
- Typography가 `<p>` 태그로 구성되어있기때문에 내부에 `<p>` 태그를 사용하게되면 해당 문제가 발생함을 알 수 있었습니다.
- GuideBox에서 `Typography` 내부에 `<p>` 태그로 작성된 부분을 수정하였습니다.
- 각각의 Typography 안에 description을 담는 것으로 수정하였습니다.
> fe_v3/GuideBoxError

- frontend_v3/src/components/atoms/modals/LentBox.tsx
#335 
- `/v3/api/lent/{cabinet_id}` 호출의 응답 status에 따라 다른 alert 창이 표시되도록 수정했습니다.
- Swagger 명세에 나와있는대로 400, 403, 409, 418 응답에 대해 switch문으로 작성했습니다.
- 403(임시 밴 또는 고장 사물함)의 경우 애초에 클릭하면 다른 모달이 보여지고 있긴 한데, 일단 response 명세에 있어서 처리해두었습니다..
> fe_v3/LentAlertMessage

- frontend_v3/src/components/atoms/modals/LentBox.tsx
#338 
- 공유사물함 클릭 시 대여 안내 메세지를 아래와 같이 변경했습니다:
- 대여기간은 3인이 모두 공유하는 순간부터 +45일 입니다.
- 대여 후 72시간 이내 취소(반납) 시, 72시간의 대여 불가 패널티가 적용됩니다.
- 내 사물함' 페이지의 메모 내용은 공유 인원끼리 공유됩니다.
- 이용 중 귀중품 분실 및 메모 내용의 유출에 책임지지 않습니다.
- 문장이 길어져 중앙 정렬은 가독성이 떨어지는 것 같아 좌측 정렬로 변경했습니다.
> fe_v3/sharedCabinetMessage

- frontend_v3/src/components/organisms/Carousel.tsx
#366 
캐러셀을 구현하며 슬라이드가 움직이는 경우, [현재 슬라이드 인덱스 * 100 / (슬라이드 개수)]% 만큼 움직이게 되어 있습니다.
따라서 슬라이드가 5개인 2F에서는 20%씩 움직이고, 슬라이드가 4개인 4F, 5F에서는 25%씩 움직입니다.
층이 바뀌는 경우, 첫 렌더 시에 이 비율이 바뀌지 않은 채로 적용이 됩니다.
ex) 2F에서 40%만큼 움직여 있는 경우, 4F으로 바꾸어도 40%만큼 움직인 상태
- 4F는 슬라이드 개수가 4개라서 0%, 25%, 50%, 75%에서 정상 화면으로 보입니다.
캐비넷 정보가 바뀌는 경우에 현재 위치를 0%로 이동시켜 각 층의 맨 첫 슬라이드로 이동하도록 수정하여 해결했습니다.
> fix: carousel slide issue

- frontend_v3/src/components/organisms/Carousel.tsx
#333 
carousel 내 모든 property 변경에 대해 transition 속성이 적용되어 있었습니다.
carousel 내 슬라이드 이동을 위한 transform property에 대해서만 transition 속성이 적용되도록 변경하였습니다.
transition은 브라우저마다 호환가능한 버전이 모두 상이합니다.
transition을 사용하는 경우 모두 확인해봐야 할 듯 합니다.
> fix: carousel render on safari

- frontend_v3/src/components/atoms/buttons/EditButton.tsx
- frontend_v3/src/components/atoms/inputs/LentTextField.tsx
- frontend_v3/src/components/organisms/LentInfo.tsx
- frontend_v3/src/components/templates/LentTemplate.tsx
- frontend_v3/src/types/dto/cabinet.dto.ts
#380 
- LentTemplate에서 호출하던 my_lent_info API가 해당 컴포넌트에서 사용되지 않아 LentInfo로 이동시켰습니다.
- justify-content: space-between을 통해 정렬했습니다.
- 대여자 정보를 아래로 내렸습니다.
- LentTextField에 전달되는 title, memo 값이 API 응답을 받기 전 undefined로 전달되고 있습니다.
LentTextField로 전달되는 title, memo 값을 dependency array로 적용한 useEffect를 통해 최신화하도록 변경하였습니다.
- title, memo가 빈 값으로 전달되는 경우 현재 title, memo가 ""으로 설정됩니다.
DB에도 ""로 저장되며, 이를 다시 불러올 경우 false("", undefined, null)로 받아와 초기설정 됩니다.
이에 맞춰 빈 값이 전달되는 경우 화면에 표시되는 텍스트를 임시 텍스트로 변경하였습니다.
title : 방 제목을 입력해주세요
memo : 필요한 내용을 메모해주세요
방 제목, 메모가 빈 값 ("")으로 전달될 경우, DB에도 null이 아닌 ""으로 저장됩니다.
이 경우에 DB에 null로 저장할지 빈 값으로 저장할지 검토가 필요할 것 같습니다.
현재 title, memo값을 한 번 변경하면 다시 null로 돌릴 수 없는 것 같습니다.
> fix: edit cabinet title and memo

- frontend_v3/src/components/atoms/buttons/EditButton.tsx
- frontend_v3/src/components/atoms/inputs/LentTextField.tsx
- frontend_v3/src/components/atoms/modals/LentBox.tsx
- frontend_v3/src/components/organisms/LentInfo.tsx
- frontend_v3/src/components/organisms/Slide.tsx
- frontend_v3/src/components/templates/LentTemplate.tsx
- frontend_v3/src/types/dto/cabinet.dto.ts
- 사물함 대여 모달의 전체적인 디자인을 수정했습니다.
- **이용 시 유의사항**을 `ScrollBox` 내부에 넣어 스크롤되도록 수정했습니다.
- (피드백을 받아) 대여자 목록이 가로로 나열되도록 수정했습니다.
> fe_v3/LentBoxRedesign

- frontend_v3/src/components/atoms/inputs/LentTextField.tsx
- frontend_v3/src/components/organisms/LentInfo.tsx
- 내 사물함 페이지에서 빌린 캐비닛 번호 아래 **대여 만료 기한**이 보이도록 수정했습니다.
- 내 사물함 페이지 `LentTextField` 에 뉴모피즘 디자인을 적용하여 수정했습니다.
- 제목 / 메모 내용이 길어질 경우 스크롤하여 전문 확인할 수 있도록 `overflow: auto` 속성을 주었습니다.
- 공유사물함의 경우 함께 이용중인 카뎃 명단이 보이도록 수정했습니다.
> fe_v3/myCabinetaPageRedesign

- backend/src/utils/expired.checker.component.ts
expired_time이 null인 경우 날짜를 계산할 필요가 없기 때문에 예외처리 했습니다.
> expired_time이 null인 경우 예외처리

- frontend_v3/src/components/atoms/buttons/CabinetBoxButton.tsx
#430 에 대한 오류를 수정했습니다.
`CabinetBoxButton`의 `setCabinetColor` switch case문에서
`case CabinetStatus.AVAILABLE || CabinetStatus.SET_EXPIRE_AVAILABLE:`을
```
case CabinetStatus.AVAILABLE:
case CabinetStatus.SET_EXPIRE_AVAILABLE:
```
로 수정하여 문제를 해결했습니다.
> fe_v3/cabinetStatus #430

- frontend_v3/src/components/atoms/inputs/LentTextField.tsx
- frontend_v3/src/components/organisms/LentInfo.tsx
1. `LentInfo.tsx` 의 `userInfo` 함수
- 캐비닛 공유 중인 카뎃 목록뿐 아니라 "함께 사용중인 카뎃들" 문구 및 `hr` 태그까지 모두 **공유사물함인 경우** 에만 보여지도록 userInfo 함수에서 `lent_type` 까지 체크하도록 수정했습니다.
2. `LentTextField`
- 백엔드에서 **개인 사물함의 경우 비밀번호를 localStorage에 저장하는 방안**에 대한 의견이 나와서, `LentInfo.tsx` 에서 `lent_type` 을 `LentTextField` 에도 넘겨주도록 일단 수정했습니다.
- 이로 인해 **`LentInfo` 가 아니라 `LentTextField` 에서 조건을 검사**(개인 캐비닛이고 title 타입인 경우 null)하여 렌더링되도록 수정했습니다.
- 상기 내용대로, 개인사물함은 공유사물함보다 귀중품(노트북 등) 보관 빈도가 높아, 물건 도난 시 **서버 비밀번호 유출로 인한 cabi 팀 쪽 책임**이 발생할 수 있다는 우려가 있습니다. 따라서 **개인 사물함은 서버가 아닌 localStorage에 메모장 내용을 저장하자는 방안**에 대해 의견 부탁드립니다.
> fe_v3/PrivateTitleUserInfo

- frontend_v3/src/components/atoms/buttons/EditButton.tsx
- frontend_v3/src/components/atoms/inputs/LentTextField.tsx
- **`EditButton.tsx` : 취소 버튼 추가**
- 사용자가 수정을 취소했을 경우 기존의 `textValue` 에 따라 기본값인 "필요한 내용을 메모해주세요" 였다면 `inputValue` 가 비워지고, 다른 값이 들어있었다면 `inputValue` 에 다시 해당 값이 들어가도록 수정했습니다.
- **`LentTextField.tsx` : `textValue` 에 따른 `inputValue` 변경**
- 최초 렌더링 시 받아오는 값인 `currentContent` 가 존재하지 않는다면 기본값("필요한 내용을~")이므로, 빈 값으로 설정됩니다.
- `textValue` 가 변경될 때마다 dependency array에 의해 기본값으로 설정된다면 `inputValue` 가 빈 값으로, 다른 값이라면 해당 값으로 설정됩니다.
- `editButton` 은 **`textValue` 를 변경하고 `inputValue` 를 patch하는 역할**을 할 뿐 `currentContent` 는 최초 렌더링 이후 변경되지 않으므로, dependency array에서 제거했습니다.
> fe_v3/LentTextFieldFixed

- backend/src/cabinet/repository/cabinet.info.repository.ts
#440 이슈를 해결하였습니다.
기존 코드에선 한번 조회시에 몇백번의 쿼리를 DB에 날리게 되어 약 1초간 지연이 생겼는데 해당 문제를 해결하였습니다.
> 사물함 초기정보 가져올 때 로딩 오래걸리는 문제 해결

- backend/src/ban/ban.service.ts
- backend/src/ban/repository/ban.repository.interface.ts
- backend/src/ban/repository/ban.repository.ts
- backend/src/entities/ban.log.entity.ts
- backend/src/lent/lent.component.ts
- backend/src/lent/lent.module.ts
- backend/src/utils/expired.checker.component.ts
- backend/src/utils/utils.module.ts
패널티로 인한 ban은 연체일로 인한 ban과는 다르다는 판단하에 새로운 필드 `is_penalty`를 추가하여 패널티로 인한 ban log 날짜는 제외하고 누적 연체일 계산
expired checker component에 있었던 `getExpriedDays` 함수는 ban service로 이동하여 `calDateDiff`로 이름을 변경, 
now()와 expired_time의 차이만 계산할 수 있었던 함수를 begin, end date를 받아 계산하는 로직으로 변경하였습니다.
> 누적 연체일에 관한 기능 추가

- frontend_v3/src/components/atoms/buttons/ReturnButton.tsx
- frontend_v3/src/components/atoms/modals/ReturnBox.tsx
- frontend_v3/src/components/organisms/LentInfo.tsx
- frontend_v3/src/components/templates/LentTemplate.tsx
**반납 확인 모달 추가되었습니다. (#383)**
- `ReturnButton` 에서 반납 API를 호출하던 방식에서, `ReturnButton` 은 **반납 확인 모달**을 띄우고 해당 모달 내부의 `CheckButton` 이 반납 API를 호출하도록 수정했습니다.
- 공유사물함인 경우에만 **"공유사물함 반납 시~"** 경고문구를 보여달라는 요청에 따라, 기존에 `LentInfo` 에서 불러오던 `myLentInfo` API 를 상위의 `LentTemplate` 으로 끌어올렸습니다.
> fe_v3/ReturnButtonFixed

- frontend_v3/src/components/atoms/buttons/SectionButton.tsx
- frontend_v3/src/components/atoms/buttons/SectionNameButton.tsx
- frontend_v3/src/components/organisms/Carousel.tsx
#412 
- SectionName이 표기되는 부분을 추가하였습니다.
- faMapLocation 아이콘을 통해 Map section으로 이동됩니다.
- SectionButton의 prop으로 전달 받았던 isClicked는 삭제하고, 현재 slide의 위치를 확인할 수 있는 currentSlide를 추가하였습니다.
- SectionButton의 clickHandler을 통해 현재 click된 section의 버튼의 색상을 다르게 보이게 수정하였습니다.
> fe_v3/sectionName

- frontend_v3/src/components/atoms/buttons/MenuButton.tsx
- MenuButton의 내 사물함 MenuItem에 대해 lent page에서 아무런 동작도 하지 못하는 문제가 있었습니다.
- cabinet을 대여한 유저를 기준으로 main page에서 `내 사물함`으로 표기 및 클릭 시 lent page 이동
- cabinet을 대여한 유저를 기준으로 lent page에서 `전체 사물함`으로 표기 및 클릭 시 main page 이동
> fe_v3/MenuButtonNavigate

- frontend_v3/src/components/atoms/buttons/FloorButton.tsx
- frontend_v3/src/components/organisms/Carousel.tsx
- frontend_v3/src/themes/muiCustomTheme.tsx
- SectionName을 추가하면서 하단의 GuideModal이 밀려나는 현상 발생
- Carousel의 Row div height 비율을 height: calc(100% - 2rem) -> height: calc(100% - 3rem) 수정
- 기존 커밋된 부분에 해당 내용이 적용되어 있어 삭제하였습니다.
- SectionName과 Button 사이 공간이 넓어 SectionButton의 height를 2rem -> 1rem으로 수정
- FloorButton의 크기 수정 및 내부 글씨가 잘 보이도록 Carousel에 사용되는 색상과 동일하게 수정
> fe_v3/MainTemplateRatio

- frontend_v3/src/components/atoms/buttons/EditButton.tsx
- frontend_v3/src/components/atoms/inputs/LentTextField.tsx
- Lent page의 title, memo 항목에서 Default인 경우 memo는 input value가 " "로 초기화되지만 title은 초기화되지 않고 있습니다.
- title이 default인 경우에도 EditButton과 handleCancelButtonClick가 실행될때 " "로 초기화될 수 있도록 수정하였습니다.
> fe_v3/ModiDefaultTitle

- frontend_v3/src/components/templates/LentTemplate.tsx
- #489 
백엔드에서 응답을 받기 전에는 빈 화면으로 표시되도록 변경했습니다.
로딩 중이라는 정보를 표시하는 방법은 로딩이 빨리 이루어졌을 때 깜빡거리는 느낌이 있어서 빈 화면으로 선택했습니다.
> ENHANCEMENT: Render my lent info after get response

- backend/src/app.module.ts
- backend/src/config/configuration.ts
환경변수를 이용하여 상황에 맞게 V2, V3를 구동할 수 있도록 수정했습니다.
.env 파일에 `IS_V3=true`로 설정하면 V3로 구동되고 그렇지 않은 경우 V2로 구동됩니다.
이를 이용하면 서비스 오픈/클로즈할 때 쉽게 안내 페이지/메인 서비스 페이지 전환이 가능할 것 같습니다!!
> :zap: 환경변수를 이용하여 상황에 맞게 V2, V3를 구동할 수 있도록 수정 #500

- frontend_v3/src/network/axios/axios.instance.ts
- frontend_v3/src/network/react-cookie/cookie.ts
- #513 
- removeCookie 추가
- Axios intercepter를 instance에 적용해서 모든 요청에 대한 401 응답에 access_token 삭제 + 로그인 페이지로 이동하도록 처리
> FIX: 401 response 처리

- frontend_v3/index.html
- ga error를 디버깅하는 과정에서 CSP에 대한 지시어를 포함해야한다는 해결 방법을 찾게되었습니다.
- `<head>` 태그 내부에 `<meta>` 태그로 정의된 CSP 정책을 작성해보았습니다.
```
<meta
http-equiv="Content-Security-Policy"
content="script-src https://www.google-analytics.com https://ssl.google-analytics.com,
img-src https://www.google-analytics.com, 
connect-src https://www.google-analytics.com"
/>
```
> fe_v3/gaCSP

- backend/src/auth/42/ft.strategy.ts
- backend/src/auth/auth.service.ts
- backend/src/auth/repository/auth.repository.interface.ts
- backend/src/auth/repository/auth.repository.ts
- backend/src/blackhole/blackhole.component.ts
- backend/src/blackhole/blackhole.service.ts
- backend/src/user/repository/user.repository.interface.ts
- backend/src/user/repository/user.repository.ts
- backend/src/user/user.service.ts
서버가 재구동될 때 모든 유저에 대해 블랙홀 검증을 하는 것이 아닌 기존에 추가했던 `blackhole_date` 필드를 활용하여 
이 필드 값에 따라 동작하는 타이머를 달아 타이머가 fired될 때 블랙홀 검증을 하도록 개선했습니다.
> 블랙홀 모듈 최종 개선안 #517

- backend/src/lent/repository/lent.repository.ts
#532 에 대한 PR입니다.
isolation level을 serializable로 설정한 경우, db에 대한 모든 접근이 불가능할거라고 예상했으나, select문은 모두 처리가 되는 것을 확인했습니다. select가 실행이 되는 이유는 select는 s-lock(공유잠금)이기 때문에 서로 공유가 됩니다. 
ex) `A 트랜잭션의 select 실행 -> B 트랜잭션의 select 실행`
하지만 이 다음에 A 트랜잭션에서 update를 하려고 하면 x-lock(배타적잠금)으로 바꾸기를 시도하는데 B 트랜잭션에서도 잠금이 걸려있으므로 변환에 실패하게됩니다. B에서는 A의 공유잠금때문에 실패하게 되고 이를 conversion deadlock이라고 합니다.
기존에 isolation level을 설정할 때 기대한 방향과 같이 실행되도록 하나의 트랜잭션에서 select를 하면 다른 트랜잭션에서 select 또한 하지 못하게 막는 for update를 사용했습니다.
개인적으로 테스트는 해보았으나 할 수 있는 테스트에 제한이 있어 다 같이 테스트 해보면 좋을 것 같습니다.
그리고 일단 deadlock 문제가 생겼던 쿼리에만 추가를 해놨으니 다른 곳에도 추가를 할 지는 논의해봐야할 것 같습니다.
혹은 다른 방법으로 처리할 수 있을지도 논의해보면 좋을 것 같습니다!
> Be v3/hotfix

- backend/src/ban/ban.service.ts
- backend/src/utils/expired.checker.component.ts
만일 이메일 보내는 시간을 바꿀 경우 날짜 계산에 문제가 생길 수 있어 calDateDiff를 수정하였고,
expiredchecker에서 환경 변수에 저장되어 있는 날짜를 통해 이메일을 제대로 보낼 수 있도록 수정하였습니다.
> Be v3/email

- backend/src/ban/ban.service.ts
- backend/src/lent/lent.component.ts
- backend/src/lent/lent.controller.ts
- backend/src/lent/lent.service.ts
- backend/src/lent/repository/lent.repository.ts
메인에서 사용했던 lent/return 코드를 admin에서 참고하면서 작성하다보니 작은 문제가 발견돼서 수정 PR 올립니다!
> swagger와 트랜잭션 관련 작은 수정사항

- .gitattributes
- backend/package.json
#573 문제 해결을 위해 `.gitattributes` 파일 추가를 통해 원격 저장소로 push 될 때 개행 문자가 `LF`로 저장될 수 있도록 수정했습니다.
https://git-scm.com/docs/gitattributes#_checking-out_and_checking-in
https://stackoverflow.com/questions/170961/whats-the-strategy-for-handling-crlf-carriage-return-line-feed-with-git
> 원격 저장소로 push 될 때 LF로 저장되도록 .gitattributes 수정 #573

- backend/package.json
- backend/src/auth/auth.controller.ts
- backend/src/auth/jwt/jwt.strategy.ts
- backend/src/config/configuration.ts
- backend/src/main.ts
- backend/src/middleware/session-middleware.ts
- frontend_v3/src/components/atoms/buttons/LoginButton.tsx
- frontend_v3/src/network/axios/axios.instance.ts
- frontend_v3/src/pages/Login.tsx
- frontend_v3/src/pages/Main.tsx
기존에는 백엔드에서 클라이언트의 쿠키에서 토큰을 추출하여 인증을 수행했었었습니다.
그러나 백엔드와 프론트 도메인이 서로 달라 클라이언트의 쿠키를 추출할 수 없는 문제가 생겼습니다.
따라서 프론트에서 API 요청을 할 때 Request header에 Bearer 토큰을 넣어서 요청하는 방식으로 수정했습니다.
그럼에도 첫 로그인 시에 401 에러가 발생하여 원인을 파악해본 결과, 토큰을 쿠키에서 꺼내오기 전에 API 요청이 발생하여 생긴 에러인 것으로 파악됩니다.
따라서 axios instance의 interceptor 기능을 이용하여 요청을 보내기 전에 토큰을 쿠키에서 꺼내오는 동작을 보장시켜 오류를 해결했습니다.
아래는 해당 이슈 해결 참고 링크입니다!
https://velog.io/@ordidxzero/axios-instance-%EB%A7%8C%EB%93%A4%EC%96%B4%EC%84%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0
> 토큰 인증 방식 수정 #580

- frontend_v4/src/assets/images/LeftSectionButton.svg
- frontend_v4/src/containers/SectionPaginationContainer.tsx
> 사물함 구역을 화살표 또는 아래 사각형 클릭으로 이동할 수 있습니다.
추후 데이터를 받아오는 부분이나 구역 변경 시 state 혹은 redux dispatch 하는 부분을 components로 분리해야합니다.
> [FE] FEAT: 사물함 구역 상단 페이지네이션 바 구현 #598

- backend/src/app.module.ts
ec2 서버에서 프론트 build 결과를 정적 파일로 관리하기 위해 사용했던 `ServeStaticModule`을 제거하려고 했으나 
로컬 환경에서 필요한 경우가 있을 수 있을 것 같아(간헐적으로 로컬에서 nginx 서버로 보낸 요청이 pending이 걸리는 현상 발생), 
환경변수 `LOCAL=true`인 경우에만 initialize 되도록 수정했습니다.
> [BE] ETC: LOCAL=true일 때만 ServeStaticModule이 동작하도록 수정 #612

- frontend_v3/src/components/atoms/buttons/MenuButton.tsx
- frontend_v3/src/network/axios/axios.instance.ts
- frontend_v3/src/pages/Login.tsx
- package-lock.json
변경 전
```
removeCookie("access_token");
```
변경 후
```
if (import.meta.env.VITE_IS_LOCAL === "true") {
removeCookie("access_token");
} else {
removeCookie("access_token", { path: "/", domain: "cabi.42seoul.io" });
}
```
추가 변경 사항
- MenuButton.tsx
서버측에서 클라이언트의 쿠키를 대신 지워주는 것이 불가능해졌으므로 API 요청을 하는 대신 쿠키를 스스로 지우도록 로직 수정했습니다.
- Login.tsx
토큰을 가지고, redux에 유저 정보를 가진 채로 로그인 페이지 진입 시, main으로 리다이렉트 되도록 수정했습니다. 기존에 쿠키가 제대로 지워지지 않을 때 이 부분 때문에 login <-> main 간의 무한 리다이렉트가 되는 버그가 존재했었는데, 이제는 어느 환경에서든 쿠키가 정상적으로 지워집니다!
프론트 .env에서 `VITE_IS_LOCAL=true`일 때만 정상적으로 동작하오니 꼭 추가하시길 바랍니다.
> [FE] BUG: 로컬에서도 쿠키가 삭제되도록 수정 #655

- .github/workflows/cicd.yaml
- backend/test/app.e2e-spec.ts
- backend/test/cabinet.e2e-spec.ts
- backend/test/jest-e2e.json
GitHub Actions에서 제공하는 기능들을 이용해 CI 상에서 MariaDB를 도커 컨테이너로서 구동시키고 컨테이너에 DDL과 샘플 데이터를 주입시켰습니다.
그리고 CI에 e2e 테스트를 추가하였으며 기존 e2e 테스트에 아래와 같은 테스트 파일을 일부 수정하였습니다.
- `app.e2e-spec.ts`
- 루트 엔드포인트에 대한 테스트로 저희 앱애선 현재까진 해당 없으므로 404 Error를 리턴하는 것이 정상인 상황으로 적용하였습니다.
- `afterEach` 를 이용해 현재 실행중인 테스트 앱을 종료시킵니다.
- `cabinet.e2e-spec.ts`
- 로그인 및 세션을 어떻게 적용할 것인지에 대해 협의가 필요하다 판단해 skip 처리하였습니다.
- 추후에 해당 테스트를 동작시킬 때 `afterEach` 를 이용해 현재 실행중인 테스트 앱을 종료시키는 코드를 추가하여야 합니다.
작업한 기록은 https://github.com/innovationacademy-kr/42cabi/wiki/CI-에서-DB-Test를-위한-환경-셋업 에 간략하게 작성하였습니다.
> [BE] FEAT: CI 단계에서 e2e Test를 위한 환경 셋업

- backend/src/admin/admin.module.ts
- backend/src/admin/cabinet/cabinet.controller.ts
- backend/src/admin/cabinet/cabinet.module.ts
- backend/src/admin/lent/lent.controller.ts
- backend/src/admin/lent/lent.module.ts
- backend/src/admin/log/log.controller.ts
- backend/src/admin/log/log.module.ts
- backend/src/admin/return/return.controller.ts
- backend/src/admin/return/return.module.ts
- backend/src/admin/search/search.controller.ts
- backend/src/admin/search/search.module.ts
- backend/src/app.module.ts
- backend/src/betatest/betatest.controller.ts
- backend/src/cabinet/cabinet.info.controller.ts
- backend/src/lent/lent.controller.ts
- backend/src/main.ts
- backend/src/user/my.info.controller.ts
- backend/src/user/my.lent.info.controller.ts
- frontend_v3/src/components/atoms/buttons/MenuButton.tsx
- frontend_v3/src/components/atoms/buttons/ReturnButton.tsx
- frontend_v3/src/components/atoms/modals/ReturnBox.tsx
- frontend_v3/src/network/axios/axios.custom.ts
기존 dev에 있던 api에 달려있는 v3 태그들을 전부 정리하였습니다(백 + 프론트)
+ 하지만, axiosV3Return이라는 라이브러리가 있는 것으로 보아 추후 프론트쪽에서 개선이 필요해 보입니다.
admin에서 미리 사용하기로 결정해놓은 api들을 AdminModule에 서브 모듈로 옮겼습니다.
Swagger에서 나타나는 API 명세의 정보를 컨벤션에 맞게 변경하고,  admin API에 대해서는 차후에 디테일하게 설명을 채워 넣을 수 있도록 틀만 만들어 두었습니다.
> [COMMON] REFACTOR: api v3 태그 제거 및 admin api 병합 #638

- frontend_v4/src/components/TopNav.tsx
- frontend_v4/src/containers/LeftNavContainer.tsx
- frontend_v4/src/containers/TopNavContainer.tsx
- frontend_v4/src/pages/HomePage.tsx
- frontend_v4/src/pages/MainPage.tsx
- frontend_v4/src/recoil/atoms.ts
- frontend_v4/src/recoil/selectors.ts
>TopNav에 건물 정보를 recoil state에서 가져다가 쓰는 것으로 변경(모든 건물 이름 배열 반환하는 selector 추가)
기존 HomePage에서 불러오던 건물 정보를 TopNav에서 받고 세팅하도록 수정
Atoms의 건물 정보 기본값을 새롬관에서 undefined로 변경(TopNav에서 API 요청 받아온 뒤 첫 번째 건물로 세팅)
TopNavContainer에서 기능을 TopNav로 분리
건물 선택 드롭다운이 section 메뉴 밑에 있어서 선택이 안되는 현상 -> 임시로 z-index 100부여(@42inshin z-index 쓰면 안좋다고 들었는데 나이스한 해결 방법 있을까요?)
*기타 수정 사항 : Home 버튼 누르면 currentFloorNumberStatus 변경하는 부분을 useResetRecoilState 훅으로 변경
> [FE] FEAT: TopNav 관련 수정 사항

- backend/src/cabinet/repository/cabinet.info.repository.ts
- backend/src/dto/response/cabinet.info.response.dto.ts
#676 에 따라 `/api/cabinet_info/{cabinet_id}` 에서 주는 사물함 정보에 `location`과 `floor`값을 추가했습니다.
해당 요청에 대한 응답은 `CabinetInfoResponseDto`를 통해 보내집니다.
`CabinetInfoResponseDto`의 부모인 `CabinetDto`에 `location`과 `floor` 필드를 추가하는 것도 고려했으나
해당 정보를 사용하지 않는 곳도 많고, 불필요하게 수정해야 할 부분이 많습니다.
따라서 `CabinetInfoResponseDto`에 `location`과 `floor` 필드를 추가하여 수정했습니다.
> 단일 사물함 정보 API response 값 추가 #676

- frontend_v4/src/components/SectionPagination.tsx
- #706 
>section pagination 바에 undefined가 출력되지 않도록 currentSectionName도 로딩 완료 체크 조건에 추가하였습니다.
기존에 isLoad 값에 따른 빈 div 반환부분을 && 조건으로 합쳤습니다.
리턴 컴포넌트 전체를 감싸는 React.Fragment는 단축 문법으로 <></> 로 사용할 수 있습니다.
의미없는 div가 추가되는 줄 알았는데 별도의 DOM을 만들지 않고 감싸는 기능이라고 하네요.
[React.Fragment 공식 문서](https://ko.reactjs.org/docs/fragments.html#short-syntax)
> [FE] FIX: pagination 바 로딩완료 체크 조건 추가 #706

- frontend_v4/src/components/CabinetInfoArea.tsx
- frontend_v4/src/containers/CabinetInfoAreaContainer.tsx
사물함 상세보기에서 맨 아래의 텍스트가 연체를 나타낼 시 (OO일 지났습니다)의 색상 변경
> [FE] FIX: 연체된 사물함 밑에 메시지 색깔 바꾸기 #725

- frontend_v4/src/components/TopNavButton.tsx
- frontend_v4/src/containers/TopNavButtonsContainer.tsx
- frontend_v4/src/hooks/useDetailInfo.ts
사물함 보기 버튼 (탑 내비게이션 바 우측 아이콘)을 눌렀을 시 사물함 상세보기 페이지가 뜨고 자신이 대여중인 사물함이 나오는 기능을 구현하였습니다. 만약 대여한 사물함이 없는 유저의 경우 해당 아이콘이 보이지 않게 처리하였습니다. 
closes #719
> [FE] 내 사물함보기 버튼 기능 추가

- frontend_v4/src/components/CabinetInfoArea.tsx
- #683 
>취소 버튼 클릭 시 targetCabinetInfoState를 초기화시키도록 했습니다.
> [FE] FEAT: 우측 구역 취소 버튼 기능 추가 #683

- frontend_v4/package-lock.json
- frontend_v4/package.json
- frontend_v4/src/containers/LeftNavContainer.tsx
- frontend_v4/src/recoil/atoms.ts
메인에서 새로고침 시 recoil값이 초기화 되어 사물함 정보가 안나오는 부분을 recoil-persist 라이브러리를 통하여 개선하였습니다.
새로운 라이브러리가 설치되었으므로, npm install이 필요합니다.
추가적으로, 섹션 부분도 저장하고 싶었으나, 해당 값도 저장하게 되면 다른 층으로 갔을때 새로운 값으로 변하지 않는 버그가 있어서 floor가 바뀌는 경우와 새로고침 시 모두 섹션은 index 0 값을 넣어 처리하였습니다.
이 내용은 개선의 여지가 있습니다. 
Closes #739
> [FE] FEAT: 새로고침을 위한 recoil-persist 적용 #739

- frontend_v4/src/containers/MemoModalContainer.tsx
- frontend_v4/src/index.css
>수정하기 버튼이 `position: absolute`로 적용되어 있었는데 `top, left, right, bottom`이 동시에 프로퍼티로 들어가 있어서 사파리에서 반정도 잘려 보였습니다. right:40px로 줘서 해결하였습니다. 
>추가로 input태그에 기본 패딩이 적용되어 있어 input태그에 대한 글로벌 스타일로 `box-sizing:border-box;`로 설정해주었습니다. 
closes #771
> [FE] BUG: 사파리에서 메모 수정하기 버튼이 잘려보이는 이슈 해결 #771

- frontend_v4/src/components/Modal.tsx
- frontend_v4/src/containers/CabinetInfoAreaContainer.tsx
- frontend_v4/src/containers/ModalContainer.tsx
- frontend_v4/src/maps.ts
>기존에 캐비넷 상태에 따라 달라지던 modalProps를 json형태로 밖으로 maps.ts에 빼서 필요한 컴포넌트에서 import해오는 방식으로 바꾸었습니다. 또 대여, 반납 api호출을 담당하는 함수를 ModalContainer.tsx에서 빼내서 Modal.tsx에서 담당하게 하였고 모달 컨테이너에 전달하는 프롭스 구조를 간략화 하여 static한 정보만 담을 수 있게하여 재사용성을 높였습니다. 
closes #763
> [FE] REFACTOR: 대여 반납 api호출부 모듈화 #763

- frontend_v4/src/containers/MapInfoContainer.tsx
- #782 
그림자 가려지는 현상 때문에 z-index를 페이지네이션 바와 동일하게 10으로 조정했습니다.
> [FE] FIX: 우측 지도 구역 z-index 10으로 조정 #782

- frontend_v4/src/components/Modal.tsx
- frontend_v4/src/containers/LeftNavContainer.tsx
- frontend_v4/src/containers/MapGridContainer.tsx
- frontend_v4/src/recoil/atoms.ts
맵에서 다른 층의 섹션을 클릭했을 때, 해당 섹션으로 가기위해서 플래그가 필요했습니다.
이전의 비슷한 사유로 만든 `isMyCabinetIdChanged` recoil state와 같은 역할이 필요해서 
`isMyCabinetIdChanged` -> `isCurrentSectionRenderState` 로 이름을 바꿔서 처리했습니다.
Closes #765
> [FE] BUG: 맵에서 다른 층의 섹션을 선택했을 때의 버그 수정 #765

- frontend_v4/src/containers/MapInfoContainer.tsx
- frontend_v4/src/containers/SectionPaginationContainer.tsx
- #782 
모바일에서 동일한 문제가 생겨서 페이지네이션 바의 z-index를 1로 조정했습니다.
우측 구역은 다시 9로 복구했습니다.
> [FE] FIX: 페이지네이션 바 z-index 1로 조정, 우측 구역 9로 복구 #782

- frontend_v4/src/components/CabinetInfoArea.tsx
- frontend_v4/src/containers/ButtonContainer.tsx
- frontend_v4/src/containers/CabinetInfoAreaContainer.tsx
- frontend_v4/src/containers/MemoModalContainer.tsx
- #760
대여 중일 때 대여 버튼을 disabled 처리 했습니다.
gray-color가 추가됨에 따라 버튼도 grayLine을 추가하고 기존 grayLine을 lightGrayLine으로 변경했습니다.
disabled -> lightGrayLine, 클릭 가능 -> grayLine 으로 적용했습니다.
> [FE] FEAT: 이미 대여 중일 때 대여 버튼 클릭 방지, gray 테마 버튼 추가 #760

- frontend/src/assets/data/mapPositionData.ts
- frontend/src/components/MapInfo/MapFloorSelect/MapFloorSelect.tsx
- frontend/src/components/MapInfo/MapFloorSelectOption/MapFloorSelectOption.tsx
- frontend/src/components/MapInfo/MapGrid/MapGrid.tsx
- frontend/src/components/MapInfo/MapInfo.tsx
- frontend/src/components/MapInfo/MapItem/MapItem.tsx
https://github.com/innovationacademy-kr/42cabi/issues/805
- 한 파일에 있던 여러 컴포넌트들 분리
- 모바일 맞춤을 위한 CSS 조정
- 섹션위치 데이터 별도로 파일 분리
Closes #805
> [FE] FIX: mapInfo 폴더의 컴포넌트, 데이터 분리 및 CSS 조정 #805

- frontend/src/pages/Layout.tsx
- frontend/src/pages/MainPage.tsx
https://github.com/innovationacademy-kr/42cabi/issues/796
- Layout에 있을 때 모든 컴포넌트가 리렌더링 되는 현상이 있어서 기존의 위치에서 MainPage 로 위치 변경했습니다.
- 기존의 터치 시작 위치를 나타내는 "touchOffset" 변수를 useState 상태값으로 잡고 있어서 클릭만 했을때도 하위의 모든 컴포넌트에 리렌더링이 있었습니다. 해당 변수는 useState 대신 일반 변수로 바꿔서 렌더링 이슈를 해결했습니다.
- 변수들 각각이 지닌 값의 의미를 명확히하기 위해서 변수 이름을 변경하였습니다.
Closes #796
> [FE] FIX: 모바일 섹션 스와이프 기능 파일 위치 수정 #796

- backend/src/auth/42/ft.strategy.ts
- backend/src/auth/42/guard/ft.guard.ts
https://github.com/innovationacademy-kr/42cabi/issues/738
다른 지역의 카뎃이 캐비닛을 대여하는 상황이 발생하여, 서울 카뎃만 인증이 가능하게끔 email의 끝자리('kr')을 기준으로 인증하는 로직을 추가하였고, 인증이 안 되었을시에 (다른 나라의 카뎃인 경우에) 인증에러 문구를 추가하였습니다.
> [BE] FEAT: 서울 카뎃만 42 인증이 가능하게끔 기능 및 문구 추가 #738

- frontend/src/components/Modals/MemoModal/MemoModal.tsx
제목없는 공유 사물함의 메모 관리 모달에서 제목이 null일 때 제목 박스가 아예 안보이던 버그를 수정하였습니다. 
https://github.com/innovationacademy-kr/42cabi/issues/809
closes #809
> [FE] 제목 없는 공유 사물함 메모 모달에서 제목 박스가 안보이던 버그 수정 #809

- frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
- frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
- frontend/src/components/TopNav/TopNavButtonGroup/TopNavButtonGroup.tsx
- frontend/src/hooks/useMenu.ts
https://github.com/innovationacademy-kr/42cabi/issues/817
useMenu에서 클릭된 사물함 값을 reset해주면서 이전의 코드에서 잘 작동하던 부분에 이상증상이 있었습니다.
내 사물함 보기 클릭 시, reset이 되었다가 다시 set이 되는 현상이 있어서 깜빡이는 것 처럼 보이는 증상이 있었고,
사물함 클릭 후 다른 사물함 클릭 시에도 깜빡이는 증상이 있었습니다.
더불어, 클릭된 사물함을 다시 클릭했을 때 api를 계속 호출하고 있었는데, 
사용자 경험에 더 맞게 다시 클릭 시에는 상세보기가 닫히도록 처리했습니다.
[**해결 사항**]
- 내 사물함 버튼 클릭 시 reset, set이 동시에 적용되는 문제 처리
- 사물함 클릭 후 다른 사물함 클릭 시, 클릭 UI 적용 안되는 문제 처리
- 클릭된 사물함 다시 클릭 시 상세보기 꺼짐
Closes #817
> [FE] BUG: 내 사물함 보기 클릭 시 깜빡임 증상 처리 #817

- frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.tsx
- frontend/src/pages/HomePage.tsx
https://github.com/innovationacademy-kr/42cabi/issues/814
home의 useEffect에서 층, 섹션을 reset하는 부분을 삭제하여 기존의 값을 유지하는 방식으로 코드를 수정하였습니다.
home으로 이동하더라도 이전의 값을 지니고 있기 때문에 뒤로가기나 앞으로가기로 main으로 이동 시 이전의 위치로 돌아갑니다.
층, 섹션 정보를 가지고 있기 때문에 이전에 있던 층과 같은 층을 클릭 시 useEffect가 동작하지 않으므로 같을 때의 조건에만 api를 사용하는 방식으로 코드를 작성하였습니다.
또한, home에서 활성화된 버튼 조건식을 수정하였습니다.
Closes #814
> [FE] BUG: 뒤로가기, 앞으로가기 시, 캐비닛정보를 못받아오는 이슈 #814

- frontend/src/pages/HomePage.tsx
https://github.com/innovationacademy-kr/42cabi/issues/822
#823 번의 PR을 다루면서 문제점을 발견 했습니다.
useEffect 내에서 커스텀 훅 사용시 커스텀 훅 내에 있는 recoil reset함수가 동작을 안하는 버그가 있습니다.
우선, 되게 끔 useEffect에서 마운트 시, 언마운트 시 recoil 상태를 reset을 하도록 처리해두었습니다.
하지만 왜 안 되는지 더 확실한 분석이 필요하므로 의견들내주시면 감사하겠습니다.
Closes #822
> [FE] 라우터 이동 시 recoil 값 초기화 안되는 버그  #822

- frontend/src/components/Modals/MemoModal/MemoModal.tsx
아이폰에서는 readOnly 속성이 있는 인풋 태그에서는 select나 focus가 안먹는것 같습니다. writeMode에 진입과 동시에 readOnly가 false가 되는데 아이폰에서는 무슨이유에서인지 모르게 readOnly가 false가 되지 않는것 같았습니다. 그래서 focus를 지우고 select로 통합했더니 아이폰에서도 인풋 박스를 터치하면 키보드가 올라오게 됩니다. 
#853 
Closes #853
> [FE] 아이폰 메모 수정모드 진입 시 키보드 활성화가 안되던 이슈 해결 #853

- backend/src/admin/auth/auth.controller.ts
- backend/src/admin/auth/google/google.auth.filter.ts
- backend/src/admin/auth/jwt/guard/jwtsign.guard.ts
https://github.com/innovationacademy-kr/42cabi/issues/834
어드민 로그인 실패시(잘못된 로그인 또는 로그인 하였으나 role이 권한 승인 대기상태 : 0 인 경우,
api/admin/auth/login/failure로 리디렉션 하게끔 설정하였습니다.
더해서, 로거를 추가하고 기존의 로깅 문장을 조금 다듬었습니다.
++
어드민 로그인 실패에 대한 페이지도 만들어 주시면 감사하겠습니다!
'승인 되지 않은 사용자'인 것을 인지하게끔 해주시고, 
다시 로그인 할 수 있게끔 ('api/admin/auth/login')으로 연결되는 버튼이 있으면 좋을 것 같습니다!
> [BE] FEAT: admin 로그인 실패시 리디렉션 및 로거 추가 #834

- frontend/src/App.tsx
- frontend/src/assets/css/media.css
- frontend/src/components/Error/ErrorTemplate.tsx
- frontend/src/pages/Layout.tsx
- frontend/src/pages/LoginFailurePage.tsx
- frontend/src/pages/NotFoundPage.tsx
https://github.com/innovationacademy-kr/42cabi/issues/840
기존의 404 페이지의 스타일을 component화하여 재사용할 수 있도록 변경하였습니다.
라우트는 기존 login에 넣으려 했으나, layout의 useEffect 영향이 있기에 밖으로 뺐습니다.
media.css에 있던 NotFoundPage 미디어쿼리를 공통으로 사용하기 위해 컴포넌트 내부로 이동하였습니다.
Closes #840
> [FE] 외국 카뎃 로그인에 따른 /login/failure 페이지 추가 #840

- frontend/src/App.tsx
- frontend/src/components/Login/Login.tsx
- frontend/src/components/Login/LoginTemplate.tsx
- frontend/src/pages/LoginPage.tsx
- frontend/src/pages/admin/AdminLoginPage.tsx
- [] FIX : 기존 기능 수정 및 정상 동작을 위한 간단한 추가, 수정사항
https://github.com/innovationacademy-kr/42cabi/issues/873
google Oauth 로그인을 위해  관리자용 login페이지를 만들었습니다.
기존의 login페이지의 style부분만 빼서 login/loginTemplate 로 넣고, LoginPage, AdminLoginPage에서 {url, title, subtitle} 로 props 넘겨서 재사용성을 높였습니다.
아직 Layout은 분리작업을 안했기 때문에 확인하기 위해서 admin용 나머지 Router는 주석처리하고 Login만 따로 빼어뒀습니다. 
이후 Layout 분리작업과 각 Page 들의 style 들을 분리하는 작업이 끝난 이후로 Router 조정이 있을 계획입니다
> ps) LoginPage과 AdminLoginPage 를 구분 짓기 위해 추후 현재의 모습과 달라질 수 있습니다..(먼저 기능부터 작업 후 추후에 작업할 예정)
Closes #873
> [FE] 관리자 로그인 페이지 추가 #873

- frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
- frontend/src/components/Home/ServiceManual.tsx
- frontend/src/components/Modals/MemoModal/MemoModal.container.tsx
- #859 
공유사물함 정원이 가득차면 3/3 대신 제목 출력하도록 수정하였습니다.
해당 이슈 작업하면서 공유사물함 정원도 정책 관련한 부분이라 생각되어 환경변수로 처리했습니다.
노션에 frontend env 업데이트 된 부분 참고 부탁드립니다!
기존 ServiceManual에서 3으로 고정되어 있던 부분만 환경변수로 대체되었습니다.
CabinetListItem에서는 환경변수 값이 아니라 props에 max_user값을 사용합니다.(사물함마다 정원이 달라질 수 있을 가능성)
내 사물함 제목 수정시에도 바로 반영될 수 있도록 상태 업데이트하는 부분이 추가되었습니다.
> [FE] FEAT: 공유사물함 정원 찬 경우 리스트에 제목 출력

- backend/src/admin/cabinet/cabinet.controller.ts
- backend/src/admin/cabinet/cabinet.service.ts
https://github.com/innovationacademy-kr/42cabi/issues/879
기존 어드민에서 사용하던 getCabinetCountFloor에 대한 API가 없어서 재구현했습니다.
> [BE] FEAT : cabinet/count/floor 구현 #879

- frontend/src/components/LeftNav/LeftNav.tsx
- frontend/src/pages/Layout.tsx
- frontend/src/pages/admin/AdminLayout.tsx
https://github.com/innovationacademy-kr/42cabi/issues/892
isLoading 상태의 초기 값을 true로 두어서 처음 들어왔을때 무조건 Loading 애니메이션이 보이도록 변경하였습니다.
해당 상태는 TopNavContainer에서 getLocationsData api가 성공적으로 불러와지는 경우에 false가 되면서 모든 레이아웃이 정상적으로 보이게 됩니다.
Closes #892
> [FE] 루트로 접근 시 login으로 리다이렉션되면서 Nav 보이는 버그 #892

- frontend/src/index.css
https://github.com/innovationacademy-kr/42cabi/issues/905
아래의 코드를 사용할 시 하이라이트를 막아준다는 stackoverflow의 내용을 보고 적용중입니다. 적용 후 삼성핸드폰으로 확인을 거치도록 하겠습니다.
```
-webkit-tap-highlight-color: transparent;
```
> [FE] BUG: 삼성 인터넷 앱에서 버튼 클릭 시 블루 하이라이트 유지되는 버그 #905

- backend/src/admin/dto/cabinet.info.dto.ts
- backend/src/admin/dto/user.cabinet.info.dto.ts
- backend/src/admin/dto/user.cabinet.info.pagenation.dto.ts
- backend/src/admin/search/repository/search.repository.interface.ts
- backend/src/admin/search/repository/search.repository.ts
- backend/src/admin/search/search.controller.ts
- backend/src/admin/search/search.service.ts
`/api/admin/search/:intraId` 라는 API가 추가되었습니다.
해당 API를 요청하면 intraId를 포함하는 유저들을 찾아서 대여중인 사물함 정보와 사물함을 대여중인 유저들의 정보를 반환합니다.
아래는 응답 예시입니다.
```
{
"result": [
{
"userInfo": [
{
"user_id": 85330,
"intra_id": "sichoi"
},
{
"user_id": 1,
"intra_id": "test1"
}
],
"cabinetInfo": {
"cabinet_id": 81,
"cabinet_num": 1,
"lent_type": "SHARE",
"cabinet_title": null,
"max_user": 3,
"status": "AVAILABLE",
"section": "End of Cluster 1",
"status_note": null
}
},
{
"userInfo": [
{
"user_id": 3,
"intra_id": "test3"
}
],
"cabinetInfo": {
"cabinet_id": 82,
"cabinet_num": 2,
"lent_type": "SHARE",
"cabinet_title": null,
"max_user": 3,
"status": "AVAILABLE",
"section": "End of Cluster 1",
"status_note": null
}
},
null
],
"total_length": 3
}
```
param으로 `test`라는 값을 주었을 때, …
> [BE] 어드민 페이지 검색 시 검색된 유저의 대여 정보 받아오는 API 구현 #921

- backend/src/admin/search/repository/search.repository.ts
- frontend/src/api/axios/axios.custom.ts
- frontend/src/assets/images/logoBlack.svg
- frontend/src/assets/images/selectPurple.svg
- frontend/src/components/Search/NoSearch.tsx
- frontend/src/components/Search/SearchDefault.tsx
- frontend/src/components/Search/SearchItemByIntraId.tsx
- frontend/src/components/Search/SearchItemByNum.tsx
- frontend/src/components/TopNav/SearchBar/SearchBar.tsx
- frontend/src/components/TopNav/SearchBar/SearchBarList/SearchBarList.tsx
- frontend/src/components/TopNav/SearchBar/SearchListItem/SearchListItem.tsx
- frontend/src/pages/admin/SearchPage.tsx
https://github.com/innovationacademy-kr/42cabi/issues/868
[[BE] FIX: 검색 API 수정](https://github.com/innovationacademy-kr/42cabi/commit/9ad9ff95ecc4390ae41ccaa82502e78850800a93) 이 머지되어야 제대로 동작하므로, 깃 상태를 해당 PR과 같은 위치에서 시작하도록 설정하였습니다.
- 최초 검색페이지 들어갔을때 필요한 SearchDefault 컴포넌트 추가
- 검색 시 숫자와 문자를 분리하여 검색하며, 검색이 없는 경우 NoSearch 컴포넌트가 나오게 처리했습니다.
- 검색한 내용이 SearchDetail 에서도 bold처리되도록 변경했습니다.
- 숫자로 검색 시 검색바 리스트에서 층도 나오도록 수정했습니다.
- total_length를 받아 "더보기"가 나오는 조건을 추가했으며, 클릭 시 다음 api를 호출하여 출력하도록 처리했습니다.
- 검색어가 없는 경우 alert 처리
- 검색바 리스트에 총 검색 수 뜨도록 처리
> [FE] FEAT: search페이지 검색을 위한 기능 및 컴포넌트 추가 #868

- backend/test/admin/lent.e2e-spec.ts
- backend/test/main/lent.e2e-spec.ts
- backend/test/utils.ts
>아래 링크에 이슈번호를 적어주세요. 예) .../42cabi/issues/793
테스트 파일들이 모두 같은 DB를 공유해서 사용하게되면, 테스트를 병렬적으로 진행할 수가 없습니다.
물론, 트랜잭션으로 관리하여 데이터 정합성 문제는 해결할 수 있겠지만 시간이 많이 소요될 것 입니다.
따라서 테스트 파일들이 각자 테스트를 진행할 DB를 직접 만들어 그 안에서 테스트를 진행할 수 있도록 수정했습니다.
일단 수정 결과 문제 없이 동시에 테스트가 가능한 것으로 확인했습니다.
> [BE] 각각의 테스트 파일들이 병렬적으로 실행될 수 있도록 수정

- frontend/index.html
- frontend/src/components/TopNav/TopNav.tsx
- frontend/src/hooks/useOutsideClick.ts
https://github.com/innovationacademy-kr/42cabi/issues/931
TopNav에 있는 건물 선택 버튼에 다른 곳을 클릭할 시 해당 리스트가 닫힐 수 있도록 커스텀훅을 추가했습니다.
> [FE] FEAT: location 선택 버튼 useOutsideClick hook 적용 #931

- frontend/src/assets/css/media.css
- frontend/src/components/TopNav/SearchBar/SearchBar.tsx
- frontend/src/components/TopNav/TopNav.tsx
- frontend/src/components/TopNav/TopNavButtonGroup/TopNavButtonGroup.tsx
https://github.com/innovationacademy-kr/42cabi/issues/933
검색 페이지를 들어가면 위와 같은 모양으로 나옵니다.
취소를 누르면 이전 탑네비가 나옵니다.
다시 검색버튼을 눌렸을 때 검색을 할 수 있습니다.
> [FE] FEAT: 모바일을 위한 검색 레이아웃 수정 #933

- backend/package-lock.json
- backend/package.json
- backend/src/admin/lent/lent.controller.ts
- backend/src/admin/return/return.controller.ts
- backend/test/admin/lent.e2e-spec.ts
- backend/test/admin/return.e2e-spec.ts
- backend/test/main/lent.e2e-spec.ts
- backend/test/test_db.sql
>아래 링크에 이슈번호를 적어주세요. 예) .../42cabi/issues/7
main: lent
admin: lent, return
E2E 테스트 코드 작성을 완료했습니다.
작성 결과 소스코드 수정이 필요한 부분이 확인되어 따로 FIXME로 주석처리 해두었습니다.
또한 대여 반납 후 반납이 잘 되었는지 확인(`cabinet_status` 확인 + `lent` 삭제 확인 + `lent_log` 추가 확인 + `ban_log` 추가 확인)해야 하는데
직접 DB에 접근해서 할 지, 다른 모듈의 API를 이용해서 할 지, 애매한 것 같아 일단 `TODO`로 표시했습니다.
1. Admin Return
-  `/cabinet/:cabinetId`, `/user/:userId`, `/bundle/cabinet`에서 실패 시 400을 응답하고 있으나 400은 문법 오류와 관련된 에러 코드이므로 409로 수정하는 것이 좋을 것 같습니다.
- 또한 성공 시, 204가 응답되어야 하는데 200이 응답되고 있습니다.
2. Admin Lent
- `lentService`에서 `intraId` 사용이 필요가 없으므로 param으로 cabinetId, userId만 받아도 될 것 같습니다.
- user와 cabinet이 존재하는지 확인하는 로직이 없어 500이 발생합니다. 
- user와 cabinet이 존재하지 않는다면 지금은 400을 반환 하도록 정의했습니다. 하지만 400은 클라이언트의 요청 문법이 잘못되었을 때 사용하는 것이므로 409를 응답하도록 수정하는게 좋을 것 같습니다.
- Return type이 any가 아닌 …
> [BE] lent, return e2e test 코드 작성 #793

- backend/src/admin/search/repository/search.repository.interface.ts
- backend/src/admin/search/repository/search.repository.ts
- backend/src/admin/search/search.controller.ts
- backend/src/admin/search/search.service.ts
사물함 번호로 검색 API에서 선택적으로 층 정보를 받아, 해당 층에 있는 사물함 정보만 가져올 수도 있도록 수정했습니다.
**사용 예시**
`localhost:2424/api/admin/search/cabinet/visibleNum/42`
-> 2, 4, 5층의 42번 사물함 정보 반환
`localhost:2424/api/admin/search/cabinet/visibleNum/42/?floor=2`
-> 2층의 42번 사물함 정보 반환
https://github.com/innovationacademy-kr/42cabi/issues/952
> [BE] 사물함 번호로 검색 API에서 층 정보를 받도록 수정

- frontend/src/api/axios/axios.custom.ts
- frontend/src/assets/data/maps.ts
- frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
- frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.container.tsx
- frontend/src/components/Modals/ReturnModal/AdminReturnModal.tsx
- frontend/src/recoil/atoms.ts
>
#959 
Closes #959 
admin이 단일 선택으로 개인 사물함을 반납시킬 수 있는 기능을 구현하였습니다. api도 연동하여 실제 동작을 확인하였습니다. 
recoil상태를 추가하였습니다. numberOfAdminWorkState라는 상태입니다. 관리자가 반납, 상태변경 등의 관리자 일을 api호출을 통해 하고 완료할 때 해당 상태값이 1 증가합니다. leftMainNav컴포넌트에서 이 상태를 useEffect Dependency로 가지며, admin 작업으로 인한 mainPage 캐비닛 아이템들의 변경 상태를 새로고침 없이 바로 반영되도록 하기 위해 만든 recoil 상태입니다.
> [FE] admin이 단일 선택모드에서 개인 캐비닛 반납 클릭 시 반납 모달 렌더링 및 api연동  

- backend/src/admin/dto/broken.cabinet.info.dto.ts
- backend/src/admin/search/repository/search.repository.ts
응답 리스트에 location과 floor 정보를 추가했습니다.
> [BE] FIX: 고장난 사물함 리스트 API에 location, floor 정보 추가 #972

- frontend/src/api/axios/axios.custom.ts
- frontend/src/components/Common/PillButton.tsx
- frontend/src/components/Common/Selector.tsx
- frontend/src/components/Modals/Modal.tsx
- frontend/src/components/Modals/ReturnModal/AdminReturnModal.tsx
#969 
admin이 공유 사물함 선택 후 반납하기를 누르면 아래와 같은 전용 UI가 렌더링 됩니다. 선택한 공유 사물함을 사용중인 유저들을 선택하여 반납할 수 있으며, 유저를 모두 선택하여 반납할 경우 사물함이 전체 반납됩니다. 
Closes #969
> [FE] admin 공유 사물함 반납 기능 추가 

- frontend/src/api/axios/axios.custom.ts
- frontend/src/assets/data/maps.ts
- frontend/src/assets/images/dropdownChevron.svg
- frontend/src/assets/images/warningTriangleIcon.svg
- frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
- frontend/src/components/Common/Dropdown.tsx
- frontend/src/components/Common/WarningNotification.tsx
- frontend/src/components/Modals/StatusModal/StatusModal.container.tsx
- frontend/src/components/Modals/StatusModal/StatusModal.tsx
#976 
위와 같이 사물함의 타입과 상태를 조회할 수 있습니다. 
위와 같이 사물함 상태, 타입을 드롭다운 메뉴 형식으로 수정할 수 있습니다. 
빌린 사람이 있는 사물함의 경우 위와 같이 경고가 뜨고 저장 버튼이 비활성화 됩니다. RealViewNotification 컴포넌트의 코드를 활용하여 새로 만들었습니다. 
Closes #976
> [FE] admin 사물함 상태 관리 모달 추가

- backend/src/admin/cabinet/cabinet.service.ts
https://github.com/innovationacademy-kr/42cabi/issues/988
이전 코드는 대여자가 있으면 사물함 상태 변경이 불가능하게 되어있었지만,
[이전 상태] -> BROKEN인 경우에만 대여자가 있는 경우 상태 변경이 불가능하도록 수정했습니다.
> [BE] 사물함 상태 변경 메서드 수정 #988

- backend/src/admin/return/return.controller.ts
- backend/src/admin/return/return.service.ts
https://github.com/innovationacademy-kr/42cabi/issues/991
사물함 여러개를 반납하는 returnCabinetBundle 메소드를 body에 cabinetId를 배열로 받을 수 있도록 수정했습니다.
> [BE] fix: returnCabinetBundle 수정 #991

- backend/src/admin/dto/Overdue.user.cabinet.info.dto.ts
- backend/src/admin/search/repository/search.repository.ts
프론트분들의 요청에 따라 연체중인 유저 목록을 불러올 때 cabinet_id까지 보낼 수 있도록 수정했습니다.
> [BE] fix: OverDueUserCabinetInfoDto에 cabinetId 추가

- backend/docker-compose.yaml
- frontend/src/pages/admin/AdminInfoPage.tsx
https://github.com/innovationacademy-kr/42cabi/issues/996
기존 openCabinet() 훅에서 딸려오는 background와 제가 따로 만든  background가 중첩되는 현상이였습니다.
수정하였습니다.
> [FE] FIX: Admin Info 페이지에서 background 두 번 나오는 현상 해결 #996

- backend/src/admin/cabinet/cabinet.service.ts
- backend/src/admin/cabinet/repository/cabinet.repository.interface.ts
- backend/src/admin/cabinet/repository/cabinet.repository.ts
https://github.com/innovationacademy-kr/42cabi/issues/1005
updateCabinetMaxUser(cabinetId: number, maxUser: number)
메서드를 어드민 캐비닛 서비스에 추가하였습니다.
차후에 재사용이 가능하도록 maxUser를 그대로 받아서 변경할 수 있게끔 구현했습니다.
해당 메서드를 이용해서, admin cabinetService에서 사용되고 있는 updateLentType에 현재 대여타입 별로 maxUser를 설정하도록 변경하였고, bundle의 경우 기존 리포지토리 함수를 직접적으로 사용하던 것을 서비스의 updateLentType를 사용하도록 하여 다중 선택으로 대여 타입을 변경하여도 max_user가 변경될 수 있도록 수정하였습니다.
> [BE] BUG: 캐비닛 렌트 타입 변경시 max_user 변경 반영 #1005

- frontend/src/components/CabinetInfoArea/AdminCabinetInfoArea.tsx
- frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
- frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
- frontend/src/components/Modals/ReturnModal/AdminReturnModal.tsx
- frontend/src/components/UserInfoArea/UserInfoArea.container.tsx
- frontend/src/components/UserInfoArea/UserInfoArea.tsx
- frontend/src/recoil/atoms.ts
https://github.com/innovationacademy-kr/42cabi/issues/999
1. 검색 페이지 - 유저 상세 정보 컴포넌트
a. 반납
b. 밴 해제
2. 사물함 상세 정보 컴포넌트 - 반납 버튼
a. 대여 중이 아니거나 동아리 사물함인 경우 버튼 비활성화
> [FE] FEAT: 검색 페이지 - 상세정보란 관리자 모달 연결, 사물함 반납 버튼 비활성화 조건 추가 #999

- frontend/src/components/Common/Dropdown.tsx
- frontend/src/components/Modals/StatusModal/StatusModal.container.tsx
- frontend/src/components/Modals/StatusModal/StatusModal.tsx
- frontend/src/hooks/useMultiSelect.ts
https://github.com/innovationacademy-kr/42cabi/issues/1006
위 이슈에서 묘사된 버그 현상을 Promise.all을 사용하여 targetCabinetInfoList를 변경해주어 변경사항을 화면에 반영하는 방향으로 고쳤습니다. 
또한 상태관리 모달에서 보이는 드롭다운 메뉴에 이미지 넣기 기능을 추가하였습니다. 상태 관리 모달의 사물함 타입란에 이제 해당 사물함 타입의 아이콘이 보이게 됩니다. 
@42inshin 님과 함께 동료학습으로 작업하였습니다. 
Closes #1006
> [FE] 다중선택모드에서 일괄 상태변경 시 변경사항이 모달에 반영 안되는 버그 수정 #1006

- frontend/src/api/axios/axios.custom.ts
- frontend/src/components/CabinetInfoArea/AdminCabinetInfoArea.tsx
- frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
- frontend/src/components/LentLog/AdminCabinetLentLog.container.tsx
- frontend/src/components/LentLog/AdminCabinetLentLog.tsx
- frontend/src/components/LentLog/AdminUserLentLog.container.tsx
- frontend/src/components/LentLog/AdminUserLentLog.tsx
- frontend/src/components/LentLog/LentLog.container.tsx
- frontend/src/components/LentLog/LogTable/AdminCabinetLogTable.tsx
- frontend/src/components/UserInfoArea/UserInfoArea.container.tsx
- frontend/src/components/UserInfoArea/UserInfoArea.tsx
- frontend/src/hooks/useMenu.ts
https://github.com/innovationacademy-kr/42cabi/issues/1003
- yooh 님이 메인 서비스에서 만들어주셨던 개인 대여 로그 컴포넌트를 재활용했습니다.
- 단순히 포맷팅 변경임에도 컴포넌트를 복사하여 구현하여 겹치는 코드가 굉장히 많습니다.
- 선 기능 구현 정신(== 최적화 해야할 것 투성이)
> [FE] FEAT: 사물함/유저 대여 기록 조회 기능 구현 #1003

- frontend/src/components/Modals/StatusModal/StatusModal.container.tsx
… #1013
https://github.com/innovationacademy-kr/42cabi/issues/1013
이제 다중선택 모드에서도 사물함들을 상태 변경 하고자 할 때 선택된 사물함이 모두 비어있을 경우에만 수정후 저장 버튼이 활성화 됩니다. 만약 선택된 사물함 중 하나라도 사용중이라면 저장 버튼이 비활성화 되고 경고 표시 호버 시 다음과 같이 경고 툴팁이 뜹니다.
> [FE] 다중선택 모드에서 사물함 일괄반납 시 저장 버튼 비활성화 여부 체크 로직 추가 #1013

- backend/package-lock.json
- frontend/src/components/Modals/LentModal/LentModal.tsx
- frontend/src/components/Modals/ReturnModal/ReturnModal.tsx
https://github.com/innovationacademy-kr/42cabi/issues/1024
현재 인원이 1명 이하일 때에는 대여날짜 문구 표시 되지 않도록 수정
대여가 시작되지 않은 공유 사물함의 경우 반납할 때 9999/12/31 이라는 날짜가 나오던 부분 나오지 않도록 수정
> [FE] BUG: 공유 사물함 대여 시작 되기 전에는 날짜가 나오지 않도록 수정 #1024

- frontend/src/assets/css/homePage.css
- frontend/src/assets/data/maps.ts
- frontend/src/assets/images/longTermIcon.svg
- frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
- frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
- frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
- frontend/src/components/Home/ServiceManual.tsx
- frontend/src/components/UserInfoArea/UserInfoArea.container.tsx
- frontend/src/types/enum/cabinet.type.enum.ts
https://github.com/innovationacademy-kr/42cabi/issues/1026
1. 메인 서비스 사물함 상세 구역 오타 수정: 사물함/유저 -> 사물함
2. 장기 대여 사물함 롤백
> [FE] FIX: 장기 대여 사물함 롤백, 오타 수정 #1026

- frontend/src/App.tsx
- frontend/src/assets/data/mapPositionData.ts
- frontend/src/components/CabinetList/CabinetList.container.tsx
- frontend/src/components/CabinetList/EmptySection/EmptySection.tsx
- frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.tsx
- frontend/src/pages/admin/AdminLogPage.tsx
> https://github.com/innovationacademy-kr/42cabi/issues/1048
- 3층 맵에서 DB에 올라가져있지 않은 사물함 섹션들 회색버튼으로 나오도록 처리
- 누른 경우, "사물함 오픈 준비 중!" 이라는 문구 나오도록 처리
- admin log 페이지 삭제 및 admin에서 log 페이지로 가는 버튼 안나오도록 처리
> [FE] FIX: 프론트엔드 dev to main을 위한 작업 #1048

- frontend/src/assets/data/mapPositionData.ts
> https://github.com/innovationacademy-kr/42cabi/issues/1054
3층 map 을 활성화 색으로 변경하기 위해서 mapPositionData.ts의 type을 closed -> cabinet으로 변경하였습니다.
Closes #1054
> [FE] FIX: 3층 map 비활성화 -> 활성화로 변경 #1054

- .github/workflows/backend-cicd.yaml
- .github/workflows/frontend-cicd.yaml
이슈에 작성한대로 backend와 frontend workflow를 분리시켰습니다.
어느 디렉토리에서 수정사항이 일어났는지에 대한 고려 없이, backend-CI와 frontend-CI가 하나의 워크플로우 안에서 동작했습니다.
때문에 frontend 디렉토리에서만 수정된 내용이더라도 backend-CI까지 같이 돌았습니다.
이 문제는 dev나 main으로 병합할 때 더 크게 와 닿게 되는 문제였습니다. frontend에서 모달 하나 추가하여 배포하려고 하는데, CD는 CI 작업이 모두 완료되어야 실행되기 때문에 수정하지도 않은 backend-CI를 모두 기다려야 합니다.
뿐만 아니라 CD에서도 수정하지도 않은 backend 코드를 build하고 배포하는 과정도 이루어집니다. 게다가 s3에 frontend 코드를 업로드하는 상황임에도 ec2에 접속 후 aws cli를 통해 배포하기 때문에 frontend 배포 과정이 ec2에 종속되는 문제도 있습니다.
backend와 frontend가 별도의 workflow로 동작하기 때문에, frontend 디렉토리에서 변경된 내용은 frontend workflow만 동작합니다.
따라서 이제 dev나 main으로 병합하여 CD를 실행하려고 할 때, 변경하지 않은 backend에 대한 CI를 기다릴 필요가 없습니다.
또한 CD에서도 backend workflow에서는 더이상 frontend 코드를 s3에 업로드하지 않습니다. frontend 코드를 업로드하는 일은 frontend …
> [COMMON] cicd workflow 분리

- frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
https://github.com/innovationacademy-kr/42cabi/issues/1073
Lent DB를 조회 해봤을 때 어떤 공유사물함은 expire_time이 NULL이고, 어떤 사물함은 9999-12-31로 저장 되어 있었습니다.
따라서 expire_time이 NULL일 때와 사물함 반납 기한이 9999년일 때 표시 되지 않도록 수정하였습니다.
> [FE] BUG: 대여 시작 안 한 공유 사물함 기한 9999로 나오는 버그 수정 #1073

- backend/src/dto/lent.cabinet.data.dto.ts
- backend/src/lent/lent.component.ts
- backend/src/lent/lent.controller.ts
- backend/src/lent/lent.service.ts
- backend/src/lent/repository/lent.repository.ts
- frontend/index.html
- frontend/src/api/axios/axios.custom.ts
- frontend/src/assets/data/maps.ts
- frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
- frontend/src/components/Common/Button.tsx
- frontend/src/components/Modals/PasswordCheckModal/PasswordCheckModal.container.tsx
- frontend/src/components/Modals/PasswordCheckModal/PasswordCheckModal.tsx
- frontend/src/components/Modals/PasswordCheckModal/PasswordContainer.tsx
- frontend/src/components/Modals/ReturnModal/ReturnModal.tsx
https://github.com/innovationacademy-kr/42cabi/issues/1059
어디까지 내다 보신 겁니까 @SeyoungCho 님.... `renderAdditionalComponent` 이거 보고 식겁했습니다
기존 모달에서 수정한 것은 거의 없고 password props 추가하느라 새로운 파일로 만들었습니다.
인신님이 말씀하신대로 input태그를 숨겨놓고 div에 비밀번호를 보여주는 방식으로 제작했습니다.
input은 width:0, height:0, color:white로 안 보이게 숨겨놨습니다.
로컬 서버에서 `return-memo` api 호출 잘 되는 것 까지 확인했습니다.
dev로 올리고 모바일 환경 테스트 해봐야할 것 같습니다.
> [FE] FEAT: 3층 사물함 반납 시 비밀번호 입력 모달 띄우기 #1059

- backend/src/admin/search/repository/search.repository.ts
- frontend/src/components/Search/SearchItemByIntraId.tsx
https://github.com/innovationacademy-kr/42cabi/issues/1085
Close #1085 
기존에 벤 된 유저를 검색시 상세보기 영역에서만 ! + 빨간색 네모로 표시 되었으나, 검색 시에도 표시되도록 수정했습니다.
추가로, 검색 API에서 사용정지 정보(banned_date, unbanned_date)가 잘못 받아지는 버그가 있어서 sichoi 님과 함께 수정했습니다.
공유 사물함으로 (대여 후 바로 반납 시)벤 된 유저의 경우, 개인 사물함을 빌릴 수 있어서 home의 사용정지 유저 표에서는 벤이라고 뜨나 실제로 검색해서 보면 개인 사물함을 사용하고 있는 유저들이 있습니다.
공유 사물함을 통해 벤 된 유저는 사용정지 유저에서 분리 또는 제외 하거나, 표시하는 방법을 다르게 해야 할 필요성이 보입니다.
> [COMMON] 어드민에서 검색 시 벤된 유저 UI 수정

- backend/build.gradle
- backend/src/main/java/org/ftclub/cabinet/CabinetApplication.java
- backend/src/main/java/org/ftclub/cabinet/auth/AuthAspect.java
- backend/src/main/java/org/ftclub/cabinet/auth/TokenProvider.java
- backend/src/main/java/org/ftclub/cabinet/auth/TokenValidator.java
- backend/src/main/java/org/ftclub/cabinet/auth/User.java
- backend/src/main/java/org/ftclub/cabinet/auth/UserAspect.java
- backend/src/main/java/org/ftclub/cabinet/dto/UserSessionDto.java
- backend/src/main/java/org/ftclub/cabinet/exception/ExceptionStatus.java
- backend/src/test/java/org/ftclub/cabinet/auth/controller/AdminAuthControllerTest.java
- backend/src/test/java/org/ftclub/cabinet/auth/controller/AuthControllerTest.java
- backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenProviderTest.java
- backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenValidatorTest.java
- backend/src/test/java/org/ftclub/cabinet/cabinet/controller/AdminCabinetControllerTest.java
- backend/src/test/java/org/ftclub/cabinet/cabinet/controller/CabinetControllerTest.java
- backend/src/test/java/org/ftclub/testutils/TestControllerUtils.java
변경 사항
1. AuthGuard에 따라 AuthAspect에서 컨트롤러 클래스에 어노테이션을 붙이는 경우 잘 작동하지 않던 점을 수정했습니다.
-> 메서드, 컨트롤러 클래스 자체에서의 우선순위를 구조적으로 둘 수 없어서, 만약 메서드 별로 AuthLevel을 다르게 설정하시려면 모든 메서드에 별개로 달아주셔야 하고, 아니면 컨트롤러 전체에 적용하는 하나의 어노테이션만 사용할 수 있습니다.
2. @AuthGuard를 사용하고 있는 어플리케이션 컨텍스트를 그대로 가져와 테스트하는 방식이므로, AuthGuard를 통과할 수 있는 토큰이 있어야 컨트롤러의 작동 여부를 제대로 확인할 수 있었습니다. 따라서, TestControllerUtils 클래스를 생성하였는데, 가지고 있는 메서드는
어드민 토큰, 유저 토큰, 쿠키 만들기, MockServletRequestBuilder를 이용한 메서드 별 저희 서비스의 인증 방식(헤더에 토큰을 담아서 요청 + 쿠키에 토큰이 있는지 확인)에 맞추어 요청을 보낼 수 있는 mockRequest(사실상 빌더) 메서드를 만들어 놨습니다.
사용법은 다음과 같습니다.
컨트롤러 테스트 클래스에 JwtProperties를 @Autowired로 주입합니다 - Utils 클래스에서 주입을 하는 방법을 모르겠어서 이렇게 했습니다.
사용하고자 하는 token, cookie를 선언하고, @BeforeEach에서 …
> [BE] SPRING Test에서 @AuthGuard를 사용하는 경우 토큰을 Mocking하는 TestUtils 구현

- backend/src/main/java/org/ftclub/cabinet/auth/TokenProvider.java
블랙홀 날짜가 `JSONObject.NULL`인 경우에 claims에 `JSONObject.NULL`가 아닌 null를 담도록 수정했습니다.
P.S
```
{
"role": "USER",
"name": "sichoi",
"email": "sichoi@student.42seoul.kr",
"exp": 1686491036
}
```
이렇게 하니까 생성된 토큰에는 아예 `blackholedAt` 필드가 포함되지 않네요....
`io.jsonwebtoken.Jwts` 라이브러리에서 null인 키값은 토큰에 포함되지 않도록 하는게 아닐까합니다..!
추후에 `UserSessionDto`에 토큰에 저장된 블랙홀 정보를 얻으려고 시도하는 경우에 버그가 발생할 수 있을 것 같아 메모 남겨둡니다.
https://github.com/innovationacademy-kr/42cabi/issues/1103
> [BE] BUG: 인트라 로그인 시 토큰 생성 오류 수정

- frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
- frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
- frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
> https://github.com/innovationacademy-kr/42cabi/issues/1106
타 사물함 선택 시 이용 중인 사용자와 대여 잔여일을 확인할 수 있도록 하였습니다. 기존에는 SET_EXPIRE_AVAILABLE 상태에서 대여 잔여일이 표시가 안 되었는데, 확인할 수 있도록 수정했습니다.
Closes #1106
> [FE] FEAT: 타 사물함 대여 잔여일 표시#1106

- backend/src/admin/auth/auth.controller.ts
- frontend/src/assets/data/maps.ts
- frontend/src/components/Login/AdminLoginTemplate.tsx
기존에는 Admin 아이디 혹은 비밀번호가 잘못 입력됐을 시 401 상태 코드를 받아 alert를 띄운 후 login 페이지로 강제 리다이렉션하는 방식으로 처리해 주었다면, 이번 수정에서 Sanan님과 회의를 거친 결과 로그인 실패 시 401(Unauthorized) -> 400(Bad request) 상태 코드를 받게 한 후 로그인 실패 모달을 띄우도록 수정했습니다.
이 외 Safari에서의 Cross browsing을 원활하게 지원하도록 코드를 수정해 주었습니다.
Closes #1109
> [FE] FEAT/FIX: Admin 로그인 실패 시 모달 추가 및 사파리 admin 로그인 폼 수정 #1109

- frontend/src/components/Common/Dropdown.tsx
- frontend/src/components/Common/Selector.tsx
- frontend/src/components/Common/WarningNotification.tsx
Common 컴포넌트 중 Dropdown, Selector, WarningNotification 컴포넌트들의 서식을 컨벤션에 맞게 수정하였습니다.
Dropdown: DropdownItemContainerStyled 내의 div Selector 가 비어있어 제거하였습니다.
Selector: PillButton 의 import 경로를 현재폴더 기준에서 '@'를 사용하는 절대경로로 변경하였습니다.
WarningNotification: export 의 위치를 코드 최하단으로 내리고, styled css 사이 줄바꿈을 넣고 들여쓰기를 알맞게 적용했습니다.
> [FE] REFACTOR: Common 컴포넌트들의 서식과 import 경로 수정 #1137

- frontend/src/api/axios/axios.custom.ts
- frontend/src/components/TopNav/SearchBar/SearchBar.tsx
- frontend/src/components/TopNav/SearchBar/SearchListItem/SearchListItem.tsx
- frontend/src/pages/admin/SearchPage.tsx
> https://github.com/innovationacademy-kr/42cabi/issues/1155
이제 사물함 번호 검색 시 리스트에서 하나를 클릭하면 해당하는 사물함만 검색이 됩니다!
> [FE] FIX: 어드민 사물함 검색 시 층 선택이 되도록 수정 #1155

- frontend/src/pages/MainPage.tsx
- frontend/src/pages/admin/AdminMainPage.tsx
- main, adminMain 페이지의 import 순서를 컨벤션에 맞게 처리해 주었습니다.
- currentSectionidx 변수명을 -> currentSectionIndex로 바꾸어 좀 더 명확하게 수정했습니다.
- AdminMainPage의 다중 선택 버튼을 감싸고 있던 div를 styled-component로 수정해주었습니다.
> [FE] REFACTOR: main, adminMain 페이지 리팩토링#1137

- backend/src/main/java/org/ftclub/cabinet/cabinet/domain/Cabinet.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/repository/CabinetRepository.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetExceptionHandlerService.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetService.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
- backend/src/test/java/org/ftclub/cabinet/cabinet/service/CabinetServiceTest.java
…아닌 도메인에서 사용하게끔 변경
https://github.com/innovationacademy-kr/42cabi/issues/1178
참조 글 : https://cabi.oopy.io/6f64bbb2-5d1d-4015-8997-29d0aca17400
앞으로의 변경사항을 고려하고, 회의를 통해서 비관적 락으로 설정하기로 결정했습니다.
비관적 락으로 변경할 수 있게끔 version 컬럼을 삭제하고, @Lock을 이용해 X Lock을 획득해서 엔티티를 가져오는 ForUpdate 메서드를 생성했습니다.
추가적으로, lentService에서 불필요하게 사용하는 cabinetService의 specifyCabinetStatusByUserCount를 도메인 메서드로 사용하게끔 변경하였습니다.
변경사항에 맞추어 테스트를 변경했습니다.
> [BE] FIX: 대여, 반납 비관적 락으로 변경

- frontend/src/components/CabinetInfoArea/AdminCabinetInfoArea.tsx
- frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
- frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
- frontend/src/components/SectionPagination/SectionPagination.container.tsx
- frontend/src/components/SectionPagination/SectionPagination.tsx
- SectionPagination 및 CabinetInfoArea의 import 순서를 수정했습니다.
- 변수명을 좀 더 명확하게 수정했습니다.
- CabinetInfoArea, AdminCabinetInfoArea 와 CabinetInfoAreaContainer의 기능 분리 작업을 진행했습니다. 기존 아키텍쳐 컨벤션에 맞게 혼재되어 있던 로직과 스타일드 컴포넌트를 분리해 주었습니다.
- 이전 yooh님이 올려 주신 코드를 참고하여 모달이 오픈되는 상태를 좀 더 분명하게 명시해 주었습니다.
-논의해보고 싶은 점: 현재 Container 코드가 너무 길어 AdminCabinetInfoAreaContainer를 따로 빼는 것이 좋을지. interface 분리에 대한 컨벤션 논의
-모달 오픈 함수를 좀 더 명학하게 사용하기 위해 open과close로 분리했습니다.
- 모달 type 추가
> [FE] REFACTOR: SectionPagination 및 CabinetInfoArea 리팩토링

- frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.container.tsx
- frontend/src/components/MapInfo/MapInfo.container.tsx
- frontend/src/recoil/atoms.ts
https://github.com/innovationacademy-kr/42cabi/issues/1133
- 위치한 층이 변화하더라도 2층 또는 사용자가 이전에 봤던 층의 지도가 뜬다는 기존의 사항을 변경했습니다.
- currentMapFloorState라는 recoil 전역 상태관리를 사용하여 층이 변화할 때 맵도 변화하도록 수정하였습니다.
- 어떠한 층에 위치한 상태에서 새로고침을 하면 currentFloor가 undefined되어서 이에 대한 예외처리를 useEffect로 처리하였습니다.
> [FE] fix: 현재 위치한 층과 동일한 맵 띄우기 #1133

- frontend/src/pages/admin/AdminHomePage.tsx
- AdminHomeStyled 에서 min-width 프로퍼티를 대부분의 모바일 환경에서 짤리지 않게 보이게 300px 로 줄였습니다. 280px 이하에서는 표의 데이터가 잘 보이지 않는 문제가 있어 더 줄이지는 않았습니다.
- AdminInfoPage 가 AdminHomePage 로 이름이 바뀌어서 이에 맞춰 변수명을 수정했습니다.
https://github.com/innovationacademy-kr/42cabi/issues/1206
> [FE] BUG: AdminHomePage 에서 표가 모바일 환경에서 잘 보이게 조정과 변수명을 페이지명에 맞춰 변경 #1206

- frontend/src/assets/data/mapPositionData.ts
- frontend/src/components/MapInfo/MapItem/MapItem.tsx
https://github.com/innovationacademy-kr/42cabi/issues/1204
사진과 같이 지도의 배경에 층의 정보도 나타나게 수정하였습니다.
> [FE] feat:mapBackGround_floorInfo 추가

- backend/src/main/java/org/ftclub/cabinet/lent/repository/LentRepository.java
- backend/src/main/java/org/ftclub/cabinet/statistics/service/StatisticsFacadeServiceImpl.java
statisticsFacadeServiceImpl에서 사용하는 lentRepository의 countLentByLentTimeBetween과 countLentByReturnTimeBetween의 query문에서 대소비교가 잘못되어 있어서 수정하였습니다.
추가적으로, countLentByReturnTimeBetween은 일정 기간 동안의 반납 개수를 반환하는 메소드라서 이름을countReturnByReturnTimeBetween라고 하는게 조금 더 적절할 것 같아서 수정하였습니다.
> [BE] FIX : 대소비교 수정 & 메소드 이름 수정 in lentRepository

- frontend/src/components/LentLog/AdminLentLog.tsx
https://github.com/innovationacademy-kr/42cabi/issues/1227
대여기록 토글(사물함, 유저) 기능은 검색에서만 쓸 수 있으며, 타이틀을 클릭 시 바뀌도록 만들었습니다.
메인 페이지에서는 사물함 로그만 뜨도록 기능 제한을 뒀습니다.
> [FE] FIX: 대여기록 제목 클릭시 토글 검색 기능은 검색페이지에서만 가능하도록 수정

- frontend/src/api/axios/axios.custom.ts
- frontend/src/components/TopNav/SearchBar/SearchBar.tsx
- frontend/src/components/TopNav/SearchBar/SearchBarList/SearchBarList.tsx
- frontend/src/types/dto/cabinet.dto.ts
https://github.com/innovationacademy-kr/42cabi/issues/1238
- `cabinets-simple API`가 새로 만들어진 것에 따라 기존의 `cabinets?visibleNum=` 으로 사용하던 API를 수정했습니다.
- 응답으로 오는 data 객체의 프로퍼티가 변경되어 새로운 DTO인 CabinetSimple을 추가했습니다.
- 기존의 사용하던 API 중 이제는 사용하지 않는 API들을 삭제 조치하였습니다.
> [FE] FIX: SearchBarList에서 사용하는 API를 cabinets-simple API로 변경 #1238

- frontend/src/api/axios/axios.custom.ts
- frontend/src/components/LentLog/AdminCabinetLentLog.tsx
- frontend/src/components/LentLog/AdminLentLog.tsx
- frontend/src/components/LentLog/AdminUserLentLog.tsx
- frontend/src/components/LentLog/LogTable/AdminCabinetLogTable.tsx
- frontend/src/components/LentLog/LogTable/LogTable.tsx
- frontend/src/hooks/useMenu.ts
- frontend/src/pages/admin/AdminLayout.tsx
https://github.com/innovationacademy-kr/42cabi/issues/1129
- 10개씩 lentlog를 받아 오는 것을 8개로 수정하였습니다. (이렇게 받아오는 게 일반 화면에서 스크롤이 생기지 않아서 더 이쁨)
- min-height를 설정하여 화면의 높이가 줄었을 때 대여기록이 겹쳐지는 부분을 해결하였습니다.
- 클릭 시 closeLent가 적용되지 않고 있는 부분을 적용되도록 변경했습니다.
- 아래에 위치했던 버튼을 리스트 안으로 옮겼습니다.
- 
사진과 같이 다음 페이지가 있으면 그라데이션이 나타납니다.
> [FE] : fix lentLog layout 화면 높이에 따른 깨짐 수정

- frontend/src/components/LentLog/LogTable/LogTable.tsx
- [ x] FIX : 기존 기능 수정 및 정상 동작을 위한 간단한 추가, 수정사항
- 반납 시간이 NULL 일 경우에 유닉스 초기 시간 대신 "-" 출력
https://github.com/innovationacademy-kr/42cabi/issues/1266
> [FE] FIX: 반납시간이 NULL 일 시 "-" 출력되게 수정 #1266

- frontend/src/components/Modals/LentModal/LentModal.tsx
- frontend/src/components/Modals/Modal.tsx
- frontend/src/components/Modals/PasswordCheckModal/PasswordCheckModal.tsx
- frontend/src/components/Modals/ReturnModal/ReturnModal.tsx
- 이전에는 위 사진처럼 대여 / 반납 시 서버에서 응답이 오기 전에 버튼을 여러번 눌러 같은 요청을 반복적으로 보낼 수 있는 문제가 있었습니다. 이를 막기 위해 Modal 에서 isLoading 을 props 로 받게 하여 응답이 올 때까지 버튼을 disable 시켰습니다.
- Modal 컴포넌트 내의 IModalContents 에서 변수명에 오타가 있어 이를 수정하였습니다. (cancleBtnText -> cancelBtnText)
https://github.com/innovationacademy-kr/42cabi/issues/1315
> [FE] FIX: 대여 / 반납 시 버튼을 연속적으로 눌러 같은 요청을 반복적으로 보내지 못하도록 수정 #1315

- frontend/src/components/LentLog/AdminLentLog.tsx
https://github.com/innovationacademy-kr/42cabi/issues/1303
- admin home에서 사용정지 유저의 대여기록을 누르면 사물함 대여기록이라 표시되면서 유저의 대여 기록이 보이지 않는 문제 해결
- 검색을 통한 결과가 아니면 CABINET기록만을 보여주고 있었어서 이 부분을 수정하였습니다.
- 코드 한 줄 수정이었지만 이거 찾기까지 좀 힘들었삼 ㅎ
> [FE] BUG : admin_home에서 사용정지 유저 사용기록 나오지 않는 버그 수정 #1303

- frontend/src/components/Modals/PasswordCheckModal/PasswordCheckModal.container.tsx
- frontend/src/components/Modals/PasswordCheckModal/PasswordCheckModal.tsx
- 이전 이슈 #1315 에서 대여 / 반납 시 버튼을 연속적으로 눌러 같은 요청을 반복적으로 보내지 못하도록 수정하고 #1320 의 PR 로 dev 로 Merge 했으나, 3층은 비밀번호 확인 모달을 통해서 반납이 이루어져 3층에서는 여전히 사물함 반납 요청을 반복적으로 보낼 수 있었습니다.
- #1315 에서 모달을 수정한 것과 동일한 로직으로 PasswodCheckModal 에서 isLoading 을 props 로 받게 하여 응답이 올 때까지 버튼을 disable 시켰습니다.
https://github.com/innovationacademy-kr/42cabi/issues/1315
> [FE] FIX: 3층 비밀번호 초기화 후 반납 시에도 같은 요청을 반복적으로 보내지 못하도록 수정 #1315 

- frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.container.tsx
- frontend/src/components/MapInfo/MapItem/MapItem.tsx
- 기존에는 LocalStorage 에 CurrentFloor 과 CurrentSection 을 저장하여 층 이동과 섹션 이동을 감지하고 있어 지도에서 Section 을 변경하고 다른 층을 누르면 CurrentFloor 만 업데이트 되고, CurrentSection 이 이미 LocalStorage 에 존재하므로 Section 을 업데이트 하지 않는 문제가 있었습니다.
- 변경된 로직에서는 층을 변경할 경우 localStorage 의 CurrentSection 과 response data 의 Section 을 비교해, CurrentSection 이 response data 에 존재하면 (e.g. Oasis) 그 Section 으로 이동하고, 아닐 시 그 층의 첫 Section 을 보여줍니다.
- 지도에서 지도 중앙의 층을 클릭할 경우 (e.g. 2F, 3F 등) 존재하지 않는 섹션 (2F, 3F 등) 으로 이동하여 빈 화면이 나타나는 문제를 발견하여 추가로 수정하였습니다.
https://github.com/innovationacademy-kr/42cabi/issues/1269
> [FE] FIX: 지도 클릭 후 층 이동시 localStorage 의 CurrentSection 이 업데이트 되지 않아 해당 층에 없는 Section 을 보여주던 문제 수정 #1269

- frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
- frontend/src/components/TopNav/TopNavButtonGroup/TopNavButtonGroup.tsx
- CabinetInfoArea 에서 연장권 정보를 확인할 수 있게 수정하면서 사물함을 대여중이 아닐 때에도 CabinetInfoArea 모달을 우측 상단 아이콘을 이용해 볼 수 있었는데, Admin 에서도 CabinetInfoArea 모달을 열 수 있는 이슈가 있어 열 수 없도록 수정하였습니다.
- 현재 개인사물함에서만 연장권 사용이 가능한데, 공유사물함에서도 연장권 사용을 가능하게 변경했습니다.
- 대여중인 사물함이 없을 때 개인사물함정보 모달에서 ‘대여’ 및 '닫기' 를 보이지 않게 수정하고 연장권 정보만 확인할 수 있게 변경했습니다.
https://github.com/innovationacademy-kr/42cabi/issues/1362
> [FE] CabinetInfoArea 연장권 위치 수정 및 에러 수정 #1362

- backend/src/main/java/org/ftclub/cabinet/config/GmailProperties.java
- backend/src/main/java/org/ftclub/cabinet/utils/mail/EmailSender.java
- backend/src/test/resources/application.yml
`MimeMessageHelper.setFrom()`의 인자로 `42CABI <이메일@example.com>` 문자열을 넣어 메일 발송 시, 발송자 이름을 `42CABI`로 표시되도록 수정 했습니다.
> [BE] FIX: 메일 발신자 이름이 42CABI로 표시되도록 수정

- frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
- frontend/src/components/CabinetInfoArea/CountTime/CountTime.container.tsx
- frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
- frontend/src/components/Home/ServiceManual.tsx
- frontend/src/components/Modals/InvitationCodeModal/InvitationCodeModal.container.tsx
- frontend/src/components/Modals/LentModal/LentModal.tsx
- frontend/src/pages/MainPage.tsx
https://github.com/innovationacademy-kr/42cabi/issues/1371
- In_session에서 사물함 상세 정보를 바라보지 않고 세션 시간이 지났을 시 자체 새로고침을 눌러서 정보 변경이 바로 가능하게 변경하였습니다.
- In_session인 경우에는 userState의 cabinetId를 업데이트 하지 않고 null로 두어서 대여가 성공한 경우에만 업데이트를 통해 userState의 cabinetId와 myCabinetInfoState의 cabinetId가 다른 경우에만 새로고침 버튼에서 층 정보와 lent/me를 같이 요청해서 정보의 변경이 바르게 이루어지도록 수정하였습니다.
- 따라서 공유 사물함을 대여할 시(아직 대여 완료가 안되었을 때)는 userState를 업데이트 하지 않습니다.
> [FE] FIX : IN_SESSION에서 상태 변경 시 올바른 상태 변경 가능#1371

- backend/src/main/java/org/ftclub/cabinet/dto/MyCabinetResponseDto.java
- backend/src/main/java/org/ftclub/cabinet/exception/ExceptionStatus.java
- backend/src/main/java/org/ftclub/cabinet/lent/controller/LentController.java
- backend/src/main/java/org/ftclub/cabinet/lent/domain/LentPolicyImpl.java
- backend/src/main/java/org/ftclub/cabinet/lent/repository/LentOptionalFetcher.java
- backend/src/main/java/org/ftclub/cabinet/lent/repository/LentRedis.java
- backend/src/main/java/org/ftclub/cabinet/lent/repository/LentRepository.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/mapper/CabinetMapper.java
사물함 대여 시 해당 사물함을 마지막으로 대여한 이전 사용자의 userName을 보여주는 로직을 추가하였습니다.
접근 방식
- 사물함 반납 시 해당 사물함의 cabinetId와 반납 유저의 userName을 key:value 형태로 redis에 저장합니다.
- 유저가 사물함을 대여 할 시에 redis에서 cabinetId로 해당 사물함을 이용한 마지막 유저의 userName을 가져옵니다.
https://github.com/innovationacademy-kr/42cabi/issues/#1368
> [BE] 사물함 대여 시 직전 사물함 유저 기록 조회 로직 추가 #1368

- frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
- frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
- frontend/src/types/dto/cabinet.dto.ts
- 현재 나의 사물함을 이전에 사용한 유저를 보여주는 기능 추가
- 호버하면 "이전 사용자"라는 문구가 나타나고 클릭 시 이름이 보이도록 하였습니다.
> [FE] FEAT 이전 사용자 보여주기 

- backend/src/main/java/org/ftclub/cabinet/alarm/DiscordAlarmMessage.java
- backend/src/main/java/org/ftclub/cabinet/alarm/DiscordWebHookMessenger.java
- backend/src/main/java/org/ftclub/cabinet/log/DiscordWebHookMessenger.java
- backend/src/main/java/org/ftclub/cabinet/log/LogParser.java
- backend/src/main/java/org/ftclub/cabinet/log/WebHookTestController.java
- backend/src/test/resources/application.yml
https://github.com/innovationacademy-kr/42cabi/issues/1384
- application profile에 webhook.discord-admin 부분이 추가되었습니다.
- 단순히 웹훅 url에 body("content" : "문구")를 전송하는 API입니다. 어드민의 경우 로깅이 진행되는데 그렇게 많은 호출이 일어나지 않을 것이라고 생각해서 단순한 POST로 사용했습니다.
> [BE] Discord Webhook Messenger 추가

- backend/src/main/java/org/ftclub/cabinet/lent/domain/LentHistory.java
- backend/src/main/java/org/ftclub/cabinet/lent/domain/LentPolicyImpl.java
- backend/src/main/java/org/ftclub/cabinet/utils/DateUtil.java
- backend/src/test/java/org/ftclub/cabinet/lent/domain/LentHistoryUnitTest.java
- backend/src/test/java/org/ftclub/cabinet/lent/domain/LentPolicyUnitTest.java
- 기존에 사물함 만료일이 대여일 + 대여일자의 시/분/초로 설정되어 있었던 부분을 만료일 당일 23시59분59초로 설정되도록 수정하였습니다.
- 사물함 연체일이 하루 적게 나오는 로직을 수정하였습니다.
> [BE] HOTFIX : 사물함 expiredAt이 만료일 23시59분59초가 되도록 수정 및 연체일이 하루 적게 나오는 로직 수정

- frontend/src/App.tsx
- frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
- frontend/src/components/Card/Card.tsx
- frontend/src/components/Card/CardStyles.ts
- frontend/src/components/Card/ExtensionCard/ExtensionCard.container.tsx
- frontend/src/components/Card/ExtensionCard/ExtensionCard.tsx
- frontend/src/components/Card/LentInfoCard/LentInfoCard.container.tsx
- frontend/src/components/Card/LentInfoCard/LentInfoCard.tsx
- frontend/src/components/Card/NotificationCard/NotificationCard.container.tsx
- frontend/src/components/Card/NotificationCard/NotificationCard.tsx
- frontend/src/components/Card/ProfileCard/ProfileCard.container.tsx
- frontend/src/components/Card/ProfileCard/ProfileCard.tsx
- frontend/src/components/Card/ThemeColorCard/ThemeColorCard.container.tsx
- frontend/src/components/Card/ThemeColorCard/ThemeColorCard.tsx
- frontend/src/components/Common/ToggleSwitch.tsx
- frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.tsx
- frontend/src/components/LeftNav/LeftSectionNav/LeftSectionNav.tsx
- frontend/src/components/Modals/ExtendModal/ExtendModal.tsx
- frontend/src/components/Modals/OverduePenaltyModal/OverduePenaltyModal.tsx
- frontend/src/components/TopNav/TopNavButtonGroup/TopNavButtonGroup.tsx
- frontend/src/pages/ProfilePage.tsx
- frontend/src/pages/admin/SearchPage.tsx
- frontend/src/utils/dateUtils.ts
- 프로필 페이지 추가
- 정보를 표시할 Card 컴포넌트를 만든 후 이를 기반으로 ProfileCard, ExtensionCard, LentInfoCard, ThemeColorCard, NotificationCard 를 만들어 ProfilePage 간소화
- 알림 (NotificationCard) 외 다용도로 쓰일 수 있는 ToggleSwitch 컴포넌트 추가
- 서브모듈 FE 에 연장권 기한 업데이트
https://github.com/innovationacademy-kr/42cabi/issues/1410
> [FE] FEAT: 프로필 페이지 추가 #1410

- frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
https://github.com/innovationacademy-kr/42cabi/issues/1425
- 내 사물함의 세션이 만료되어서 다른 사람이 들어가서 새로운 세션이 생겼을 때, 사물함 상태의 변화는 없기에 데이터가 업데이트 되지 않는 문제를 lent정보에서 userid를 순회하며 내가 있지 않으면 내 사물함 데이터를 업데이트 하도록 추가하였습니다.
> [FE] FIX: 공유 사물함 랜더링 추가문제 해결

- frontend/src/App.tsx
- frontend/src/api/axios/axios.custom.ts
- frontend/src/assets/images/alarm.svg
- frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.container.tsx
- frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.tsx
- frontend/src/pages/Layout.tsx
- frontend/src/pages/PendingPage/PendingPage.tsx
- frontend/src/pages/PendingPage/components/FloorContainer.tsx
- frontend/src/pages/PendingPage/components/Timer.tsx
- frontend/src/recoil/atoms.ts
1. 오픈 예정 및 사용 가능한 사물함들을 층 별로 모아볼 수 있는 새로운 페이지를 생성하였습니다.
2. 오픈 예정 사물함은 오픈 시간(현재 오후 1:00:00)에 맞춰 사용 가능한 사물함으로 변경됩니다.
3. 타이머의 시간은 로그인 후 최초 접속 시 서버 시간을 받아옵니다(전역 상태로 관리).
4. 전역 상태로 관리되는 서버 시간은 Layout 컴포넌트에서 Interval로 지속적으로 현재 시간을 업데이트해 줍니다
-> 추후 다른 컴포넌트에서 서버 시간 사용이 필요할 때 사용하시면 됩니다.
https://github.com/innovationacademy-kr/42cabi/issues/1414
> [FE] FEAT: PendingPage 추가

- frontend/src/components/Card/CardStyles.ts
- frontend/src/components/Card/LentInfoCard/LentInfoCard.container.tsx
- frontend/src/components/Card/LentInfoCard/LentInfoCard.tsx
- 연체 시 CabinetInfoArea 처럼 연체일을 표시하는 기능을 프로필 페이지에 추가
https://github.com/innovationacademy-kr/42cabi/issues/1453
> [FE] FIX: 연체 시 프로필 페이지에서 연체 기간을 표시하도록 수정 #1453

- backend/database/cabi_local.sql
- backend/src/main/java/org/ftclub/cabinet/dto/LentExtensionResponseDto.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/LentExtension.java
- backend/src/main/java/org/ftclub/cabinet/user/repository/LentExtensionOptionalFetcher.java
- backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
- backend/src/test/java/org/ftclub/cabinet/user/controller/UserControllerTest.java
- backend/src/test/java/org/ftclub/cabinet/user/service/LentExtensionServiceTest.java
- backend/src/test/java/org/ftclub/cabinet/user/service/UserFacadeServiceTest.java
https://github.com/innovationacademy-kr/42cabi/issues/1457
특정 일자에 적용되는 스케줄링을 통해서, 일괄적으로 리포지터리를 deleteAll하던 로직을,
현재 정책에 맞는 비즈니스 로직(expiredAt이 측정 시각 기준으로 지난 경우)에 맞추어 soft delete하도록 변경하였습니다.
이후에 있을 리팩토링을 고려해서 우선 중복되는 필터 로직으로 작성해두었습니다(이후에 개선할 여지가 있다고 생각합니다).
soft delete를 결정한 이유는 연장권이 어떻게 발급되었고, 얼마나 이용되었고 등에 대한 데이터 수집을 위함입니다.
현재 테스트 환경이 잘 깨져서 자동화된 테스트는 굴려보지 못했지만, 실제 로컬환경에서 테스트해본 결과 잘 동작하는 것을 확인했습니다.
이후에 dev에 업로드 이후에도 같이 QA하듯이 테스트해봐야 할 것 같습니다.
> [BE] 연장권 삭제 로직 변경 및 변경에 따른 조회 로직 수정

- backend/src/main/java/org/ftclub/cabinet/cabinet/controller/CabinetController.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/repository/CabinetComplexRepository.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/repository/CabinetOptionalFetcher.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/repository/CabinetRepository.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/firebase/FCMInitializer.java
- backend/src/main/java/org/ftclub/cabinet/lent/domain/LentHistory.java
- backend/src/main/java/org/ftclub/cabinet/lent/repository/LentOptionalFetcher.java
- backend/src/main/java/org/ftclub/cabinet/lent/repository/LentRepository.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/statistics/service/StatisticsFacadeServiceImpl.java
- backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionServiceImpl.java
- backend/src/test/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeServiceUnitTest.java
- backend/src/test/java/org/ftclub/cabinet/lent/repository/LentRepositoryTest.java
- backend/src/test/java/org/ftclub/cabinet/lent/service/LentServiceImplTest.java
- backend/src/test/java/org/ftclub/cabinet/statistics/service/StatisticsFacadeServiceUnitTest.java
- backend/src/test/java/org/ftclub/cabinet/user/service/LentExtensionServiceTest.java
- [X] FEAT : 새로운 기능 추가 및 개선
수정사항
1. cabinet pending 사물함 조회 로직 수정
2. Cabinet, LentHistory 리팩토링 
- repository 이름 통일 - 단건 조회 find, 다건 조회 findAll
- 층 전체 조회 로직 가독성 개선
- 미사용 코드 삭제
3. 로컬에서 테스트 돌리면 FCM Initializer 때문에 동작 안되는 현상 임시 해결(추후 리팩토링 필요)
> [BE] pending 조회 로직 수정 및 cabinet, lent 리팩토링

- frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
- frontend/src/components/Modals/MemoModal/MemoModal.tsx
- frontend/src/components/TopNav/TopNavButtonGroup/TopNavButtonGroup.tsx
https://github.com/innovationacademy-kr/42cabi/issues/1428
- 개인 사물함도 title 변경이 가능하도록 기능을 수정하였습니다. 
- 기존에 공유 사물함과 title 로직이 있었고, 개인 사물함이면 title을 변경할 수 있는 부분을 보이지 않게만 해놓은 상태였기에 이 부분을 지워서 개인 사물함도 title변경이 가능하도록 수정하였습니다.
- top에 있는 내 사물함을 눌렀을 때 memo를 초기화하던 코드가 남아있어서 이 부분도 지워서 memo가 잘 남도록 하였습니다.
> [FE] FEAT: 개인 사물함도 title 을 변경할 수 있도록 기능 추가 #1428

- frontend/src/components/Common/MultiToggleSwitch.tsx
- frontend/src/components/Modals/PasswordCheckModal/PasswordContainer.tsx
- frontend/src/pages/PendingPage/PendingPage.tsx
- useRef 를 사용하여 MultiToggleSwitch 내의 버튼에만 style 변경이 적용되도록 MultiToggleSwitch 를 수정했습니다.
- 사용가능 페이지에서 localStorage 에 있는 층의 사물함 데이터를 요창하지 못하도록 사용가능 페이지 진입 시 층 정보를 제거했습니다.
https://github.com/innovationacademy-kr/42cabi/issues/1512
> [FE] FIX: MultiToggleSwitch 이 페이지 전체 button 에 영향을 주지 못하도록 수정#1512

- backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeService.java
1시 이후에 반납해도 사용 가능 사물함에서 오픈 예정이 안보이는 현상 수정
> [HOTFIX] 1시 이후 반납된 사물함이 pending에서 안보이는 것 수정

- backend/src/main/java/org/ftclub/cabinet/alarm/config/AlarmProperties.java
- backend/src/main/java/org/ftclub/cabinet/event/RedisExpirationEventListener.java
- backend/src/main/java/org/ftclub/cabinet/utils/overdue/manager/OverdueManager.java
- backend/src/main/java/org/ftclub/cabinet/utils/overdue/manager/OverdueType.java
- backend/src/main/java/org/ftclub/cabinet/utils/scheduler/SystemScheduler.java
https://github.com/innovationacademy-kr/42cabi/issues/1518
연체 전후 1, 3, 7일차에도 알람을 보내도록 기능 변경
> [BE] FEAT: 반납일 7,3,1 일전 미리 알람주도록 기능 추가#1518

- frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
- CabientInfoArea 에서 해당 컴포넌트를 이용해 모달 (사물함 관리, 대여, 반납 등) 을 열고, 브라우저 뒤로가기를 눌렀을 시 모달이 정상적으로 닫히지 않아 다른 사물함을 클릭했을 시 마지막으로 열었던 모달이 그대로 랜더링되는 이슈가 있어 이를 useLocation() 을 사용해 URL 변경 시 모달 값을 초기화하도록 변경했습니다
- 모달 값을 초기화 할 시 { lentModal: false, unavailableModal: false ... } 등으로 나열하는 것이 효율적이지 않다고 판단하여 ICurrentModalStateInfo 와 IAdminCurrentModalStateInfo interface 를 초기화해 Object 를 반환하는 함수를 만들고 이를 사용하도록 변경하였습니다.
https://github.com/innovationacademy-kr/42cabi/issues/1567
> [FE] FIX: CabinetInfoArea 에서 뒤로가기 모달이 정상적으로 닫히지 않던 문제 수정 #1567

- frontend/index.html
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/TrackPageView.tsx
- frontend/src/api/analytics/PageTracker.tsx
- frontend/src/components/Card/NotificationCard/NotificationCard.container.tsx
- frontend/src/components/Search/SearchItemByIntraId.tsx
- frontend/src/pages/Layout.tsx
> Closed #1565 
이전 방식으로는 Index.html에 script를 직접 적용해서 구글 애널리틱스에 추적이 되었습니다.
main만 추적이 되도록 메인 index.html에만 적용해뒀었는데, 버전관리를 진행하면서 로컬,dev에도 적용이 되어서 main만 구분이 안되었습니다.
사실 현재 적용되어 있는 것들은 main,dev,local 모든 이벤트를 추적하고 있는 상태였습니다.
이번 수정으로  .env에 VITE_GA_TRACKING_ID를 통해서 추적되도록 변경했습니다.
이전에 사용중인 GA-ID로는 main만 추적되도록 적용했으며, 
테스트용으로 만든 다른 GA-ID는 dev에 연결되도록 dev.env와 .env에 추가했습니다. 
로컬 작업중에는 추적하지 않도록 조건문을 추가해서 막았습니다.
```js
!window.location.hostname.includes("localhost")
```
react-ga4를 사용했으며, path(라우터)가 변경될때마다 이벤트를 추적하도록 변경했습니다.
- 예시
GA를 위한 파일을 구분화 했습니다.
PageTracker로 컴포넌트화 한 이유는 처음에는 custom Hook으로 빼려고 했으나,
useLocation를 사용은 Router 내에서만 사용할 수 있어서 App.tsx에 자체에서 실행하려고 하면 오류가 납니다.
그렇기 때문에 따로 컴포넌트로 만들어서 routers 내부에 적용하는 방식으로 처리했습니다.
컴포넌트 형태이지만 실제 역할은 view를 그리기 위함이 아닌 페이지, 이벤트 추적을 위한 코드가 들어 있어서, 파일을 …
> [FE] FEAT: 구글 애널리틱스 고도화 #1565

- frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
- 문제: 동아리 사물함 페이지가 구현 및 적용 된 이후에 반납 시 사물함 title (동아리 명) 이 초기화되나, 이전에 할당한 동아리 사물함 (42cabi, 관리용 등) 은 title 이 초기화되지 않아 Status 가 AVAILABLE 임에도 '동아리 대여' 대신 '반납' 버튼이 출력됨.
- 하위 호환성을 위해 대여 판별식에 Status 도 확인하도록 수정
https://github.com/innovationacademy-kr/42cabi/issues/1574
> [FE] FIX: 동아리 사물함이 비었을 때 반납이 출력되는 이슈 수정 #1574

- frontend/src/components/TopNav/TopNav.tsx
- frontend/src/components/TopNav/TopNavButtonGroup/TopNavButton/TopNavButton.tsx
- frontend/src/components/TopNav/TopNavButtonGroup/TopNavButtonGroup.tsx
내 사물함 버튼을 클릭 시, 우측 CabinetInfoArea 에 표시할 케비넷을 '나의 케비넷' 으로 변경하는데, 이때:
```
setMyInfo((prev) => ({ ...prev, cabinetId: null }))
```
recoil state 인 myInfo 를 항상 업데이트 하고 있었기 때문에 렌더링이 두번 발생하면서 깜빡이는 것 처럼 보이는 현상을 필요할 때만 myInfo 를 업데이트하도록 변경했습니다.
https://github.com/innovationacademy-kr/42cabi/issues/1576
> [FE] FIX: 내 사물함 버튼 클릭 시 버튼이 깜빡이는 문제 수정 #1576

- backend/src/main/java/org/ftclub/cabinet/log/AllRequestLogInterceptor.java
https://github.com/innovationacademy-kr/42cabi/issues/1583
AllRequestLogInterceptor NPE가 발생하는 버그 수정했습니다.
버그 원인은 `payloadJson`의 유효성 검증 로직의 오류였습니다.
AllRequestLogInterceptor에서 tokenValidator를 통해 token의 payload 정보(payloadJson)를 JSON 형식으로 받아오는데,
이때 payloadJson가 빈 문자열이거나, name 정보가 존재하지 않으면 NPE가 발생합니다.
이 버그를 재현하려면 브라우저 쿠키에 access_token 필드에 JWT 형식은 맞으나 payload에 name 정보가 없는 토큰을 넣고 요청해야 하기 때문에 프러덕션에서 발생할 확률은 매우 낮습니다만, 그래도 버그 수정하고 잘 동작하는 것까지 확인했습니다.
> [BE] BUG: AllRequestLogInterceptor NPE 수정 #1583

- backend/src/main/java/org/ftclub/cabinet/alarm/discord/DiscordWebAlarmMessage.java
- backend/src/main/java/org/ftclub/cabinet/alarm/discord/DiscordWebHookMessenger.java
- backend/src/main/java/org/ftclub/cabinet/auth/filter/CachingRequestBodyFilter.java
- backend/src/main/java/org/ftclub/cabinet/auth/service/AdminOauthService.java
- backend/src/main/java/org/ftclub/cabinet/exception/ExceptionController.java
- backend/src/main/resources/log4j2-prod.xml
https://github.com/innovationacademy-kr/42cabi/issues/1593
사진과 같이 확인된(Checked) 에러가 디스코드로 알림을 오는 부분이 불편하다고 느껴, 모든 에러 로그를 알림보내지 않도록 `log4j2.xml`을 수정했습니다.
다음과 같이 확인되지 않은 에러만 (서버측 에러의 확률이 높은 에러) 500 에러로 표시하여 응답하고, ERROR 레벨로 로그를 남긴 후, 디스코드로 알림을 보내도록 개선했습니다.
또한 `ExceptionController`가 `ResponseEntityExceptionHandler`를 구현하도록 하여 우리가 처리할 수 없는 Spring MVC에서 발생시키는 클라이언트 측 에러를 `커스텀 에러 형식(statusCode, message, error)`에 맞게 변환하여 응답하도록 개선했습니다.
이 역시 확인되지 않은 500번대 에러만 ERROR 레벨로 로그를 남기고 알림을 보내고, 그렇지 않은 경우에는 WARN 레벨로 로그를 남기도록 구현했습니다.
> [BE] FIX: 글로벌 에러 핸들링 개선 & 필요한 오류 알림만 상세화하여 보내도록 수정 #1593

- backend/src/main/java/org/ftclub/cabinet/alarm/discord/DiscordScheduleAlarmMessage.java
- backend/src/main/java/org/ftclub/cabinet/alarm/discord/DiscordWebHookMessenger.java
- backend/src/main/java/org/ftclub/cabinet/dto/ActiveLentHistoryDto.java
- backend/src/main/java/org/ftclub/cabinet/lent/domain/LentHistory.java
- backend/src/main/java/org/ftclub/cabinet/mapper/LentMapper.java
- backend/src/main/java/org/ftclub/cabinet/utils/overdue/manager/OverdueManager.java
- backend/src/main/java/org/ftclub/cabinet/utils/scheduler/SystemScheduler.java
https://github.com/innovationacademy-kr/42cabi/issues/1597
`daysFromExpireDate`값이 null이 될 수 있어 발생한 오류였습니다. (사용하는 측에서 null의 프로퍼티 참조 시도 -> NPE 발생!)
`LentHistory.getDaysFromExpireDate()` 에서 null을 반환하는 것 자체가 안티 패턴이라고 생각합니다.
**그런데** 이미 음수 자체가 `연체전`이라는 의미를 가지고 있고, null 값 역시 `만료일 미설정`이라는 의미를 가지고 있어 null 반환 대신 사용할 적절한 대안을 찾지 못했어요.....
그래서 NPE 발생하는 부분 예외처리를 적용하고, 주석과 `@Nullable` 마크업 어노테이션을 달아 명시해두었습니다..!
제 딴에는 최선이라고 생각했지만... 혹시 다른 해결 방안이 있으시다면 말씀해주세요!!
핫픽스이기는 하지만 스케줄러가 자정에 돌기 때문에 자정 전까지는 merge 하지는 않겠습니다.
또 스케줄러 함수의 루프 내에서 태스크 처리 중 에러가 발생하면 디스코드로 웹 훅을 전송하고, 루프가 중단되지 않도록 설정했습니다..! (고의적으로 에러를 발생시킨 사진입니다.)
> [BE] HOTFIX: 연체 스케줄러 NPE 수정 #1597

- backend/src/main/java/org/ftclub/cabinet/dto/ActiveLentHistoryDto.java
- backend/src/main/java/org/ftclub/cabinet/lent/domain/LentHistory.java
- backend/src/main/java/org/ftclub/cabinet/mapper/LentMapper.java
- backend/src/test/java/org/ftclub/cabinet/lent/domain/LentHistoryTest.java
https://github.com/innovationacademy-kr/42cabi/issues/1597
- 레거시 정책 코드 제거 ex. LentHistory.isSetExpired() 제거
- 실제로 NPE 문제를 유발했던 LentMapper의 필드를 ActiveLentHistoryDto의 daysFromExpireDate와 동일하도록 수정
> [BE] FIX: 연체 처리 NPE 오류 수정 #1597

- backend/src/main/java/org/ftclub/cabinet/exception/ControllerException.java
- backend/src/main/java/org/ftclub/cabinet/exception/CustomServiceException.java
- backend/src/main/java/org/ftclub/cabinet/exception/DomainException.java
- backend/src/main/java/org/ftclub/cabinet/exception/FtClubCabinetException.java
- backend/src/main/java/org/ftclub/cabinet/exception/ServiceException.java
- backend/src/main/java/org/ftclub/cabinet/exception/UtilException.java
- backend/src/main/java/org/ftclub/cabinet/utils/scheduler/SystemScheduler.java
https://github.com/innovationacademy-kr/42cabi/issues/1602
스케줄러 에러 핸들러 측에서 커스텀 에러(확인된 예외)도 error 로그를 찍고, 알림을 보내는 문제가 있었습니다.
커스텀 에러(확인된 예외)에 대한 공통 인터페이스(FtClubCabinetException)를 만든 후 이를 implements 하여 공통 타입으로 만들었습니다.
이후 스케줄러에서 catch 된 에러 타입이 FtClubCabinetException이 아닌 경우에만 error 로그를 찍고 알림을 보내도록 수정했습니다.
로컬에서 인수 테스트를 진행하였고, 정상적으로 동작하는 것을 확인했습니다.
> [BE] FIX: 커스텀 에러 (확인된 예외)는 알림을 발송하지 않도록 수정 #1602

- frontend/src/Cabinet/pages/Layout.tsx
- frontend/src/Cabinet/pages/ProfilePage.tsx
- frontend/src/Cabinet/pages/admin/AdminLayout.tsx
자세한 문제 상황 설명 -> https://github.com/innovationacademy-kr/42cabi/issues/1551
`Layout`에서 로컬스토리지에서 `main-color`의 값이 `"var(--default-main-color)"`이면 해당 아이템 삭제. (`main-color` 뿐만 아니라 `sub-color`, `mine-color`도 마찬가지)
```
localStorage.getItem("main-color") === "var(--default-main-color)" && localStorage.removeItem("main-color");
```
> [FE] FEAT: 로컬스토리지에 --default-main-color값 있을 경우 해당 아이템 지움#1551

- frontend/src/Cabinet/pages/admin/AdminLayout.tsx
>어드민에서 사용정지 유저가 아닌 반납지연 유저를 검색하고 사물함 정보 버튼을 눌렀을때 대여 중이 아닌 사용자가 아닌 대여중인 사물함의 구역이 떠야함.
https://github.com/innovationacademy-kr/42cabi/issues/1635
> [FE] FIX: intra id로 검색하고 사물함 정보 눌렀을때 잘못된 cabinetInfoArea 뜨는것 해결#1604

- backend/src/main/java/org/ftclub/cabinet/admin/item/service/AdminItemFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/admin/lent/service/AdminLentFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemFacadeService.java
- backend/src/main/java/org/ftclub/cabinet/item/service/ItemRedisService.java
- backend/src/main/java/org/ftclub/cabinet/user/domain/User.java
- backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionManager.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserCommandService.java
- backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeService.java
https://github.com/innovationacademy-kr/42cabi/issues/1647
- LentExtensionManager 
issueLentExtension() 연장권 만큼의 재화 지급
연장권 발급시 2000 코인 지급 user에 직접 add 형태로 변경
- ItemFacadeService, 
- AdminItemFacadeService
assignItem()  아이템 지급
Redis 관련함수 삭제
```itemRedisService.getCoinAmount(userId);```
```userQueryService.getUser(userId).getCoin();```
```userCommandService.updateCoinAmount(userId, price);``` 
함수를 이용하도록 수정
ItemFacadeService
purchaseItem() 아이템 구매
> [BE] REFACTOR: 유저 현재 보유 재화를 REDIS -> RDBMS 이전 #1647

- frontend/src/Cabinet/components/Modals/Modal.tsx
- 이사권 사용실패 모달창에서 링크를 클릭해 까비상점으로 이동 시, 1040px 이하에서 상점으로 이동 후 Menu Background 가 해제되지 않음
- 모달 내 링크로 다른 Route 이동 시, `closeAll()` 로 Menu Background 해제
https://github.com/innovationacademy-kr/42cabi/issues/1668
> [FE] BUG: 모달에서 링크로 이동 시 모든 창을 닫도록 closeAll 추가 #1668

- frontend/src/Cabinet/components/Common/LoadingAnimation.tsx
- frontend/src/Cabinet/pages/MainPage.tsx
- frontend/src/Cabinet/pages/admin/AdminMainPage.tsx
- MainPage에서 isLoading의 값에 따라 보이는 컴포넌트 변경
- LoadingAnimation에 스크롤 기능 제거하기 위해 `hidden` 추가
https://github.com/innovationacademy-kr/42cabi/issues/1669
> [FE] FIX: 새로고침 버튼 누를 때 나타나는 스크롤바 제거

- frontend/src/main.tsx
현재 Sentry의 environment는 이분법적으로, local 여부에 따라 `local`과 `production`으로 나뉩니다.
`production` 및 `local` 환경과는 별도로 dev 브랜치 이슈만 추적하고 싶을때 `development`에서 확인할 수 있도록
**`production`에서 `development`와 `production을` 분리**했습니다.
https://github.com/innovationacademy-kr/42cabi/issues/1709
> [FE] FEAT: 기존 Sentry environment에서 development 분리 #1709

- frontend/src/main.tsx
**sentry sample rate 조정**
firebase error 발생 원인 확인하려하는데, replay 영상이 센트리에 많이 기록돼있지 않아서 추적이 어려움.
-> `tracesSampleRate`, `replaysOnErrorSampleRate` 1로 올리고, `replaysSessionSampleRate`는 에러 확인과 관련이 없는 것 같아 하향 조정.
> [FE] ETC: Sentry traces sample, error replay sample 비율 상향 #1709

- frontend/src/Cabinet/components/CabinetList/CabinetList.container.tsx
- frontend/src/Cabinet/components/LeftNav/LeftMainNav/LeftMainNav.tsx
- frontend/src/Cabinet/components/LeftNav/LeftSectionNav/LeftSectionNav.tsx
- frontend/src/Cabinet/components/MapInfo/MapFloorSelectOption/MapFloorSelectOption.tsx
- frontend/src/Cabinet/components/MapInfo/MapInfo.tsx
- frontend/src/Cabinet/pages/AvailablePage.tsx
- frontend/src/Cabinet/pages/MainPage.tsx
- frontend/src/Cabinet/pages/admin/AdminMainPage.tsx
- LeftNav 에 4층 제외 (admin에서는 제외 X)
- map 도 4층 제외
- 임의로 localStorage를 통한 4층 접근 시
1. 이용불가 안내 표시
2. 하트, 위치안내 아이콘 제거
3. map 은 2층을 default로 설정 (더 좋은 방법 추천받아요~)
https://github.com/innovationacademy-kr/42cabi/issues/1703
> [FE] 4층 사물함 접근 제한 #1703

- backend/database/cabi_local.sql
- frontend/src/Presentation/components/Modals/EditStatusModal/EditStatusModal.tsx
- frontend/src/Presentation/components/Modals/RegisterModal/RegisterModal.tsx
- frontend/src/Presentation/components/Register/DropdownDateMenu.tsx
- frontend/src/Presentation/components/Register/DropdownTimeMenu.tsx
- frontend/src/Presentation/pages/DropdownMenu.tsx
- frontend/src/Presentation/pages/RegisterPage.tsx
[수요지식회]
1. 수지회 신청 폼에서 신청 버튼을 누를 때, 신청한 날짜에서 연도는 신청 날짜 기준으로 보내지는 부분 수정
- `getFullYear()` 사용 -> api에서 받아오는 값을 `y/M/d` 형식으로 바꾸어 출력시만 `M/d`로 변형하고, 연도도 해당 정보에서 가져오는 것으로 변경
2. `presentationLocation`의 기본 값에 대해 수지회를 만들때 정해졌던 3층이 아닌 지하 1층으로 바뀜에 따라 수정
3. 로컬에서 테스트하기 위한 케이스 5월까지 추가 (-> 현재를 기준으로 3개월만 보이는지 확인용)
[주의 해야 할 부분]
1. 한달에 발표가 재단 사정 상 2번이 불가능 한 경우 -> 추가, 삭제 관련 내용이 필요함
2. 현재 백엔드에서는 valid-date에 대해 현재 날(day) 기준, 3개월 이내의 더미에 대해 가능한 날짜에 대해 반환
- 만약에, 현재 스케쥴러(1달에 1번 1달치)에서 변경될 경우(3개월 이후의 더미가 생성되어 있을 경우), 백엔드에서는 가능한 날짜로 넘어와서 신청이 되어도, 프론트 화면에서 볼 수 없음
- 즉, 이 경우에는 valid-date의 기준을 '달(month)'을 기준으로 변경해야 함
https://github.com/innovationacademy-kr/42cabi/issues/1718
> [FE] FIX: 수지회 신청 날짜 형식 수정 #1718

- backend/src/main/java/org/ftclub/cabinet/admin/dto/AdminPresentationSlotUpdateRequestDto.java
- backend/src/main/java/org/ftclub/cabinet/admin/dto/PresentationSlotUpdateServiceDto.java
- backend/src/main/java/org/ftclub/cabinet/admin/presentation/controller/AdminPresentationSlotController.java
- backend/src/main/java/org/ftclub/cabinet/admin/presentation/service/AdminPresentationSlotService.java
- backend/src/main/java/org/ftclub/cabinet/exception/ExceptionStatus.java
- backend/src/main/java/org/ftclub/cabinet/presentation/domain/PresentationSlot.java
- backend/src/test/java/org/ftclub/cabinet/admin/presentation/controller/AdminPresentationSlotControllerTest.java
- backend/src/test/java/org/ftclub/cabinet/admin/presentation/service/AdminPresentationSlotServiceTest.java
https://github.com/innovationacademy-kr/42cabi/issues/1762
어드민 슬롯 수정 기능 추가하였습니다!
각 레이어에 대해 테스트 코드 작성했고, 포스트맨 테스트도 로컬에서나마 진행해보았습니다.
기획때 슬롯 수정하면 슬롯에 연결된 발표도 같이 수정되게 하기로 했는지 정확히 기억이 안나고
아직 발표 수정 기능도 개발이 안돼있어서
일단 발표쪽은 빼고 슬롯부분만 기능 만들었습니다.
크게 추가된 로직은 없어서 그냥 훑어만 보시고 혹시 문제가 있다면 알려주시오.
> 어드민 슬롯 수정 기능 추가/#1762

- backend/src/main/java/org/ftclub/cabinet/admin/presentation/controller/AdminPresentationSlotController.java
- backend/src/main/java/org/ftclub/cabinet/admin/presentation/service/AdminPresentationSlotService.java
- backend/src/main/java/org/ftclub/cabinet/exception/ExceptionStatus.java
- backend/src/main/java/org/ftclub/cabinet/presentation/domain/PresentationSlot.java
- backend/src/test/java/org/ftclub/cabinet/admin/presentation/controller/AdminPresentationSlotControllerTest.java
- backend/src/test/java/org/ftclub/cabinet/admin/presentation/service/AdminPresentationSlotServiceTest.java
https://github.com/innovationacademy-kr/42cabi/issues/#1764
어드민에서 슬롯 삭제하는 기능 구현했습니다.
슬롯에 이미 등록된 발표가 있으면 삭제는 안되는걸로 에러처리 해놨습니다. 
발표쪽에서 등록할때 슬롯에도 등록할수 있도록 PresentationSlot 클래스에 assignPresentation 메서드도 살짝 넣어놨습니다.
테스트 코드 작성, 포스트맨으로 엔드투엔드 테스트까지 완료 했습니다.
슥 보시고 리뷰 해주세요~
> Be/presentation renewal/feat delete slot/#1764

- backend/build.gradle
- backend/src/main/java/org/ftclub/cabinet/admin/presentation/service/AdminPresentationCommentService.java
- backend/src/main/java/org/ftclub/cabinet/admin/presentation/service/AdminPresentationSlotService.java
- backend/src/main/java/org/ftclub/cabinet/presentation/repository/PresentationCommentRepository.java
- backend/src/main/java/org/ftclub/cabinet/presentation/service/PresentationCommentService.java
- backend/src/test/java/org/ftclub/cabinet/admin/presentation/controller/AdminPresentationControllerTest.java
- backend/src/test/java/org/ftclub/cabinet/admin/presentation/controller/AdminPresentationSlotControllerTest.java
- backend/src/test/java/org/ftclub/cabinet/admin/presentation/service/AdminPresentationCommentServiceTest.java
- backend/src/test/java/org/ftclub/cabinet/admin/presentation/service/AdminPresentationSlotServiceTest.java
- backend/src/test/java/org/ftclub/cabinet/presentation/repository/PresentationCommentRepositoryTest.java
- backend/src/test/java/org/ftclub/cabinet/presentation/repository/PresentationSlotRepositoryTest.java
- backend/src/test/java/org/ftclub/cabinet/presentation/service/PresentationCommentServiceTest.java
- backend/src/test/java/org/ftclub/cabinet/presentation/service/PresentationSlotServiceTest.java
- backend/src/test/resources/application.yml
https://github.com/innovationacademy-kr/42cabi/issues/1806  
이번 PR에서는 두 가지 주요 문제를 해결했습니다.
1. **버그 수정**: 발표의 댓글 목록 조회 시, 논리적으로 삭제된 댓글이 필터링되지 않고 그대로 노출되는 문제를 해결했습니다.
2. **환경 개선**: 테스트 실행 시 발생하던 H2 데이터베이스 관련 에러를 수정하여 안정적인 테스트 환경을 구축했습니다.
**1. 삭제된 댓글 조회 버그 수정**  
- **문제 원인**: 댓글을 조회하는 Repository 메서드가 댓글의 삭제 상태 (`isDeleted`)를 확인하지 않아, 삭제 처리된 댓글까지 모두 가져오고 있었습니다.
- **해결 방안**: `PresentationCommentRepository`의 조회 메서드에 `AndDeletedFalse` 조건을 추가하여, 삭제되지 않은 댓글만 조회하도록 수정했습니다.
- `findByPresentationIdOrderByCreatedAtAsc` -> `findByPresentationIdAndDeletedFalseOrderByCreatedAtAsc`
- **테스트 추가**: 변경 사항을 명확하게 검증하기 위해 `PresentationCommentRepositoryTest`를 추가했습니다. 이 테스트는 특정 발표에 속한 댓글 중 **삭제된 댓글은 제외하고 활성화된 댓글만** 정상적으로 조회되는지 확인합니다.
**2. 테스트 H2 데이터베이스 에러 해결**  
- **문제 원인**: 테스트에 사용하는 H2 DB에서 `USER`는 예약어(Reserved …
> [BE] FIX: 삭제된 댓글 조회 버그 수정 및 테스트 DB 환경 개선 #1806
